#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ABP_ChickenPal_Implemantation

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "CoreUObject_structs.hpp"
#include "AnimGraphRuntime_structs.hpp"
#include "Pal_classes.hpp"


namespace SDK
{

// AnimBlueprintGeneratedClass ABP_ChickenPal_Implemantation.ABP_ChickenPal_Implemantation_C
// 0x0750 (0x0E20 - 0x06D0)
class UABP_ChickenPal_Implemantation_C final : public UPalAnimInstance
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x06D0(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	struct FAnimSubsystemInstance                 AnimBlueprintExtension_PropertyAccess;             // 0x06D8(0x0008)()
	struct FAnimSubsystemInstance                 AnimBlueprintExtension_Base;                       // 0x06E0(0x0008)()
	struct FAnimNode_Root                         AnimGraphNode_Root_4;                              // 0x06E8(0x0020)()
	struct FAnimNode_LinkedInputPose              AnimGraphNode_LinkedInputPose_4;                   // 0x0708(0x00C8)()
	struct FAnimNode_Root                         AnimGraphNode_Root_3;                              // 0x07D0(0x0020)()
	struct FAnimNode_LinkedInputPose              AnimGraphNode_LinkedInputPose_3;                   // 0x07F0(0x00C8)()
	struct FAnimNode_Root                         AnimGraphNode_Root_2;                              // 0x08B8(0x0020)()
	struct FAnimNode_LinkedInputPose              AnimGraphNode_LinkedInputPose_2;                   // 0x08D8(0x00C8)()
	struct FAnimNode_LookAt                       AnimGraphNode_LookAt;                              // 0x09A0(0x0250)()
	struct FAnimNode_ConvertLocalToComponentSpace AnimGraphNode_LocalToComponentSpace;               // 0x0BF0(0x0020)()
	struct FAnimNode_ConvertComponentToLocalSpace AnimGraphNode_ComponentToLocalSpace;               // 0x0C10(0x0020)()
	struct FAnimNode_Root                         AnimGraphNode_Root_1;                              // 0x0C30(0x0020)()
	struct FAnimNode_LinkedInputPose              AnimGraphNode_LinkedInputPose_1;                   // 0x0C50(0x00C8)()
	struct FAnimNode_LinkedInputPose              AnimGraphNode_LinkedInputPose;                     // 0x0D18(0x00C8)()
	struct FAnimNode_Root                         AnimGraphNode_Root;                                // 0x0DE0(0x0020)()
	struct FVector                                LookAtWorldLocation;                               // 0x0E00(0x0018)(BlueprintReadOnly, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void UpperOverride(const struct FPoseLink& NativePose, const struct FPoseLink& ActionPose, struct FPoseLink* UpperOverride_0);
	void LookAtOverride(const struct FPoseLink& InPose, const struct FVector& LookAtWorldLocation_0, struct FPoseLink* LookAtOverride_0);
	void ExecuteUbergraph_ABP_ChickenPal_Implemantation(int32 EntryPoint);
	void AnimGraph(struct FPoseLink* AnimGraph_0);
	void AimingOverride(const struct FPoseLink& DefaultPose, const struct FRotator& AimRotator, struct FPoseLink* AimingOverride_0);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"ABP_ChickenPal_Implemantation_C">();
	}
	static class UABP_ChickenPal_Implemantation_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UABP_ChickenPal_Implemantation_C>();
	}
};
static_assert(alignof(UABP_ChickenPal_Implemantation_C) == 0x000010, "Wrong alignment on UABP_ChickenPal_Implemantation_C");
static_assert(sizeof(UABP_ChickenPal_Implemantation_C) == 0x000E20, "Wrong size on UABP_ChickenPal_Implemantation_C");
static_assert(offsetof(UABP_ChickenPal_Implemantation_C, UberGraphFrame) == 0x0006D0, "Member 'UABP_ChickenPal_Implemantation_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(UABP_ChickenPal_Implemantation_C, AnimBlueprintExtension_PropertyAccess) == 0x0006D8, "Member 'UABP_ChickenPal_Implemantation_C::AnimBlueprintExtension_PropertyAccess' has a wrong offset!");
static_assert(offsetof(UABP_ChickenPal_Implemantation_C, AnimBlueprintExtension_Base) == 0x0006E0, "Member 'UABP_ChickenPal_Implemantation_C::AnimBlueprintExtension_Base' has a wrong offset!");
static_assert(offsetof(UABP_ChickenPal_Implemantation_C, AnimGraphNode_Root_4) == 0x0006E8, "Member 'UABP_ChickenPal_Implemantation_C::AnimGraphNode_Root_4' has a wrong offset!");
static_assert(offsetof(UABP_ChickenPal_Implemantation_C, AnimGraphNode_LinkedInputPose_4) == 0x000708, "Member 'UABP_ChickenPal_Implemantation_C::AnimGraphNode_LinkedInputPose_4' has a wrong offset!");
static_assert(offsetof(UABP_ChickenPal_Implemantation_C, AnimGraphNode_Root_3) == 0x0007D0, "Member 'UABP_ChickenPal_Implemantation_C::AnimGraphNode_Root_3' has a wrong offset!");
static_assert(offsetof(UABP_ChickenPal_Implemantation_C, AnimGraphNode_LinkedInputPose_3) == 0x0007F0, "Member 'UABP_ChickenPal_Implemantation_C::AnimGraphNode_LinkedInputPose_3' has a wrong offset!");
static_assert(offsetof(UABP_ChickenPal_Implemantation_C, AnimGraphNode_Root_2) == 0x0008B8, "Member 'UABP_ChickenPal_Implemantation_C::AnimGraphNode_Root_2' has a wrong offset!");
static_assert(offsetof(UABP_ChickenPal_Implemantation_C, AnimGraphNode_LinkedInputPose_2) == 0x0008D8, "Member 'UABP_ChickenPal_Implemantation_C::AnimGraphNode_LinkedInputPose_2' has a wrong offset!");
static_assert(offsetof(UABP_ChickenPal_Implemantation_C, AnimGraphNode_LookAt) == 0x0009A0, "Member 'UABP_ChickenPal_Implemantation_C::AnimGraphNode_LookAt' has a wrong offset!");
static_assert(offsetof(UABP_ChickenPal_Implemantation_C, AnimGraphNode_LocalToComponentSpace) == 0x000BF0, "Member 'UABP_ChickenPal_Implemantation_C::AnimGraphNode_LocalToComponentSpace' has a wrong offset!");
static_assert(offsetof(UABP_ChickenPal_Implemantation_C, AnimGraphNode_ComponentToLocalSpace) == 0x000C10, "Member 'UABP_ChickenPal_Implemantation_C::AnimGraphNode_ComponentToLocalSpace' has a wrong offset!");
static_assert(offsetof(UABP_ChickenPal_Implemantation_C, AnimGraphNode_Root_1) == 0x000C30, "Member 'UABP_ChickenPal_Implemantation_C::AnimGraphNode_Root_1' has a wrong offset!");
static_assert(offsetof(UABP_ChickenPal_Implemantation_C, AnimGraphNode_LinkedInputPose_1) == 0x000C50, "Member 'UABP_ChickenPal_Implemantation_C::AnimGraphNode_LinkedInputPose_1' has a wrong offset!");
static_assert(offsetof(UABP_ChickenPal_Implemantation_C, AnimGraphNode_LinkedInputPose) == 0x000D18, "Member 'UABP_ChickenPal_Implemantation_C::AnimGraphNode_LinkedInputPose' has a wrong offset!");
static_assert(offsetof(UABP_ChickenPal_Implemantation_C, AnimGraphNode_Root) == 0x000DE0, "Member 'UABP_ChickenPal_Implemantation_C::AnimGraphNode_Root' has a wrong offset!");
static_assert(offsetof(UABP_ChickenPal_Implemantation_C, LookAtWorldLocation) == 0x000E00, "Member 'UABP_ChickenPal_Implemantation_C::LookAtWorldLocation' has a wrong offset!");

}

