#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_ActionUnlockCagePalLock

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "BP_ActionSimpleMonoMontage_classes.hpp"
#include "AkAudio_structs.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_ActionUnlockCagePalLock.BP_ActionUnlockCagePalLock_C
// 0x0020 (0x01B0 - 0x0190)
class UBP_ActionUnlockCagePalLock_C final : public UBP_ActionSimpleMonoMontage_C
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame_BP_ActionUnlockCagePalLock_C;       // 0x0190(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class FName                                   flagName;                                          // 0x0198(0x0008)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UAkAudioEvent*                          AkEventUnlockCage;                                 // 0x01A0(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_BP_ActionUnlockCagePalLock(int32 EntryPoint);
	void OnBeginAction();
	void OnEndAction();
	void RotateToLockModel();

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_ActionUnlockCagePalLock_C">();
	}
	static class UBP_ActionUnlockCagePalLock_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_ActionUnlockCagePalLock_C>();
	}
};
static_assert(alignof(UBP_ActionUnlockCagePalLock_C) == 0x000010, "Wrong alignment on UBP_ActionUnlockCagePalLock_C");
static_assert(sizeof(UBP_ActionUnlockCagePalLock_C) == 0x0001B0, "Wrong size on UBP_ActionUnlockCagePalLock_C");
static_assert(offsetof(UBP_ActionUnlockCagePalLock_C, UberGraphFrame_BP_ActionUnlockCagePalLock_C) == 0x000190, "Member 'UBP_ActionUnlockCagePalLock_C::UberGraphFrame_BP_ActionUnlockCagePalLock_C' has a wrong offset!");
static_assert(offsetof(UBP_ActionUnlockCagePalLock_C, flagName) == 0x000198, "Member 'UBP_ActionUnlockCagePalLock_C::flagName' has a wrong offset!");
static_assert(offsetof(UBP_ActionUnlockCagePalLock_C, AkEventUnlockCage) == 0x0001A0, "Member 'UBP_ActionUnlockCagePalLock_C::AkEventUnlockCage' has a wrong offset!");

}

