#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Fishing_Lure

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "CoreUObject_structs.hpp"
#include "Pal_structs.hpp"


namespace SDK::Params
{

// Function BP_Fishing_Lure.BP_Fishing_Lure_C.ExecuteUbergraph_BP_Fishing_Lure
// 0x0490 (0x0490 - 0x0000)
struct BP_Fishing_Lure_C_ExecuteUbergraph_BP_Fishing_Lure final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         K2Node_Event_DeltaSeconds;                         // 0x0004(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_GetSocketLocation_ReturnValue;            // 0x0008(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_Add_DoubleDouble_ReturnValue;             // 0x0020(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_EqualEqual_ByteByte_ReturnValue;          // 0x0028(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_29[0x7];                                       // 0x0029(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	double                                        CallFunc_Multiply_DoubleDouble_ReturnValue;        // 0x0030(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_Sin_ReturnValue;                          // 0x0038(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_Multiply_DoubleDouble_ReturnValue_1;      // 0x0040(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_Add_DoubleDouble_ReturnValue_1;           // 0x0048(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	EPalFishingRodState                           K2Node_CustomEvent_RodState;                       // 0x0050(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_51[0x7];                                       // 0x0051(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	double                                        CallFunc_Subtract_DoubleDouble_ReturnValue;        // 0x0058(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FHitResult                             CallFunc_K2_SetRelativeLocation_SweepHitResult;    // 0x0060(0x00E8)(IsPlainOldData, NoDestructor, ContainsInstancedReference)
	struct FHitResult                             CallFunc_K2_SetRelativeLocation_SweepHitResult_1;  // 0x0148(0x00E8)(IsPlainOldData, NoDestructor, ContainsInstancedReference)
	double                                        CallFunc_BreakVector_X;                            // 0x0230(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_BreakVector_Y;                            // 0x0238(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_BreakVector_Z;                            // 0x0240(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_BreakVector_X_1;                          // 0x0248(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_BreakVector_Y_1;                          // 0x0250(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_BreakVector_Z_1;                          // 0x0258(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_MakeVector_ReturnValue;                   // 0x0260(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FHitResult                             CallFunc_K2_SetRelativeLocation_SweepHitResult_2;  // 0x0278(0x00E8)(IsPlainOldData, NoDestructor, ContainsInstancedReference)
	double                                        CallFunc_BreakVector_X_2;                          // 0x0360(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_BreakVector_Y_2;                          // 0x0368(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_BreakVector_Z_2;                          // 0x0370(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_MakeVector_ReturnValue_1;                 // 0x0378(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_SwitchEnum_CmpSuccess;                      // 0x0390(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_EqualEqual_ByteByte_ReturnValue_1;        // 0x0391(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_EqualEqual_ByteByte_ReturnValue_2;        // 0x0392(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_EqualEqual_ByteByte_ReturnValue_3;        // 0x0393(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_BooleanOR_ReturnValue;                    // 0x0394(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_BooleanOR_ReturnValue_1;                  // 0x0395(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_CustomEvent_IsMove;                         // 0x0396(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Not_PreBool_ReturnValue;                  // 0x0397(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x0398(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_EqualEqual_ByteByte_ReturnValue_4;        // 0x0399(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue_1;                    // 0x039A(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_39B[0x5];                                      // 0x039B(0x0005)(Fixing Size After Last Property [ Dumper-7 ])
	struct FHitResult                             CallFunc_K2_SetWorldLocation_SweepHitResult;       // 0x03A0(0x00E8)(IsPlainOldData, NoDestructor, ContainsInstancedReference)
	double                                        CallFunc_Add_DoubleDouble_B_ImplicitCast;          // 0x0488(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_Fishing_Lure_C_ExecuteUbergraph_BP_Fishing_Lure) == 0x000008, "Wrong alignment on BP_Fishing_Lure_C_ExecuteUbergraph_BP_Fishing_Lure");
static_assert(sizeof(BP_Fishing_Lure_C_ExecuteUbergraph_BP_Fishing_Lure) == 0x000490, "Wrong size on BP_Fishing_Lure_C_ExecuteUbergraph_BP_Fishing_Lure");
static_assert(offsetof(BP_Fishing_Lure_C_ExecuteUbergraph_BP_Fishing_Lure, EntryPoint) == 0x000000, "Member 'BP_Fishing_Lure_C_ExecuteUbergraph_BP_Fishing_Lure::EntryPoint' has a wrong offset!");
static_assert(offsetof(BP_Fishing_Lure_C_ExecuteUbergraph_BP_Fishing_Lure, K2Node_Event_DeltaSeconds) == 0x000004, "Member 'BP_Fishing_Lure_C_ExecuteUbergraph_BP_Fishing_Lure::K2Node_Event_DeltaSeconds' has a wrong offset!");
static_assert(offsetof(BP_Fishing_Lure_C_ExecuteUbergraph_BP_Fishing_Lure, CallFunc_GetSocketLocation_ReturnValue) == 0x000008, "Member 'BP_Fishing_Lure_C_ExecuteUbergraph_BP_Fishing_Lure::CallFunc_GetSocketLocation_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_Fishing_Lure_C_ExecuteUbergraph_BP_Fishing_Lure, CallFunc_Add_DoubleDouble_ReturnValue) == 0x000020, "Member 'BP_Fishing_Lure_C_ExecuteUbergraph_BP_Fishing_Lure::CallFunc_Add_DoubleDouble_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_Fishing_Lure_C_ExecuteUbergraph_BP_Fishing_Lure, CallFunc_EqualEqual_ByteByte_ReturnValue) == 0x000028, "Member 'BP_Fishing_Lure_C_ExecuteUbergraph_BP_Fishing_Lure::CallFunc_EqualEqual_ByteByte_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_Fishing_Lure_C_ExecuteUbergraph_BP_Fishing_Lure, CallFunc_Multiply_DoubleDouble_ReturnValue) == 0x000030, "Member 'BP_Fishing_Lure_C_ExecuteUbergraph_BP_Fishing_Lure::CallFunc_Multiply_DoubleDouble_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_Fishing_Lure_C_ExecuteUbergraph_BP_Fishing_Lure, CallFunc_Sin_ReturnValue) == 0x000038, "Member 'BP_Fishing_Lure_C_ExecuteUbergraph_BP_Fishing_Lure::CallFunc_Sin_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_Fishing_Lure_C_ExecuteUbergraph_BP_Fishing_Lure, CallFunc_Multiply_DoubleDouble_ReturnValue_1) == 0x000040, "Member 'BP_Fishing_Lure_C_ExecuteUbergraph_BP_Fishing_Lure::CallFunc_Multiply_DoubleDouble_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_Fishing_Lure_C_ExecuteUbergraph_BP_Fishing_Lure, CallFunc_Add_DoubleDouble_ReturnValue_1) == 0x000048, "Member 'BP_Fishing_Lure_C_ExecuteUbergraph_BP_Fishing_Lure::CallFunc_Add_DoubleDouble_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_Fishing_Lure_C_ExecuteUbergraph_BP_Fishing_Lure, K2Node_CustomEvent_RodState) == 0x000050, "Member 'BP_Fishing_Lure_C_ExecuteUbergraph_BP_Fishing_Lure::K2Node_CustomEvent_RodState' has a wrong offset!");
static_assert(offsetof(BP_Fishing_Lure_C_ExecuteUbergraph_BP_Fishing_Lure, CallFunc_Subtract_DoubleDouble_ReturnValue) == 0x000058, "Member 'BP_Fishing_Lure_C_ExecuteUbergraph_BP_Fishing_Lure::CallFunc_Subtract_DoubleDouble_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_Fishing_Lure_C_ExecuteUbergraph_BP_Fishing_Lure, CallFunc_K2_SetRelativeLocation_SweepHitResult) == 0x000060, "Member 'BP_Fishing_Lure_C_ExecuteUbergraph_BP_Fishing_Lure::CallFunc_K2_SetRelativeLocation_SweepHitResult' has a wrong offset!");
static_assert(offsetof(BP_Fishing_Lure_C_ExecuteUbergraph_BP_Fishing_Lure, CallFunc_K2_SetRelativeLocation_SweepHitResult_1) == 0x000148, "Member 'BP_Fishing_Lure_C_ExecuteUbergraph_BP_Fishing_Lure::CallFunc_K2_SetRelativeLocation_SweepHitResult_1' has a wrong offset!");
static_assert(offsetof(BP_Fishing_Lure_C_ExecuteUbergraph_BP_Fishing_Lure, CallFunc_BreakVector_X) == 0x000230, "Member 'BP_Fishing_Lure_C_ExecuteUbergraph_BP_Fishing_Lure::CallFunc_BreakVector_X' has a wrong offset!");
static_assert(offsetof(BP_Fishing_Lure_C_ExecuteUbergraph_BP_Fishing_Lure, CallFunc_BreakVector_Y) == 0x000238, "Member 'BP_Fishing_Lure_C_ExecuteUbergraph_BP_Fishing_Lure::CallFunc_BreakVector_Y' has a wrong offset!");
static_assert(offsetof(BP_Fishing_Lure_C_ExecuteUbergraph_BP_Fishing_Lure, CallFunc_BreakVector_Z) == 0x000240, "Member 'BP_Fishing_Lure_C_ExecuteUbergraph_BP_Fishing_Lure::CallFunc_BreakVector_Z' has a wrong offset!");
static_assert(offsetof(BP_Fishing_Lure_C_ExecuteUbergraph_BP_Fishing_Lure, CallFunc_BreakVector_X_1) == 0x000248, "Member 'BP_Fishing_Lure_C_ExecuteUbergraph_BP_Fishing_Lure::CallFunc_BreakVector_X_1' has a wrong offset!");
static_assert(offsetof(BP_Fishing_Lure_C_ExecuteUbergraph_BP_Fishing_Lure, CallFunc_BreakVector_Y_1) == 0x000250, "Member 'BP_Fishing_Lure_C_ExecuteUbergraph_BP_Fishing_Lure::CallFunc_BreakVector_Y_1' has a wrong offset!");
static_assert(offsetof(BP_Fishing_Lure_C_ExecuteUbergraph_BP_Fishing_Lure, CallFunc_BreakVector_Z_1) == 0x000258, "Member 'BP_Fishing_Lure_C_ExecuteUbergraph_BP_Fishing_Lure::CallFunc_BreakVector_Z_1' has a wrong offset!");
static_assert(offsetof(BP_Fishing_Lure_C_ExecuteUbergraph_BP_Fishing_Lure, CallFunc_MakeVector_ReturnValue) == 0x000260, "Member 'BP_Fishing_Lure_C_ExecuteUbergraph_BP_Fishing_Lure::CallFunc_MakeVector_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_Fishing_Lure_C_ExecuteUbergraph_BP_Fishing_Lure, CallFunc_K2_SetRelativeLocation_SweepHitResult_2) == 0x000278, "Member 'BP_Fishing_Lure_C_ExecuteUbergraph_BP_Fishing_Lure::CallFunc_K2_SetRelativeLocation_SweepHitResult_2' has a wrong offset!");
static_assert(offsetof(BP_Fishing_Lure_C_ExecuteUbergraph_BP_Fishing_Lure, CallFunc_BreakVector_X_2) == 0x000360, "Member 'BP_Fishing_Lure_C_ExecuteUbergraph_BP_Fishing_Lure::CallFunc_BreakVector_X_2' has a wrong offset!");
static_assert(offsetof(BP_Fishing_Lure_C_ExecuteUbergraph_BP_Fishing_Lure, CallFunc_BreakVector_Y_2) == 0x000368, "Member 'BP_Fishing_Lure_C_ExecuteUbergraph_BP_Fishing_Lure::CallFunc_BreakVector_Y_2' has a wrong offset!");
static_assert(offsetof(BP_Fishing_Lure_C_ExecuteUbergraph_BP_Fishing_Lure, CallFunc_BreakVector_Z_2) == 0x000370, "Member 'BP_Fishing_Lure_C_ExecuteUbergraph_BP_Fishing_Lure::CallFunc_BreakVector_Z_2' has a wrong offset!");
static_assert(offsetof(BP_Fishing_Lure_C_ExecuteUbergraph_BP_Fishing_Lure, CallFunc_MakeVector_ReturnValue_1) == 0x000378, "Member 'BP_Fishing_Lure_C_ExecuteUbergraph_BP_Fishing_Lure::CallFunc_MakeVector_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_Fishing_Lure_C_ExecuteUbergraph_BP_Fishing_Lure, K2Node_SwitchEnum_CmpSuccess) == 0x000390, "Member 'BP_Fishing_Lure_C_ExecuteUbergraph_BP_Fishing_Lure::K2Node_SwitchEnum_CmpSuccess' has a wrong offset!");
static_assert(offsetof(BP_Fishing_Lure_C_ExecuteUbergraph_BP_Fishing_Lure, CallFunc_EqualEqual_ByteByte_ReturnValue_1) == 0x000391, "Member 'BP_Fishing_Lure_C_ExecuteUbergraph_BP_Fishing_Lure::CallFunc_EqualEqual_ByteByte_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_Fishing_Lure_C_ExecuteUbergraph_BP_Fishing_Lure, CallFunc_EqualEqual_ByteByte_ReturnValue_2) == 0x000392, "Member 'BP_Fishing_Lure_C_ExecuteUbergraph_BP_Fishing_Lure::CallFunc_EqualEqual_ByteByte_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(BP_Fishing_Lure_C_ExecuteUbergraph_BP_Fishing_Lure, CallFunc_EqualEqual_ByteByte_ReturnValue_3) == 0x000393, "Member 'BP_Fishing_Lure_C_ExecuteUbergraph_BP_Fishing_Lure::CallFunc_EqualEqual_ByteByte_ReturnValue_3' has a wrong offset!");
static_assert(offsetof(BP_Fishing_Lure_C_ExecuteUbergraph_BP_Fishing_Lure, CallFunc_BooleanOR_ReturnValue) == 0x000394, "Member 'BP_Fishing_Lure_C_ExecuteUbergraph_BP_Fishing_Lure::CallFunc_BooleanOR_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_Fishing_Lure_C_ExecuteUbergraph_BP_Fishing_Lure, CallFunc_BooleanOR_ReturnValue_1) == 0x000395, "Member 'BP_Fishing_Lure_C_ExecuteUbergraph_BP_Fishing_Lure::CallFunc_BooleanOR_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_Fishing_Lure_C_ExecuteUbergraph_BP_Fishing_Lure, K2Node_CustomEvent_IsMove) == 0x000396, "Member 'BP_Fishing_Lure_C_ExecuteUbergraph_BP_Fishing_Lure::K2Node_CustomEvent_IsMove' has a wrong offset!");
static_assert(offsetof(BP_Fishing_Lure_C_ExecuteUbergraph_BP_Fishing_Lure, CallFunc_Not_PreBool_ReturnValue) == 0x000397, "Member 'BP_Fishing_Lure_C_ExecuteUbergraph_BP_Fishing_Lure::CallFunc_Not_PreBool_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_Fishing_Lure_C_ExecuteUbergraph_BP_Fishing_Lure, CallFunc_IsValid_ReturnValue) == 0x000398, "Member 'BP_Fishing_Lure_C_ExecuteUbergraph_BP_Fishing_Lure::CallFunc_IsValid_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_Fishing_Lure_C_ExecuteUbergraph_BP_Fishing_Lure, CallFunc_EqualEqual_ByteByte_ReturnValue_4) == 0x000399, "Member 'BP_Fishing_Lure_C_ExecuteUbergraph_BP_Fishing_Lure::CallFunc_EqualEqual_ByteByte_ReturnValue_4' has a wrong offset!");
static_assert(offsetof(BP_Fishing_Lure_C_ExecuteUbergraph_BP_Fishing_Lure, CallFunc_IsValid_ReturnValue_1) == 0x00039A, "Member 'BP_Fishing_Lure_C_ExecuteUbergraph_BP_Fishing_Lure::CallFunc_IsValid_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_Fishing_Lure_C_ExecuteUbergraph_BP_Fishing_Lure, CallFunc_K2_SetWorldLocation_SweepHitResult) == 0x0003A0, "Member 'BP_Fishing_Lure_C_ExecuteUbergraph_BP_Fishing_Lure::CallFunc_K2_SetWorldLocation_SweepHitResult' has a wrong offset!");
static_assert(offsetof(BP_Fishing_Lure_C_ExecuteUbergraph_BP_Fishing_Lure, CallFunc_Add_DoubleDouble_B_ImplicitCast) == 0x000488, "Member 'BP_Fishing_Lure_C_ExecuteUbergraph_BP_Fishing_Lure::CallFunc_Add_DoubleDouble_B_ImplicitCast' has a wrong offset!");

// Function BP_Fishing_Lure.BP_Fishing_Lure_C.OnChangeFloatMoveState
// 0x0001 (0x0001 - 0x0000)
struct BP_Fishing_Lure_C_OnChangeFloatMoveState final
{
public:
	bool                                          IsMove;                                            // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_Fishing_Lure_C_OnChangeFloatMoveState) == 0x000001, "Wrong alignment on BP_Fishing_Lure_C_OnChangeFloatMoveState");
static_assert(sizeof(BP_Fishing_Lure_C_OnChangeFloatMoveState) == 0x000001, "Wrong size on BP_Fishing_Lure_C_OnChangeFloatMoveState");
static_assert(offsetof(BP_Fishing_Lure_C_OnChangeFloatMoveState, IsMove) == 0x000000, "Member 'BP_Fishing_Lure_C_OnChangeFloatMoveState::IsMove' has a wrong offset!");

// Function BP_Fishing_Lure.BP_Fishing_Lure_C.OnChangeRodState
// 0x0001 (0x0001 - 0x0000)
struct BP_Fishing_Lure_C_OnChangeRodState final
{
public:
	EPalFishingRodState                           RodState_0;                                        // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_Fishing_Lure_C_OnChangeRodState) == 0x000001, "Wrong alignment on BP_Fishing_Lure_C_OnChangeRodState");
static_assert(sizeof(BP_Fishing_Lure_C_OnChangeRodState) == 0x000001, "Wrong size on BP_Fishing_Lure_C_OnChangeRodState");
static_assert(offsetof(BP_Fishing_Lure_C_OnChangeRodState, RodState_0) == 0x000000, "Member 'BP_Fishing_Lure_C_OnChangeRodState::RodState_0' has a wrong offset!");

// Function BP_Fishing_Lure.BP_Fishing_Lure_C.ReceiveTick
// 0x0004 (0x0004 - 0x0000)
struct BP_Fishing_Lure_C_ReceiveTick final
{
public:
	float                                         DeltaSeconds;                                      // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_Fishing_Lure_C_ReceiveTick) == 0x000004, "Wrong alignment on BP_Fishing_Lure_C_ReceiveTick");
static_assert(sizeof(BP_Fishing_Lure_C_ReceiveTick) == 0x000004, "Wrong size on BP_Fishing_Lure_C_ReceiveTick");
static_assert(offsetof(BP_Fishing_Lure_C_ReceiveTick, DeltaSeconds) == 0x000000, "Member 'BP_Fishing_Lure_C_ReceiveTick::DeltaSeconds' has a wrong offset!");

// Function BP_Fishing_Lure.BP_Fishing_Lure_C.SetFloatMesh
// 0x0008 (0x0008 - 0x0000)
struct BP_Fishing_Lure_C_SetFloatMesh final
{
public:
	class USkeletalMesh*                          Mesh;                                              // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_Fishing_Lure_C_SetFloatMesh) == 0x000008, "Wrong alignment on BP_Fishing_Lure_C_SetFloatMesh");
static_assert(sizeof(BP_Fishing_Lure_C_SetFloatMesh) == 0x000008, "Wrong size on BP_Fishing_Lure_C_SetFloatMesh");
static_assert(offsetof(BP_Fishing_Lure_C_SetFloatMesh, Mesh) == 0x000000, "Member 'BP_Fishing_Lure_C_SetFloatMesh::Mesh' has a wrong offset!");

// Function BP_Fishing_Lure.BP_Fishing_Lure_C.SetTargetFishShadow
// 0x0008 (0x0008 - 0x0000)
struct BP_Fishing_Lure_C_SetTargetFishShadow final
{
public:
	class ABP_Fishing_FishShadowBase_C*           TargetFish_0;                                      // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_Fishing_Lure_C_SetTargetFishShadow) == 0x000008, "Wrong alignment on BP_Fishing_Lure_C_SetTargetFishShadow");
static_assert(sizeof(BP_Fishing_Lure_C_SetTargetFishShadow) == 0x000008, "Wrong size on BP_Fishing_Lure_C_SetTargetFishShadow");
static_assert(offsetof(BP_Fishing_Lure_C_SetTargetFishShadow, TargetFish_0) == 0x000000, "Member 'BP_Fishing_Lure_C_SetTargetFishShadow::TargetFish_0' has a wrong offset!");

// Function BP_Fishing_Lure.BP_Fishing_Lure_C.SetThrowLocation
// 0x0218 (0x0218 - 0x0000)
struct BP_Fishing_Lure_C_SetThrowLocation final
{
public:
	struct FVector                                ThrowLocation;                                     // 0x0000(0x0018)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_Add_VectorVector_ReturnValue;             // 0x0018(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_Add_VectorVector_ReturnValue_1;           // 0x0030(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TArray<class AActor*>                         K2Node_MakeArray_Array;                            // 0x0048(0x0010)(ConstParm, ReferenceParm)
	struct FHitResult                             CallFunc_LineTraceSingle_OutHit;                   // 0x0058(0x00E8)(IsPlainOldData, NoDestructor, ContainsInstancedReference)
	bool                                          CallFunc_LineTraceSingle_ReturnValue;              // 0x0140(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_BreakHitResult_bBlockingHit;              // 0x0141(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_BreakHitResult_bInitialOverlap;           // 0x0142(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_143[0x1];                                      // 0x0143(0x0001)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         CallFunc_BreakHitResult_Time;                      // 0x0144(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_BreakHitResult_Distance;                  // 0x0148(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_14C[0x4];                                      // 0x014C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	struct FVector                                CallFunc_BreakHitResult_Location;                  // 0x0150(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_BreakHitResult_ImpactPoint;               // 0x0168(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_BreakHitResult_Normal;                    // 0x0180(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_BreakHitResult_ImpactNormal;              // 0x0198(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UPhysicalMaterial*                      CallFunc_BreakHitResult_PhysMat;                   // 0x01B0(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class AActor*                                 CallFunc_BreakHitResult_HitActor;                  // 0x01B8(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class UPrimitiveComponent*                    CallFunc_BreakHitResult_HitComponent;              // 0x01C0(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	class FName                                   CallFunc_BreakHitResult_HitBoneName;               // 0x01C8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FName                                   CallFunc_BreakHitResult_BoneName;                  // 0x01D0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_BreakHitResult_HitItem;                   // 0x01D8(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_BreakHitResult_ElementIndex;              // 0x01DC(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_BreakHitResult_FaceIndex;                 // 0x01E0(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_1E4[0x4];                                      // 0x01E4(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	struct FVector                                CallFunc_BreakHitResult_TraceStart;                // 0x01E8(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_BreakHitResult_TraceEnd;                  // 0x0200(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_Fishing_Lure_C_SetThrowLocation) == 0x000008, "Wrong alignment on BP_Fishing_Lure_C_SetThrowLocation");
static_assert(sizeof(BP_Fishing_Lure_C_SetThrowLocation) == 0x000218, "Wrong size on BP_Fishing_Lure_C_SetThrowLocation");
static_assert(offsetof(BP_Fishing_Lure_C_SetThrowLocation, ThrowLocation) == 0x000000, "Member 'BP_Fishing_Lure_C_SetThrowLocation::ThrowLocation' has a wrong offset!");
static_assert(offsetof(BP_Fishing_Lure_C_SetThrowLocation, CallFunc_Add_VectorVector_ReturnValue) == 0x000018, "Member 'BP_Fishing_Lure_C_SetThrowLocation::CallFunc_Add_VectorVector_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_Fishing_Lure_C_SetThrowLocation, CallFunc_Add_VectorVector_ReturnValue_1) == 0x000030, "Member 'BP_Fishing_Lure_C_SetThrowLocation::CallFunc_Add_VectorVector_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_Fishing_Lure_C_SetThrowLocation, K2Node_MakeArray_Array) == 0x000048, "Member 'BP_Fishing_Lure_C_SetThrowLocation::K2Node_MakeArray_Array' has a wrong offset!");
static_assert(offsetof(BP_Fishing_Lure_C_SetThrowLocation, CallFunc_LineTraceSingle_OutHit) == 0x000058, "Member 'BP_Fishing_Lure_C_SetThrowLocation::CallFunc_LineTraceSingle_OutHit' has a wrong offset!");
static_assert(offsetof(BP_Fishing_Lure_C_SetThrowLocation, CallFunc_LineTraceSingle_ReturnValue) == 0x000140, "Member 'BP_Fishing_Lure_C_SetThrowLocation::CallFunc_LineTraceSingle_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_Fishing_Lure_C_SetThrowLocation, CallFunc_BreakHitResult_bBlockingHit) == 0x000141, "Member 'BP_Fishing_Lure_C_SetThrowLocation::CallFunc_BreakHitResult_bBlockingHit' has a wrong offset!");
static_assert(offsetof(BP_Fishing_Lure_C_SetThrowLocation, CallFunc_BreakHitResult_bInitialOverlap) == 0x000142, "Member 'BP_Fishing_Lure_C_SetThrowLocation::CallFunc_BreakHitResult_bInitialOverlap' has a wrong offset!");
static_assert(offsetof(BP_Fishing_Lure_C_SetThrowLocation, CallFunc_BreakHitResult_Time) == 0x000144, "Member 'BP_Fishing_Lure_C_SetThrowLocation::CallFunc_BreakHitResult_Time' has a wrong offset!");
static_assert(offsetof(BP_Fishing_Lure_C_SetThrowLocation, CallFunc_BreakHitResult_Distance) == 0x000148, "Member 'BP_Fishing_Lure_C_SetThrowLocation::CallFunc_BreakHitResult_Distance' has a wrong offset!");
static_assert(offsetof(BP_Fishing_Lure_C_SetThrowLocation, CallFunc_BreakHitResult_Location) == 0x000150, "Member 'BP_Fishing_Lure_C_SetThrowLocation::CallFunc_BreakHitResult_Location' has a wrong offset!");
static_assert(offsetof(BP_Fishing_Lure_C_SetThrowLocation, CallFunc_BreakHitResult_ImpactPoint) == 0x000168, "Member 'BP_Fishing_Lure_C_SetThrowLocation::CallFunc_BreakHitResult_ImpactPoint' has a wrong offset!");
static_assert(offsetof(BP_Fishing_Lure_C_SetThrowLocation, CallFunc_BreakHitResult_Normal) == 0x000180, "Member 'BP_Fishing_Lure_C_SetThrowLocation::CallFunc_BreakHitResult_Normal' has a wrong offset!");
static_assert(offsetof(BP_Fishing_Lure_C_SetThrowLocation, CallFunc_BreakHitResult_ImpactNormal) == 0x000198, "Member 'BP_Fishing_Lure_C_SetThrowLocation::CallFunc_BreakHitResult_ImpactNormal' has a wrong offset!");
static_assert(offsetof(BP_Fishing_Lure_C_SetThrowLocation, CallFunc_BreakHitResult_PhysMat) == 0x0001B0, "Member 'BP_Fishing_Lure_C_SetThrowLocation::CallFunc_BreakHitResult_PhysMat' has a wrong offset!");
static_assert(offsetof(BP_Fishing_Lure_C_SetThrowLocation, CallFunc_BreakHitResult_HitActor) == 0x0001B8, "Member 'BP_Fishing_Lure_C_SetThrowLocation::CallFunc_BreakHitResult_HitActor' has a wrong offset!");
static_assert(offsetof(BP_Fishing_Lure_C_SetThrowLocation, CallFunc_BreakHitResult_HitComponent) == 0x0001C0, "Member 'BP_Fishing_Lure_C_SetThrowLocation::CallFunc_BreakHitResult_HitComponent' has a wrong offset!");
static_assert(offsetof(BP_Fishing_Lure_C_SetThrowLocation, CallFunc_BreakHitResult_HitBoneName) == 0x0001C8, "Member 'BP_Fishing_Lure_C_SetThrowLocation::CallFunc_BreakHitResult_HitBoneName' has a wrong offset!");
static_assert(offsetof(BP_Fishing_Lure_C_SetThrowLocation, CallFunc_BreakHitResult_BoneName) == 0x0001D0, "Member 'BP_Fishing_Lure_C_SetThrowLocation::CallFunc_BreakHitResult_BoneName' has a wrong offset!");
static_assert(offsetof(BP_Fishing_Lure_C_SetThrowLocation, CallFunc_BreakHitResult_HitItem) == 0x0001D8, "Member 'BP_Fishing_Lure_C_SetThrowLocation::CallFunc_BreakHitResult_HitItem' has a wrong offset!");
static_assert(offsetof(BP_Fishing_Lure_C_SetThrowLocation, CallFunc_BreakHitResult_ElementIndex) == 0x0001DC, "Member 'BP_Fishing_Lure_C_SetThrowLocation::CallFunc_BreakHitResult_ElementIndex' has a wrong offset!");
static_assert(offsetof(BP_Fishing_Lure_C_SetThrowLocation, CallFunc_BreakHitResult_FaceIndex) == 0x0001E0, "Member 'BP_Fishing_Lure_C_SetThrowLocation::CallFunc_BreakHitResult_FaceIndex' has a wrong offset!");
static_assert(offsetof(BP_Fishing_Lure_C_SetThrowLocation, CallFunc_BreakHitResult_TraceStart) == 0x0001E8, "Member 'BP_Fishing_Lure_C_SetThrowLocation::CallFunc_BreakHitResult_TraceStart' has a wrong offset!");
static_assert(offsetof(BP_Fishing_Lure_C_SetThrowLocation, CallFunc_BreakHitResult_TraceEnd) == 0x000200, "Member 'BP_Fishing_Lure_C_SetThrowLocation::CallFunc_BreakHitResult_TraceEnd' has a wrong offset!");

// Function BP_Fishing_Lure.BP_Fishing_Lure_C.SetVisibleBattleSplashEffect
// 0x0030 (0x0030 - 0x0000)
struct BP_Fishing_Lure_C_SetVisibleBattleSplashEffect final
{
public:
	bool                                          IsVisible;                                         // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x0001(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue_1;                    // 0x0002(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_3[0x5];                                        // 0x0003(0x0005)(Fixing Size After Last Property [ Dumper-7 ])
	struct FVector                                CallFunc_K2_GetActorLocation_ReturnValue;          // 0x0008(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UNiagaraComponent*                      CallFunc_SpawnSystemAtLocation_ReturnValue;        // 0x0020(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue_2;                    // 0x0028(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_Fishing_Lure_C_SetVisibleBattleSplashEffect) == 0x000008, "Wrong alignment on BP_Fishing_Lure_C_SetVisibleBattleSplashEffect");
static_assert(sizeof(BP_Fishing_Lure_C_SetVisibleBattleSplashEffect) == 0x000030, "Wrong size on BP_Fishing_Lure_C_SetVisibleBattleSplashEffect");
static_assert(offsetof(BP_Fishing_Lure_C_SetVisibleBattleSplashEffect, IsVisible) == 0x000000, "Member 'BP_Fishing_Lure_C_SetVisibleBattleSplashEffect::IsVisible' has a wrong offset!");
static_assert(offsetof(BP_Fishing_Lure_C_SetVisibleBattleSplashEffect, CallFunc_IsValid_ReturnValue) == 0x000001, "Member 'BP_Fishing_Lure_C_SetVisibleBattleSplashEffect::CallFunc_IsValid_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_Fishing_Lure_C_SetVisibleBattleSplashEffect, CallFunc_IsValid_ReturnValue_1) == 0x000002, "Member 'BP_Fishing_Lure_C_SetVisibleBattleSplashEffect::CallFunc_IsValid_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_Fishing_Lure_C_SetVisibleBattleSplashEffect, CallFunc_K2_GetActorLocation_ReturnValue) == 0x000008, "Member 'BP_Fishing_Lure_C_SetVisibleBattleSplashEffect::CallFunc_K2_GetActorLocation_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_Fishing_Lure_C_SetVisibleBattleSplashEffect, CallFunc_SpawnSystemAtLocation_ReturnValue) == 0x000020, "Member 'BP_Fishing_Lure_C_SetVisibleBattleSplashEffect::CallFunc_SpawnSystemAtLocation_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_Fishing_Lure_C_SetVisibleBattleSplashEffect, CallFunc_IsValid_ReturnValue_2) == 0x000028, "Member 'BP_Fishing_Lure_C_SetVisibleBattleSplashEffect::CallFunc_IsValid_ReturnValue_2' has a wrong offset!");

// Function BP_Fishing_Lure.BP_Fishing_Lure_C.SetVisibleEffect
// 0x0158 (0x0158 - 0x0000)
struct BP_Fishing_Lure_C_SetVisibleEffect final
{
public:
	class UNiagaraComponent*                      Effect;                                            // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	bool                                          IsVisible;                                         // 0x0008(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_9[0x7];                                        // 0x0009(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	double                                        CallFunc_BreakVector_X;                            // 0x0010(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_BreakVector_Y;                            // 0x0018(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_BreakVector_Z;                            // 0x0020(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_K2_GetComponentLocation_ReturnValue;      // 0x0028(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_BreakVector_X_1;                          // 0x0040(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_BreakVector_Y_1;                          // 0x0048(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_BreakVector_Z_1;                          // 0x0050(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_MakeVector_ReturnValue;                   // 0x0058(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FHitResult                             CallFunc_K2_SetWorldLocation_SweepHitResult;       // 0x0070(0x00E8)(IsPlainOldData, NoDestructor, ContainsInstancedReference)
};
static_assert(alignof(BP_Fishing_Lure_C_SetVisibleEffect) == 0x000008, "Wrong alignment on BP_Fishing_Lure_C_SetVisibleEffect");
static_assert(sizeof(BP_Fishing_Lure_C_SetVisibleEffect) == 0x000158, "Wrong size on BP_Fishing_Lure_C_SetVisibleEffect");
static_assert(offsetof(BP_Fishing_Lure_C_SetVisibleEffect, Effect) == 0x000000, "Member 'BP_Fishing_Lure_C_SetVisibleEffect::Effect' has a wrong offset!");
static_assert(offsetof(BP_Fishing_Lure_C_SetVisibleEffect, IsVisible) == 0x000008, "Member 'BP_Fishing_Lure_C_SetVisibleEffect::IsVisible' has a wrong offset!");
static_assert(offsetof(BP_Fishing_Lure_C_SetVisibleEffect, CallFunc_BreakVector_X) == 0x000010, "Member 'BP_Fishing_Lure_C_SetVisibleEffect::CallFunc_BreakVector_X' has a wrong offset!");
static_assert(offsetof(BP_Fishing_Lure_C_SetVisibleEffect, CallFunc_BreakVector_Y) == 0x000018, "Member 'BP_Fishing_Lure_C_SetVisibleEffect::CallFunc_BreakVector_Y' has a wrong offset!");
static_assert(offsetof(BP_Fishing_Lure_C_SetVisibleEffect, CallFunc_BreakVector_Z) == 0x000020, "Member 'BP_Fishing_Lure_C_SetVisibleEffect::CallFunc_BreakVector_Z' has a wrong offset!");
static_assert(offsetof(BP_Fishing_Lure_C_SetVisibleEffect, CallFunc_K2_GetComponentLocation_ReturnValue) == 0x000028, "Member 'BP_Fishing_Lure_C_SetVisibleEffect::CallFunc_K2_GetComponentLocation_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_Fishing_Lure_C_SetVisibleEffect, CallFunc_BreakVector_X_1) == 0x000040, "Member 'BP_Fishing_Lure_C_SetVisibleEffect::CallFunc_BreakVector_X_1' has a wrong offset!");
static_assert(offsetof(BP_Fishing_Lure_C_SetVisibleEffect, CallFunc_BreakVector_Y_1) == 0x000048, "Member 'BP_Fishing_Lure_C_SetVisibleEffect::CallFunc_BreakVector_Y_1' has a wrong offset!");
static_assert(offsetof(BP_Fishing_Lure_C_SetVisibleEffect, CallFunc_BreakVector_Z_1) == 0x000050, "Member 'BP_Fishing_Lure_C_SetVisibleEffect::CallFunc_BreakVector_Z_1' has a wrong offset!");
static_assert(offsetof(BP_Fishing_Lure_C_SetVisibleEffect, CallFunc_MakeVector_ReturnValue) == 0x000058, "Member 'BP_Fishing_Lure_C_SetVisibleEffect::CallFunc_MakeVector_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_Fishing_Lure_C_SetVisibleEffect, CallFunc_K2_SetWorldLocation_SweepHitResult) == 0x000070, "Member 'BP_Fishing_Lure_C_SetVisibleEffect::CallFunc_K2_SetWorldLocation_SweepHitResult' has a wrong offset!");

// Function BP_Fishing_Lure.BP_Fishing_Lure_C.SetVisibleEffectForLoop
// 0x0010 (0x0010 - 0x0000)
struct BP_Fishing_Lure_C_SetVisibleEffectForLoop final
{
public:
	class UNiagaraComponent*                      Effect;                                            // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	bool                                          IsVisible;                                         // 0x0008(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          IsAdjustWaterPlane;                                // 0x0009(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsVisible_ReturnValue;                    // 0x000A(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_Fishing_Lure_C_SetVisibleEffectForLoop) == 0x000008, "Wrong alignment on BP_Fishing_Lure_C_SetVisibleEffectForLoop");
static_assert(sizeof(BP_Fishing_Lure_C_SetVisibleEffectForLoop) == 0x000010, "Wrong size on BP_Fishing_Lure_C_SetVisibleEffectForLoop");
static_assert(offsetof(BP_Fishing_Lure_C_SetVisibleEffectForLoop, Effect) == 0x000000, "Member 'BP_Fishing_Lure_C_SetVisibleEffectForLoop::Effect' has a wrong offset!");
static_assert(offsetof(BP_Fishing_Lure_C_SetVisibleEffectForLoop, IsVisible) == 0x000008, "Member 'BP_Fishing_Lure_C_SetVisibleEffectForLoop::IsVisible' has a wrong offset!");
static_assert(offsetof(BP_Fishing_Lure_C_SetVisibleEffectForLoop, IsAdjustWaterPlane) == 0x000009, "Member 'BP_Fishing_Lure_C_SetVisibleEffectForLoop::IsAdjustWaterPlane' has a wrong offset!");
static_assert(offsetof(BP_Fishing_Lure_C_SetVisibleEffectForLoop, CallFunc_IsVisible_ReturnValue) == 0x00000A, "Member 'BP_Fishing_Lure_C_SetVisibleEffectForLoop::CallFunc_IsVisible_ReturnValue' has a wrong offset!");

// Function BP_Fishing_Lure.BP_Fishing_Lure_C.SetVisibleFloat
// 0x0002 (0x0002 - 0x0000)
struct BP_Fishing_Lure_C_SetVisibleFloat final
{
public:
	bool                                          IsVisible;                                         // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsVisible_ReturnValue;                    // 0x0001(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_Fishing_Lure_C_SetVisibleFloat) == 0x000001, "Wrong alignment on BP_Fishing_Lure_C_SetVisibleFloat");
static_assert(sizeof(BP_Fishing_Lure_C_SetVisibleFloat) == 0x000002, "Wrong size on BP_Fishing_Lure_C_SetVisibleFloat");
static_assert(offsetof(BP_Fishing_Lure_C_SetVisibleFloat, IsVisible) == 0x000000, "Member 'BP_Fishing_Lure_C_SetVisibleFloat::IsVisible' has a wrong offset!");
static_assert(offsetof(BP_Fishing_Lure_C_SetVisibleFloat, CallFunc_IsVisible_ReturnValue) == 0x000001, "Member 'BP_Fishing_Lure_C_SetVisibleFloat::CallFunc_IsVisible_ReturnValue' has a wrong offset!");

// Function BP_Fishing_Lure.BP_Fishing_Lure_C.SetVisibleInWaterEffect
// 0x0001 (0x0001 - 0x0000)
struct BP_Fishing_Lure_C_SetVisibleInWaterEffect final
{
public:
	bool                                          IsVisible;                                         // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_Fishing_Lure_C_SetVisibleInWaterEffect) == 0x000001, "Wrong alignment on BP_Fishing_Lure_C_SetVisibleInWaterEffect");
static_assert(sizeof(BP_Fishing_Lure_C_SetVisibleInWaterEffect) == 0x000001, "Wrong size on BP_Fishing_Lure_C_SetVisibleInWaterEffect");
static_assert(offsetof(BP_Fishing_Lure_C_SetVisibleInWaterEffect, IsVisible) == 0x000000, "Member 'BP_Fishing_Lure_C_SetVisibleInWaterEffect::IsVisible' has a wrong offset!");

// Function BP_Fishing_Lure.BP_Fishing_Lure_C.SetVisibleLandingPointEffect
// 0x0002 (0x0002 - 0x0000)
struct BP_Fishing_Lure_C_SetVisibleLandingPointEffect final
{
public:
	bool                                          IsVisible;                                         // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CanFishing;                                        // 0x0001(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_Fishing_Lure_C_SetVisibleLandingPointEffect) == 0x000001, "Wrong alignment on BP_Fishing_Lure_C_SetVisibleLandingPointEffect");
static_assert(sizeof(BP_Fishing_Lure_C_SetVisibleLandingPointEffect) == 0x000002, "Wrong size on BP_Fishing_Lure_C_SetVisibleLandingPointEffect");
static_assert(offsetof(BP_Fishing_Lure_C_SetVisibleLandingPointEffect, IsVisible) == 0x000000, "Member 'BP_Fishing_Lure_C_SetVisibleLandingPointEffect::IsVisible' has a wrong offset!");
static_assert(offsetof(BP_Fishing_Lure_C_SetVisibleLandingPointEffect, CanFishing) == 0x000001, "Member 'BP_Fishing_Lure_C_SetVisibleLandingPointEffect::CanFishing' has a wrong offset!");

// Function BP_Fishing_Lure.BP_Fishing_Lure_C.SetVisibleOnWaterSplashEffect
// 0x0001 (0x0001 - 0x0000)
struct BP_Fishing_Lure_C_SetVisibleOnWaterSplashEffect final
{
public:
	bool                                          IsVisible;                                         // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_Fishing_Lure_C_SetVisibleOnWaterSplashEffect) == 0x000001, "Wrong alignment on BP_Fishing_Lure_C_SetVisibleOnWaterSplashEffect");
static_assert(sizeof(BP_Fishing_Lure_C_SetVisibleOnWaterSplashEffect) == 0x000001, "Wrong size on BP_Fishing_Lure_C_SetVisibleOnWaterSplashEffect");
static_assert(offsetof(BP_Fishing_Lure_C_SetVisibleOnWaterSplashEffect, IsVisible) == 0x000000, "Member 'BP_Fishing_Lure_C_SetVisibleOnWaterSplashEffect::IsVisible' has a wrong offset!");

// Function BP_Fishing_Lure.BP_Fishing_Lure_C.SetVisibleSinkSplashEffect
// 0x0001 (0x0001 - 0x0000)
struct BP_Fishing_Lure_C_SetVisibleSinkSplashEffect final
{
public:
	bool                                          IsVisible;                                         // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_Fishing_Lure_C_SetVisibleSinkSplashEffect) == 0x000001, "Wrong alignment on BP_Fishing_Lure_C_SetVisibleSinkSplashEffect");
static_assert(sizeof(BP_Fishing_Lure_C_SetVisibleSinkSplashEffect) == 0x000001, "Wrong size on BP_Fishing_Lure_C_SetVisibleSinkSplashEffect");
static_assert(offsetof(BP_Fishing_Lure_C_SetVisibleSinkSplashEffect, IsVisible) == 0x000000, "Member 'BP_Fishing_Lure_C_SetVisibleSinkSplashEffect::IsVisible' has a wrong offset!");

// Function BP_Fishing_Lure.BP_Fishing_Lure_C.SetVisibleSuccessSplashEffect
// 0x0001 (0x0001 - 0x0000)
struct BP_Fishing_Lure_C_SetVisibleSuccessSplashEffect final
{
public:
	bool                                          IsVisible;                                         // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_Fishing_Lure_C_SetVisibleSuccessSplashEffect) == 0x000001, "Wrong alignment on BP_Fishing_Lure_C_SetVisibleSuccessSplashEffect");
static_assert(sizeof(BP_Fishing_Lure_C_SetVisibleSuccessSplashEffect) == 0x000001, "Wrong size on BP_Fishing_Lure_C_SetVisibleSuccessSplashEffect");
static_assert(offsetof(BP_Fishing_Lure_C_SetVisibleSuccessSplashEffect, IsVisible) == 0x000000, "Member 'BP_Fishing_Lure_C_SetVisibleSuccessSplashEffect::IsVisible' has a wrong offset!");

// Function BP_Fishing_Lure.BP_Fishing_Lure_C.SetVisibleSwimEffect
// 0x0001 (0x0001 - 0x0000)
struct BP_Fishing_Lure_C_SetVisibleSwimEffect final
{
public:
	bool                                          IsVisible;                                         // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_Fishing_Lure_C_SetVisibleSwimEffect) == 0x000001, "Wrong alignment on BP_Fishing_Lure_C_SetVisibleSwimEffect");
static_assert(sizeof(BP_Fishing_Lure_C_SetVisibleSwimEffect) == 0x000001, "Wrong size on BP_Fishing_Lure_C_SetVisibleSwimEffect");
static_assert(offsetof(BP_Fishing_Lure_C_SetVisibleSwimEffect, IsVisible) == 0x000000, "Member 'BP_Fishing_Lure_C_SetVisibleSwimEffect::IsVisible' has a wrong offset!");

}

