#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_GuidedMissileLauncher

#include "Basic.hpp"

#include "BP_RocketLauncher_classes.hpp"
#include "Engine_structs.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_GuidedMissileLauncher.BP_GuidedMissileLauncher_C
// 0x0010 (0x0660 - 0x0650)
class ABP_GuidedMissileLauncher_C : public ABP_RocketLauncher_C
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame_BP_GuidedMissileLauncher_C;         // 0x0650(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UStaticMeshComponent*                   StaticMesh;                                        // 0x0658(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	void OnShoot(class APalBullet* BulletActor);
	void OnReloadStart(float InReloadSpeedPlayRate);
	void GetMuzzleEffect(class UNiagaraSystem** NewParam);
	void GetBulletClass(class UClass** NewParam);
	void ExecuteUbergraph_BP_GuidedMissileLauncher(int32 EntryPoint);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_GuidedMissileLauncher_C">();
	}
	static class ABP_GuidedMissileLauncher_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_GuidedMissileLauncher_C>();
	}
};
static_assert(alignof(ABP_GuidedMissileLauncher_C) == 0x000008, "Wrong alignment on ABP_GuidedMissileLauncher_C");
static_assert(sizeof(ABP_GuidedMissileLauncher_C) == 0x000660, "Wrong size on ABP_GuidedMissileLauncher_C");
static_assert(offsetof(ABP_GuidedMissileLauncher_C, UberGraphFrame_BP_GuidedMissileLauncher_C) == 0x000650, "Member 'ABP_GuidedMissileLauncher_C::UberGraphFrame_BP_GuidedMissileLauncher_C' has a wrong offset!");
static_assert(offsetof(ABP_GuidedMissileLauncher_C, StaticMesh) == 0x000658, "Member 'ABP_GuidedMissileLauncher_C::StaticMesh' has a wrong offset!");

}

