#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_MonsterAIController_ArenaNPCOtomo

#include "Basic.hpp"

#include "BP_MonsterAIControllerBase_classes.hpp"
#include "Engine_structs.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_MonsterAIController_ArenaNPCOtomo.BP_MonsterAIController_ArenaNPCOtomo_C
// 0x0010 (0x0570 - 0x0560)
class ABP_MonsterAIController_ArenaNPCOtomo_C final : public ABP_MonsterAIControllerBase_C
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame_BP_MonsterAIController_ArenaNPCOtomo_C; // 0x0560(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	TSubclassOf<class UPalAIActionBase>           CombatAIActionClass;                               // 0x0568(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, NoDestructor, UObjectWrapper, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_BP_MonsterAIController_ArenaNPCOtomo(int32 EntryPoint);
	void OnStartInBattle();
	void ReceivePossess(class APawn* PossessedPawn);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_MonsterAIController_ArenaNPCOtomo_C">();
	}
	static class ABP_MonsterAIController_ArenaNPCOtomo_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_MonsterAIController_ArenaNPCOtomo_C>();
	}
};
static_assert(alignof(ABP_MonsterAIController_ArenaNPCOtomo_C) == 0x000008, "Wrong alignment on ABP_MonsterAIController_ArenaNPCOtomo_C");
static_assert(sizeof(ABP_MonsterAIController_ArenaNPCOtomo_C) == 0x000570, "Wrong size on ABP_MonsterAIController_ArenaNPCOtomo_C");
static_assert(offsetof(ABP_MonsterAIController_ArenaNPCOtomo_C, UberGraphFrame_BP_MonsterAIController_ArenaNPCOtomo_C) == 0x000560, "Member 'ABP_MonsterAIController_ArenaNPCOtomo_C::UberGraphFrame_BP_MonsterAIController_ArenaNPCOtomo_C' has a wrong offset!");
static_assert(offsetof(ABP_MonsterAIController_ArenaNPCOtomo_C, CombatAIActionClass) == 0x000568, "Member 'ABP_MonsterAIController_ArenaNPCOtomo_C::CombatAIActionClass' has a wrong offset!");

}

