#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_IngameMenu_WorkSpace

#include "Basic.hpp"

#include "UMG_structs.hpp"
#include "CommonInput_structs.hpp"
#include "SlateCore_structs.hpp"
#include "Pal_structs.hpp"
#include "Engine_structs.hpp"


namespace SDK::Params
{

// Function WBP_IngameMenu_WorkSpace.WBP_IngameMenu_WorkSpace_C.BndEvt__WBP_IngameMenu_WorkSpace_WBP_IngameCommonSelectNum_K2Node_ComponentBoundEvent_5_OnUpdateNum__DelegateSignature
// 0x0008 (0x0008 - 0x0000)
struct WBP_IngameMenu_WorkSpace_C_BndEvt__WBP_IngameMenu_WorkSpace_WBP_IngameCommonSelectNum_K2Node_ComponentBoundEvent_5_OnUpdateNum__DelegateSignature final
{
public:
	int64                                         Num;                                               // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WBP_IngameMenu_WorkSpace_C_BndEvt__WBP_IngameMenu_WorkSpace_WBP_IngameCommonSelectNum_K2Node_ComponentBoundEvent_5_OnUpdateNum__DelegateSignature) == 0x000008, "Wrong alignment on WBP_IngameMenu_WorkSpace_C_BndEvt__WBP_IngameMenu_WorkSpace_WBP_IngameCommonSelectNum_K2Node_ComponentBoundEvent_5_OnUpdateNum__DelegateSignature");
static_assert(sizeof(WBP_IngameMenu_WorkSpace_C_BndEvt__WBP_IngameMenu_WorkSpace_WBP_IngameCommonSelectNum_K2Node_ComponentBoundEvent_5_OnUpdateNum__DelegateSignature) == 0x000008, "Wrong size on WBP_IngameMenu_WorkSpace_C_BndEvt__WBP_IngameMenu_WorkSpace_WBP_IngameCommonSelectNum_K2Node_ComponentBoundEvent_5_OnUpdateNum__DelegateSignature");
static_assert(offsetof(WBP_IngameMenu_WorkSpace_C_BndEvt__WBP_IngameMenu_WorkSpace_WBP_IngameCommonSelectNum_K2Node_ComponentBoundEvent_5_OnUpdateNum__DelegateSignature, Num) == 0x000000, "Member 'WBP_IngameMenu_WorkSpace_C_BndEvt__WBP_IngameMenu_WorkSpace_WBP_IngameCommonSelectNum_K2Node_ComponentBoundEvent_5_OnUpdateNum__DelegateSignature::Num' has a wrong offset!");

// Function WBP_IngameMenu_WorkSpace.WBP_IngameMenu_WorkSpace_C.BndEvt__WBP_IngameMenu_WorkSpace_WBP_PalInvisibleButton_TransportCheck_K2Node_ComponentBoundEvent_8_CommonButtonBaseClicked__DelegateSignature
// 0x0008 (0x0008 - 0x0000)
struct WBP_IngameMenu_WorkSpace_C_BndEvt__WBP_IngameMenu_WorkSpace_WBP_PalInvisibleButton_TransportCheck_K2Node_ComponentBoundEvent_8_CommonButtonBaseClicked__DelegateSignature final
{
public:
	class UCommonButtonBase*                      Button;                                            // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WBP_IngameMenu_WorkSpace_C_BndEvt__WBP_IngameMenu_WorkSpace_WBP_PalInvisibleButton_TransportCheck_K2Node_ComponentBoundEvent_8_CommonButtonBaseClicked__DelegateSignature) == 0x000008, "Wrong alignment on WBP_IngameMenu_WorkSpace_C_BndEvt__WBP_IngameMenu_WorkSpace_WBP_PalInvisibleButton_TransportCheck_K2Node_ComponentBoundEvent_8_CommonButtonBaseClicked__DelegateSignature");
static_assert(sizeof(WBP_IngameMenu_WorkSpace_C_BndEvt__WBP_IngameMenu_WorkSpace_WBP_PalInvisibleButton_TransportCheck_K2Node_ComponentBoundEvent_8_CommonButtonBaseClicked__DelegateSignature) == 0x000008, "Wrong size on WBP_IngameMenu_WorkSpace_C_BndEvt__WBP_IngameMenu_WorkSpace_WBP_PalInvisibleButton_TransportCheck_K2Node_ComponentBoundEvent_8_CommonButtonBaseClicked__DelegateSignature");
static_assert(offsetof(WBP_IngameMenu_WorkSpace_C_BndEvt__WBP_IngameMenu_WorkSpace_WBP_PalInvisibleButton_TransportCheck_K2Node_ComponentBoundEvent_8_CommonButtonBaseClicked__DelegateSignature, Button) == 0x000000, "Member 'WBP_IngameMenu_WorkSpace_C_BndEvt__WBP_IngameMenu_WorkSpace_WBP_PalInvisibleButton_TransportCheck_K2Node_ComponentBoundEvent_8_CommonButtonBaseClicked__DelegateSignature::Button' has a wrong offset!");

// Function WBP_IngameMenu_WorkSpace.WBP_IngameMenu_WorkSpace_C.ExecuteUbergraph_WBP_IngameMenu_WorkSpace
// 0x0090 (0x0090 - 0x0000)
struct WBP_IngameMenu_WorkSpace_C_ExecuteUbergraph_WBP_IngameMenu_WorkSpace final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ECheckBoxState                                Temp_byte_Variable;                                // 0x0004(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_5[0x3];                                        // 0x0005(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_CalcMaxProductableNum_ReturnValue;        // 0x0008(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ECheckBoxState                                Temp_byte_Variable_1;                              // 0x000C(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_D[0x3];                                        // 0x000D(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_Max_ReturnValue;                          // 0x0010(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_14[0x4];                                       // 0x0014(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UCommonInputSubsystem*                  CallFunc_GetLocalPlayerSubsystem_ReturnValue;      // 0x0018(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class UPalHUDService*                         CallFunc_GetHUDService_ReturnValue;                // 0x0020(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x0028(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	EPalUIConvertItemRequestStartResponse         CallFunc_CanStartProduction_ReturnValue;           // 0x0029(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_EqualEqual_ByteByte_ReturnValue;          // 0x002A(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_2B[0x1];                                       // 0x002B(0x0001)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_CalcMaxProductableNum_ReturnValue_1;      // 0x002C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Max_ReturnValue_1;                        // 0x0030(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsSelectingProductNum_IsSelecting;        // 0x0034(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_35[0x3];                                       // 0x0035(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	TDelegate<void()>                             K2Node_CreateDelegate_OutputDelegate;              // 0x0038(0x0010)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	struct FTimerHandle                           CallFunc_K2_SetTimerDelegate_ReturnValue;          // 0x0048(0x0008)(NoDestructor, HasGetValueTypeHash)
	class UCommonButtonBase*                      K2Node_ComponentBoundEvent_Button;                 // 0x0050(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Not_PreBool_ReturnValue;                  // 0x0058(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsChecked_ReturnValue;                    // 0x0059(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsSelectingProductNum_IsSelecting_1;      // 0x005A(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Temp_bool_Variable;                                // 0x005B(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TDelegate<void(ECommonInputType bNewInputType)> K2Node_CreateDelegate_OutputDelegate_1;          // 0x005C(0x0010)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	ECheckBoxState                                K2Node_Select_Default;                             // 0x006C(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_6D[0x3];                                       // 0x006D(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	TDelegate<void(ECommonInputType bNewInputType)> K2Node_CreateDelegate_OutputDelegate_2;          // 0x0070(0x0010)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	int64                                         K2Node_ComponentBoundEvent_Num;                    // 0x0080(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Conv_Int64ToInt_ReturnValue;              // 0x0088(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Clamp_ReturnValue;                        // 0x008C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WBP_IngameMenu_WorkSpace_C_ExecuteUbergraph_WBP_IngameMenu_WorkSpace) == 0x000008, "Wrong alignment on WBP_IngameMenu_WorkSpace_C_ExecuteUbergraph_WBP_IngameMenu_WorkSpace");
static_assert(sizeof(WBP_IngameMenu_WorkSpace_C_ExecuteUbergraph_WBP_IngameMenu_WorkSpace) == 0x000090, "Wrong size on WBP_IngameMenu_WorkSpace_C_ExecuteUbergraph_WBP_IngameMenu_WorkSpace");
static_assert(offsetof(WBP_IngameMenu_WorkSpace_C_ExecuteUbergraph_WBP_IngameMenu_WorkSpace, EntryPoint) == 0x000000, "Member 'WBP_IngameMenu_WorkSpace_C_ExecuteUbergraph_WBP_IngameMenu_WorkSpace::EntryPoint' has a wrong offset!");
static_assert(offsetof(WBP_IngameMenu_WorkSpace_C_ExecuteUbergraph_WBP_IngameMenu_WorkSpace, Temp_byte_Variable) == 0x000004, "Member 'WBP_IngameMenu_WorkSpace_C_ExecuteUbergraph_WBP_IngameMenu_WorkSpace::Temp_byte_Variable' has a wrong offset!");
static_assert(offsetof(WBP_IngameMenu_WorkSpace_C_ExecuteUbergraph_WBP_IngameMenu_WorkSpace, CallFunc_CalcMaxProductableNum_ReturnValue) == 0x000008, "Member 'WBP_IngameMenu_WorkSpace_C_ExecuteUbergraph_WBP_IngameMenu_WorkSpace::CallFunc_CalcMaxProductableNum_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_IngameMenu_WorkSpace_C_ExecuteUbergraph_WBP_IngameMenu_WorkSpace, Temp_byte_Variable_1) == 0x00000C, "Member 'WBP_IngameMenu_WorkSpace_C_ExecuteUbergraph_WBP_IngameMenu_WorkSpace::Temp_byte_Variable_1' has a wrong offset!");
static_assert(offsetof(WBP_IngameMenu_WorkSpace_C_ExecuteUbergraph_WBP_IngameMenu_WorkSpace, CallFunc_Max_ReturnValue) == 0x000010, "Member 'WBP_IngameMenu_WorkSpace_C_ExecuteUbergraph_WBP_IngameMenu_WorkSpace::CallFunc_Max_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_IngameMenu_WorkSpace_C_ExecuteUbergraph_WBP_IngameMenu_WorkSpace, CallFunc_GetLocalPlayerSubsystem_ReturnValue) == 0x000018, "Member 'WBP_IngameMenu_WorkSpace_C_ExecuteUbergraph_WBP_IngameMenu_WorkSpace::CallFunc_GetLocalPlayerSubsystem_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_IngameMenu_WorkSpace_C_ExecuteUbergraph_WBP_IngameMenu_WorkSpace, CallFunc_GetHUDService_ReturnValue) == 0x000020, "Member 'WBP_IngameMenu_WorkSpace_C_ExecuteUbergraph_WBP_IngameMenu_WorkSpace::CallFunc_GetHUDService_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_IngameMenu_WorkSpace_C_ExecuteUbergraph_WBP_IngameMenu_WorkSpace, CallFunc_IsValid_ReturnValue) == 0x000028, "Member 'WBP_IngameMenu_WorkSpace_C_ExecuteUbergraph_WBP_IngameMenu_WorkSpace::CallFunc_IsValid_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_IngameMenu_WorkSpace_C_ExecuteUbergraph_WBP_IngameMenu_WorkSpace, CallFunc_CanStartProduction_ReturnValue) == 0x000029, "Member 'WBP_IngameMenu_WorkSpace_C_ExecuteUbergraph_WBP_IngameMenu_WorkSpace::CallFunc_CanStartProduction_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_IngameMenu_WorkSpace_C_ExecuteUbergraph_WBP_IngameMenu_WorkSpace, CallFunc_EqualEqual_ByteByte_ReturnValue) == 0x00002A, "Member 'WBP_IngameMenu_WorkSpace_C_ExecuteUbergraph_WBP_IngameMenu_WorkSpace::CallFunc_EqualEqual_ByteByte_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_IngameMenu_WorkSpace_C_ExecuteUbergraph_WBP_IngameMenu_WorkSpace, CallFunc_CalcMaxProductableNum_ReturnValue_1) == 0x00002C, "Member 'WBP_IngameMenu_WorkSpace_C_ExecuteUbergraph_WBP_IngameMenu_WorkSpace::CallFunc_CalcMaxProductableNum_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(WBP_IngameMenu_WorkSpace_C_ExecuteUbergraph_WBP_IngameMenu_WorkSpace, CallFunc_Max_ReturnValue_1) == 0x000030, "Member 'WBP_IngameMenu_WorkSpace_C_ExecuteUbergraph_WBP_IngameMenu_WorkSpace::CallFunc_Max_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(WBP_IngameMenu_WorkSpace_C_ExecuteUbergraph_WBP_IngameMenu_WorkSpace, CallFunc_IsSelectingProductNum_IsSelecting) == 0x000034, "Member 'WBP_IngameMenu_WorkSpace_C_ExecuteUbergraph_WBP_IngameMenu_WorkSpace::CallFunc_IsSelectingProductNum_IsSelecting' has a wrong offset!");
static_assert(offsetof(WBP_IngameMenu_WorkSpace_C_ExecuteUbergraph_WBP_IngameMenu_WorkSpace, K2Node_CreateDelegate_OutputDelegate) == 0x000038, "Member 'WBP_IngameMenu_WorkSpace_C_ExecuteUbergraph_WBP_IngameMenu_WorkSpace::K2Node_CreateDelegate_OutputDelegate' has a wrong offset!");
static_assert(offsetof(WBP_IngameMenu_WorkSpace_C_ExecuteUbergraph_WBP_IngameMenu_WorkSpace, CallFunc_K2_SetTimerDelegate_ReturnValue) == 0x000048, "Member 'WBP_IngameMenu_WorkSpace_C_ExecuteUbergraph_WBP_IngameMenu_WorkSpace::CallFunc_K2_SetTimerDelegate_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_IngameMenu_WorkSpace_C_ExecuteUbergraph_WBP_IngameMenu_WorkSpace, K2Node_ComponentBoundEvent_Button) == 0x000050, "Member 'WBP_IngameMenu_WorkSpace_C_ExecuteUbergraph_WBP_IngameMenu_WorkSpace::K2Node_ComponentBoundEvent_Button' has a wrong offset!");
static_assert(offsetof(WBP_IngameMenu_WorkSpace_C_ExecuteUbergraph_WBP_IngameMenu_WorkSpace, CallFunc_Not_PreBool_ReturnValue) == 0x000058, "Member 'WBP_IngameMenu_WorkSpace_C_ExecuteUbergraph_WBP_IngameMenu_WorkSpace::CallFunc_Not_PreBool_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_IngameMenu_WorkSpace_C_ExecuteUbergraph_WBP_IngameMenu_WorkSpace, CallFunc_IsChecked_ReturnValue) == 0x000059, "Member 'WBP_IngameMenu_WorkSpace_C_ExecuteUbergraph_WBP_IngameMenu_WorkSpace::CallFunc_IsChecked_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_IngameMenu_WorkSpace_C_ExecuteUbergraph_WBP_IngameMenu_WorkSpace, CallFunc_IsSelectingProductNum_IsSelecting_1) == 0x00005A, "Member 'WBP_IngameMenu_WorkSpace_C_ExecuteUbergraph_WBP_IngameMenu_WorkSpace::CallFunc_IsSelectingProductNum_IsSelecting_1' has a wrong offset!");
static_assert(offsetof(WBP_IngameMenu_WorkSpace_C_ExecuteUbergraph_WBP_IngameMenu_WorkSpace, Temp_bool_Variable) == 0x00005B, "Member 'WBP_IngameMenu_WorkSpace_C_ExecuteUbergraph_WBP_IngameMenu_WorkSpace::Temp_bool_Variable' has a wrong offset!");
static_assert(offsetof(WBP_IngameMenu_WorkSpace_C_ExecuteUbergraph_WBP_IngameMenu_WorkSpace, K2Node_CreateDelegate_OutputDelegate_1) == 0x00005C, "Member 'WBP_IngameMenu_WorkSpace_C_ExecuteUbergraph_WBP_IngameMenu_WorkSpace::K2Node_CreateDelegate_OutputDelegate_1' has a wrong offset!");
static_assert(offsetof(WBP_IngameMenu_WorkSpace_C_ExecuteUbergraph_WBP_IngameMenu_WorkSpace, K2Node_Select_Default) == 0x00006C, "Member 'WBP_IngameMenu_WorkSpace_C_ExecuteUbergraph_WBP_IngameMenu_WorkSpace::K2Node_Select_Default' has a wrong offset!");
static_assert(offsetof(WBP_IngameMenu_WorkSpace_C_ExecuteUbergraph_WBP_IngameMenu_WorkSpace, K2Node_CreateDelegate_OutputDelegate_2) == 0x000070, "Member 'WBP_IngameMenu_WorkSpace_C_ExecuteUbergraph_WBP_IngameMenu_WorkSpace::K2Node_CreateDelegate_OutputDelegate_2' has a wrong offset!");
static_assert(offsetof(WBP_IngameMenu_WorkSpace_C_ExecuteUbergraph_WBP_IngameMenu_WorkSpace, K2Node_ComponentBoundEvent_Num) == 0x000080, "Member 'WBP_IngameMenu_WorkSpace_C_ExecuteUbergraph_WBP_IngameMenu_WorkSpace::K2Node_ComponentBoundEvent_Num' has a wrong offset!");
static_assert(offsetof(WBP_IngameMenu_WorkSpace_C_ExecuteUbergraph_WBP_IngameMenu_WorkSpace, CallFunc_Conv_Int64ToInt_ReturnValue) == 0x000088, "Member 'WBP_IngameMenu_WorkSpace_C_ExecuteUbergraph_WBP_IngameMenu_WorkSpace::CallFunc_Conv_Int64ToInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_IngameMenu_WorkSpace_C_ExecuteUbergraph_WBP_IngameMenu_WorkSpace, CallFunc_Clamp_ReturnValue) == 0x00008C, "Member 'WBP_IngameMenu_WorkSpace_C_ExecuteUbergraph_WBP_IngameMenu_WorkSpace::CallFunc_Clamp_ReturnValue' has a wrong offset!");

// Function WBP_IngameMenu_WorkSpace.WBP_IngameMenu_WorkSpace_C.FilteringRecipe
// 0x01A8 (0x01A8 - 0x0000)
struct WBP_IngameMenu_WorkSpace_C_FilteringRecipe final
{
public:
	TArray<class FName>                           recipeIDArray;                                     // 0x0000(0x0010)(BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
	TArray<class FName>                           FilteredArray;                                     // 0x0010(0x0010)(Parm, OutParm)
	TArray<class FName>                           WorkingTechnologyRecipeIDArray;                    // 0x0020(0x0010)(Edit, BlueprintVisible)
	TArray<class FName>                           MissingBlueprintItemIDArray;                       // 0x0030(0x0010)(Edit, BlueprintVisible)
	TMap<class FName, class FName>                RequireBluepintItemAndRecipeMap;                   // 0x0040(0x0050)(Edit, BlueprintVisible)
	int32                                         Temp_int_Array_Index_Variable;                     // 0x0090(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FPalStaticItemIdAndNum                 CallFunc_Array_Get_Item;                           // 0x0094(0x000C)(NoDestructor)
	int32                                         CallFunc_Array_Length_ReturnValue;                 // 0x00A0(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Loop_Counter_Variable;                    // 0x00A4(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Array_Index_Variable_1;                   // 0x00A8(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Less_IntInt_ReturnValue;                  // 0x00AC(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_AD[0x3];                                       // 0x00AD(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_Add_IntInt_ReturnValue;                   // 0x00B0(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Loop_Counter_Variable_1;                  // 0x00B4(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Add_IntInt_ReturnValue_1;                 // 0x00B8(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Array_Index_Variable_2;                   // 0x00BC(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Loop_Counter_Variable_2;                  // 0x00C0(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FName                                   CallFunc_Array_Get_Item_1;                         // 0x00C4(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Array_Length_ReturnValue_1;               // 0x00CC(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Add_IntInt_ReturnValue_2;                 // 0x00D0(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Less_IntInt_ReturnValue_1;                // 0x00D4(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_D5[0x3];                                       // 0x00D5(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	class FName                                   CallFunc_Array_Get_Item_2;                         // 0x00D8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Array_RemoveItem_ReturnValue;             // 0x00E0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_E1[0x3];                                       // 0x00E1(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	class FName                                   CallFunc_Map_Find_Value;                           // 0x00E4(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Map_Find_ReturnValue;                     // 0x00EC(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_ED[0x3];                                       // 0x00ED(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_Array_Length_ReturnValue_2;               // 0x00F0(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Less_IntInt_ReturnValue_2;                // 0x00F4(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Array_RemoveItem_ReturnValue_1;           // 0x00F5(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_F6[0x2];                                       // 0x00F6(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<struct FPalStaticItemIdAndNum>         CallFunc_CollectLocalPlayerControllableItemInfos_OutItemInfos; // 0x00F8(0x0010)(ReferenceParm)
	class UPalMasterDataTableAccess_ItemRecipe*   CallFunc_GetItemRecipeDataTableAccess_ReturnValue; // 0x0108(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class UPalTechnologyData*                     CallFunc_GetLocalTechnologyData_ReturnValue;       // 0x0110(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_BP_FindRow_bResult;                       // 0x0118(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_119[0x7];                                      // 0x0119(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	struct FPalItemRecipe                         CallFunc_BP_FindRow_ReturnValue;                   // 0x0120(0x0070)()
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x0190(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_NotEqual_NameName_ReturnValue;            // 0x0191(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_192[0x2];                                      // 0x0192(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_Array_AddUnique_ReturnValue;              // 0x0194(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TArray<class FName>                           CallFunc_FilteringUnlockedRecipe_OutRecipeIdArray; // 0x0198(0x0010)(ReferenceParm)
};
static_assert(alignof(WBP_IngameMenu_WorkSpace_C_FilteringRecipe) == 0x000008, "Wrong alignment on WBP_IngameMenu_WorkSpace_C_FilteringRecipe");
static_assert(sizeof(WBP_IngameMenu_WorkSpace_C_FilteringRecipe) == 0x0001A8, "Wrong size on WBP_IngameMenu_WorkSpace_C_FilteringRecipe");
static_assert(offsetof(WBP_IngameMenu_WorkSpace_C_FilteringRecipe, recipeIDArray) == 0x000000, "Member 'WBP_IngameMenu_WorkSpace_C_FilteringRecipe::recipeIDArray' has a wrong offset!");
static_assert(offsetof(WBP_IngameMenu_WorkSpace_C_FilteringRecipe, FilteredArray) == 0x000010, "Member 'WBP_IngameMenu_WorkSpace_C_FilteringRecipe::FilteredArray' has a wrong offset!");
static_assert(offsetof(WBP_IngameMenu_WorkSpace_C_FilteringRecipe, WorkingTechnologyRecipeIDArray) == 0x000020, "Member 'WBP_IngameMenu_WorkSpace_C_FilteringRecipe::WorkingTechnologyRecipeIDArray' has a wrong offset!");
static_assert(offsetof(WBP_IngameMenu_WorkSpace_C_FilteringRecipe, MissingBlueprintItemIDArray) == 0x000030, "Member 'WBP_IngameMenu_WorkSpace_C_FilteringRecipe::MissingBlueprintItemIDArray' has a wrong offset!");
static_assert(offsetof(WBP_IngameMenu_WorkSpace_C_FilteringRecipe, RequireBluepintItemAndRecipeMap) == 0x000040, "Member 'WBP_IngameMenu_WorkSpace_C_FilteringRecipe::RequireBluepintItemAndRecipeMap' has a wrong offset!");
static_assert(offsetof(WBP_IngameMenu_WorkSpace_C_FilteringRecipe, Temp_int_Array_Index_Variable) == 0x000090, "Member 'WBP_IngameMenu_WorkSpace_C_FilteringRecipe::Temp_int_Array_Index_Variable' has a wrong offset!");
static_assert(offsetof(WBP_IngameMenu_WorkSpace_C_FilteringRecipe, CallFunc_Array_Get_Item) == 0x000094, "Member 'WBP_IngameMenu_WorkSpace_C_FilteringRecipe::CallFunc_Array_Get_Item' has a wrong offset!");
static_assert(offsetof(WBP_IngameMenu_WorkSpace_C_FilteringRecipe, CallFunc_Array_Length_ReturnValue) == 0x0000A0, "Member 'WBP_IngameMenu_WorkSpace_C_FilteringRecipe::CallFunc_Array_Length_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_IngameMenu_WorkSpace_C_FilteringRecipe, Temp_int_Loop_Counter_Variable) == 0x0000A4, "Member 'WBP_IngameMenu_WorkSpace_C_FilteringRecipe::Temp_int_Loop_Counter_Variable' has a wrong offset!");
static_assert(offsetof(WBP_IngameMenu_WorkSpace_C_FilteringRecipe, Temp_int_Array_Index_Variable_1) == 0x0000A8, "Member 'WBP_IngameMenu_WorkSpace_C_FilteringRecipe::Temp_int_Array_Index_Variable_1' has a wrong offset!");
static_assert(offsetof(WBP_IngameMenu_WorkSpace_C_FilteringRecipe, CallFunc_Less_IntInt_ReturnValue) == 0x0000AC, "Member 'WBP_IngameMenu_WorkSpace_C_FilteringRecipe::CallFunc_Less_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_IngameMenu_WorkSpace_C_FilteringRecipe, CallFunc_Add_IntInt_ReturnValue) == 0x0000B0, "Member 'WBP_IngameMenu_WorkSpace_C_FilteringRecipe::CallFunc_Add_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_IngameMenu_WorkSpace_C_FilteringRecipe, Temp_int_Loop_Counter_Variable_1) == 0x0000B4, "Member 'WBP_IngameMenu_WorkSpace_C_FilteringRecipe::Temp_int_Loop_Counter_Variable_1' has a wrong offset!");
static_assert(offsetof(WBP_IngameMenu_WorkSpace_C_FilteringRecipe, CallFunc_Add_IntInt_ReturnValue_1) == 0x0000B8, "Member 'WBP_IngameMenu_WorkSpace_C_FilteringRecipe::CallFunc_Add_IntInt_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(WBP_IngameMenu_WorkSpace_C_FilteringRecipe, Temp_int_Array_Index_Variable_2) == 0x0000BC, "Member 'WBP_IngameMenu_WorkSpace_C_FilteringRecipe::Temp_int_Array_Index_Variable_2' has a wrong offset!");
static_assert(offsetof(WBP_IngameMenu_WorkSpace_C_FilteringRecipe, Temp_int_Loop_Counter_Variable_2) == 0x0000C0, "Member 'WBP_IngameMenu_WorkSpace_C_FilteringRecipe::Temp_int_Loop_Counter_Variable_2' has a wrong offset!");
static_assert(offsetof(WBP_IngameMenu_WorkSpace_C_FilteringRecipe, CallFunc_Array_Get_Item_1) == 0x0000C4, "Member 'WBP_IngameMenu_WorkSpace_C_FilteringRecipe::CallFunc_Array_Get_Item_1' has a wrong offset!");
static_assert(offsetof(WBP_IngameMenu_WorkSpace_C_FilteringRecipe, CallFunc_Array_Length_ReturnValue_1) == 0x0000CC, "Member 'WBP_IngameMenu_WorkSpace_C_FilteringRecipe::CallFunc_Array_Length_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(WBP_IngameMenu_WorkSpace_C_FilteringRecipe, CallFunc_Add_IntInt_ReturnValue_2) == 0x0000D0, "Member 'WBP_IngameMenu_WorkSpace_C_FilteringRecipe::CallFunc_Add_IntInt_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(WBP_IngameMenu_WorkSpace_C_FilteringRecipe, CallFunc_Less_IntInt_ReturnValue_1) == 0x0000D4, "Member 'WBP_IngameMenu_WorkSpace_C_FilteringRecipe::CallFunc_Less_IntInt_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(WBP_IngameMenu_WorkSpace_C_FilteringRecipe, CallFunc_Array_Get_Item_2) == 0x0000D8, "Member 'WBP_IngameMenu_WorkSpace_C_FilteringRecipe::CallFunc_Array_Get_Item_2' has a wrong offset!");
static_assert(offsetof(WBP_IngameMenu_WorkSpace_C_FilteringRecipe, CallFunc_Array_RemoveItem_ReturnValue) == 0x0000E0, "Member 'WBP_IngameMenu_WorkSpace_C_FilteringRecipe::CallFunc_Array_RemoveItem_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_IngameMenu_WorkSpace_C_FilteringRecipe, CallFunc_Map_Find_Value) == 0x0000E4, "Member 'WBP_IngameMenu_WorkSpace_C_FilteringRecipe::CallFunc_Map_Find_Value' has a wrong offset!");
static_assert(offsetof(WBP_IngameMenu_WorkSpace_C_FilteringRecipe, CallFunc_Map_Find_ReturnValue) == 0x0000EC, "Member 'WBP_IngameMenu_WorkSpace_C_FilteringRecipe::CallFunc_Map_Find_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_IngameMenu_WorkSpace_C_FilteringRecipe, CallFunc_Array_Length_ReturnValue_2) == 0x0000F0, "Member 'WBP_IngameMenu_WorkSpace_C_FilteringRecipe::CallFunc_Array_Length_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(WBP_IngameMenu_WorkSpace_C_FilteringRecipe, CallFunc_Less_IntInt_ReturnValue_2) == 0x0000F4, "Member 'WBP_IngameMenu_WorkSpace_C_FilteringRecipe::CallFunc_Less_IntInt_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(WBP_IngameMenu_WorkSpace_C_FilteringRecipe, CallFunc_Array_RemoveItem_ReturnValue_1) == 0x0000F5, "Member 'WBP_IngameMenu_WorkSpace_C_FilteringRecipe::CallFunc_Array_RemoveItem_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(WBP_IngameMenu_WorkSpace_C_FilteringRecipe, CallFunc_CollectLocalPlayerControllableItemInfos_OutItemInfos) == 0x0000F8, "Member 'WBP_IngameMenu_WorkSpace_C_FilteringRecipe::CallFunc_CollectLocalPlayerControllableItemInfos_OutItemInfos' has a wrong offset!");
static_assert(offsetof(WBP_IngameMenu_WorkSpace_C_FilteringRecipe, CallFunc_GetItemRecipeDataTableAccess_ReturnValue) == 0x000108, "Member 'WBP_IngameMenu_WorkSpace_C_FilteringRecipe::CallFunc_GetItemRecipeDataTableAccess_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_IngameMenu_WorkSpace_C_FilteringRecipe, CallFunc_GetLocalTechnologyData_ReturnValue) == 0x000110, "Member 'WBP_IngameMenu_WorkSpace_C_FilteringRecipe::CallFunc_GetLocalTechnologyData_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_IngameMenu_WorkSpace_C_FilteringRecipe, CallFunc_BP_FindRow_bResult) == 0x000118, "Member 'WBP_IngameMenu_WorkSpace_C_FilteringRecipe::CallFunc_BP_FindRow_bResult' has a wrong offset!");
static_assert(offsetof(WBP_IngameMenu_WorkSpace_C_FilteringRecipe, CallFunc_BP_FindRow_ReturnValue) == 0x000120, "Member 'WBP_IngameMenu_WorkSpace_C_FilteringRecipe::CallFunc_BP_FindRow_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_IngameMenu_WorkSpace_C_FilteringRecipe, CallFunc_IsValid_ReturnValue) == 0x000190, "Member 'WBP_IngameMenu_WorkSpace_C_FilteringRecipe::CallFunc_IsValid_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_IngameMenu_WorkSpace_C_FilteringRecipe, CallFunc_NotEqual_NameName_ReturnValue) == 0x000191, "Member 'WBP_IngameMenu_WorkSpace_C_FilteringRecipe::CallFunc_NotEqual_NameName_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_IngameMenu_WorkSpace_C_FilteringRecipe, CallFunc_Array_AddUnique_ReturnValue) == 0x000194, "Member 'WBP_IngameMenu_WorkSpace_C_FilteringRecipe::CallFunc_Array_AddUnique_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_IngameMenu_WorkSpace_C_FilteringRecipe, CallFunc_FilteringUnlockedRecipe_OutRecipeIdArray) == 0x000198, "Member 'WBP_IngameMenu_WorkSpace_C_FilteringRecipe::CallFunc_FilteringUnlockedRecipe_OutRecipeIdArray' has a wrong offset!");

// Function WBP_IngameMenu_WorkSpace.WBP_IngameMenu_WorkSpace_C.FilterSkillUnlocker
// 0x0050 (0x0050 - 0x0000)
struct WBP_IngameMenu_WorkSpace_C_FilterSkillUnlocker final
{
public:
	TArray<class FName>                           Recipes;                                           // 0x0000(0x0010)(BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
	class FName                                   WorkBenchId;                                       // 0x0010(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TArray<class FName>                           FilteredRecipes;                                   // 0x0018(0x0010)(Parm, OutParm)
	TArray<class FName>                           TempRecipes;                                       // 0x0028(0x0010)(Edit, BlueprintVisible)
	TArray<class FName>                           Filtered;                                          // 0x0038(0x0010)(Edit, BlueprintVisible)
	ESlateVisibility                              Temp_byte_Variable;                                // 0x0048(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_EqualEqual_NameName_ReturnValue;          // 0x0049(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ESlateVisibility                              Temp_byte_Variable_1;                              // 0x004A(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Temp_bool_Variable;                                // 0x004B(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ESlateVisibility                              K2Node_Select_Default;                             // 0x004C(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WBP_IngameMenu_WorkSpace_C_FilterSkillUnlocker) == 0x000008, "Wrong alignment on WBP_IngameMenu_WorkSpace_C_FilterSkillUnlocker");
static_assert(sizeof(WBP_IngameMenu_WorkSpace_C_FilterSkillUnlocker) == 0x000050, "Wrong size on WBP_IngameMenu_WorkSpace_C_FilterSkillUnlocker");
static_assert(offsetof(WBP_IngameMenu_WorkSpace_C_FilterSkillUnlocker, Recipes) == 0x000000, "Member 'WBP_IngameMenu_WorkSpace_C_FilterSkillUnlocker::Recipes' has a wrong offset!");
static_assert(offsetof(WBP_IngameMenu_WorkSpace_C_FilterSkillUnlocker, WorkBenchId) == 0x000010, "Member 'WBP_IngameMenu_WorkSpace_C_FilterSkillUnlocker::WorkBenchId' has a wrong offset!");
static_assert(offsetof(WBP_IngameMenu_WorkSpace_C_FilterSkillUnlocker, FilteredRecipes) == 0x000018, "Member 'WBP_IngameMenu_WorkSpace_C_FilterSkillUnlocker::FilteredRecipes' has a wrong offset!");
static_assert(offsetof(WBP_IngameMenu_WorkSpace_C_FilterSkillUnlocker, TempRecipes) == 0x000028, "Member 'WBP_IngameMenu_WorkSpace_C_FilterSkillUnlocker::TempRecipes' has a wrong offset!");
static_assert(offsetof(WBP_IngameMenu_WorkSpace_C_FilterSkillUnlocker, Filtered) == 0x000038, "Member 'WBP_IngameMenu_WorkSpace_C_FilterSkillUnlocker::Filtered' has a wrong offset!");
static_assert(offsetof(WBP_IngameMenu_WorkSpace_C_FilterSkillUnlocker, Temp_byte_Variable) == 0x000048, "Member 'WBP_IngameMenu_WorkSpace_C_FilterSkillUnlocker::Temp_byte_Variable' has a wrong offset!");
static_assert(offsetof(WBP_IngameMenu_WorkSpace_C_FilterSkillUnlocker, CallFunc_EqualEqual_NameName_ReturnValue) == 0x000049, "Member 'WBP_IngameMenu_WorkSpace_C_FilterSkillUnlocker::CallFunc_EqualEqual_NameName_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_IngameMenu_WorkSpace_C_FilterSkillUnlocker, Temp_byte_Variable_1) == 0x00004A, "Member 'WBP_IngameMenu_WorkSpace_C_FilterSkillUnlocker::Temp_byte_Variable_1' has a wrong offset!");
static_assert(offsetof(WBP_IngameMenu_WorkSpace_C_FilterSkillUnlocker, Temp_bool_Variable) == 0x00004B, "Member 'WBP_IngameMenu_WorkSpace_C_FilterSkillUnlocker::Temp_bool_Variable' has a wrong offset!");
static_assert(offsetof(WBP_IngameMenu_WorkSpace_C_FilterSkillUnlocker, K2Node_Select_Default) == 0x00004C, "Member 'WBP_IngameMenu_WorkSpace_C_FilterSkillUnlocker::K2Node_Select_Default' has a wrong offset!");

// Function WBP_IngameMenu_WorkSpace.WBP_IngameMenu_WorkSpace_C.InputMethodChanged
// 0x0007 (0x0007 - 0x0000)
struct WBP_IngameMenu_WorkSpace_C_InputMethodChanged final
{
public:
	ECommonInputType                              InputType;                                         // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_EqualEqual_ByteByte_ReturnValue;          // 0x0001(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FPalSlateNavigationSetting             K2Node_MakeStruct_PalSlateNavigationSetting;       // 0x0002(0x0005)(NoDestructor)
};
static_assert(alignof(WBP_IngameMenu_WorkSpace_C_InputMethodChanged) == 0x000001, "Wrong alignment on WBP_IngameMenu_WorkSpace_C_InputMethodChanged");
static_assert(sizeof(WBP_IngameMenu_WorkSpace_C_InputMethodChanged) == 0x000007, "Wrong size on WBP_IngameMenu_WorkSpace_C_InputMethodChanged");
static_assert(offsetof(WBP_IngameMenu_WorkSpace_C_InputMethodChanged, InputType) == 0x000000, "Member 'WBP_IngameMenu_WorkSpace_C_InputMethodChanged::InputType' has a wrong offset!");
static_assert(offsetof(WBP_IngameMenu_WorkSpace_C_InputMethodChanged, CallFunc_EqualEqual_ByteByte_ReturnValue) == 0x000001, "Member 'WBP_IngameMenu_WorkSpace_C_InputMethodChanged::CallFunc_EqualEqual_ByteByte_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_IngameMenu_WorkSpace_C_InputMethodChanged, K2Node_MakeStruct_PalSlateNavigationSetting) == 0x000002, "Member 'WBP_IngameMenu_WorkSpace_C_InputMethodChanged::K2Node_MakeStruct_PalSlateNavigationSetting' has a wrong offset!");

// Function WBP_IngameMenu_WorkSpace.WBP_IngameMenu_WorkSpace_C.IsSelectingProductNum
// 0x0001 (0x0001 - 0x0000)
struct WBP_IngameMenu_WorkSpace_C_IsSelectingProductNum final
{
public:
	bool                                          IsSelecting;                                       // 0x0000(0x0001)(Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WBP_IngameMenu_WorkSpace_C_IsSelectingProductNum) == 0x000001, "Wrong alignment on WBP_IngameMenu_WorkSpace_C_IsSelectingProductNum");
static_assert(sizeof(WBP_IngameMenu_WorkSpace_C_IsSelectingProductNum) == 0x000001, "Wrong size on WBP_IngameMenu_WorkSpace_C_IsSelectingProductNum");
static_assert(offsetof(WBP_IngameMenu_WorkSpace_C_IsSelectingProductNum, IsSelecting) == 0x000000, "Member 'WBP_IngameMenu_WorkSpace_C_IsSelectingProductNum::IsSelecting' has a wrong offset!");

// Function WBP_IngameMenu_WorkSpace.WBP_IngameMenu_WorkSpace_C.OnCancelInput
// 0x0002 (0x0002 - 0x0000)
struct WBP_IngameMenu_WorkSpace_C_OnCancelInput final
{
public:
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x0000(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Not_PreBool_ReturnValue;                  // 0x0001(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WBP_IngameMenu_WorkSpace_C_OnCancelInput) == 0x000001, "Wrong alignment on WBP_IngameMenu_WorkSpace_C_OnCancelInput");
static_assert(sizeof(WBP_IngameMenu_WorkSpace_C_OnCancelInput) == 0x000002, "Wrong size on WBP_IngameMenu_WorkSpace_C_OnCancelInput");
static_assert(offsetof(WBP_IngameMenu_WorkSpace_C_OnCancelInput, CallFunc_IsValid_ReturnValue) == 0x000000, "Member 'WBP_IngameMenu_WorkSpace_C_OnCancelInput::CallFunc_IsValid_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_IngameMenu_WorkSpace_C_OnCancelInput, CallFunc_Not_PreBool_ReturnValue) == 0x000001, "Member 'WBP_IngameMenu_WorkSpace_C_OnCancelInput::CallFunc_Not_PreBool_ReturnValue' has a wrong offset!");

// Function WBP_IngameMenu_WorkSpace.WBP_IngameMenu_WorkSpace_C.OnClickedRecipeSlot
// 0x0178 (0x0178 - 0x0000)
struct WBP_IngameMenu_WorkSpace_C_OnClickedRecipeSlot final
{
public:
	class UWBP_PalConvertItemMenu_RecipeSlotButton_C* Slot_0;                                        // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	TMap<class FName, int32>                      MaterialDetails;                                   // 0x0008(0x0050)(Edit, BlueprintVisible)
	struct FPalSlateNavigationSetting             K2Node_MakeStruct_PalSlateNavigationSetting;       // 0x0058(0x0005)(NoDestructor)
	uint8                                         Pad_5D[0x3];                                       // 0x005D(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_CalcMaxProductableNum_ReturnValue;        // 0x0060(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Max_ReturnValue;                          // 0x0064(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int64                                         CallFunc_Conv_IntToInt64_ReturnValue;              // 0x0068(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FName                                   CallFunc_GetRecipeID_recipeID;                     // 0x0070(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_NotEqual_ObjectObject_ReturnValue;        // 0x0078(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x0079(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_7A[0x6];                                       // 0x007A(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	class UPalMasterDataTableAccess_ItemRecipe*   CallFunc_GetItemRecipeDataTableAccess_ReturnValue; // 0x0080(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_BP_FindRow_bResult;                       // 0x0088(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_89[0x7];                                       // 0x0089(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	struct FPalItemRecipe                         CallFunc_BP_FindRow_ReturnValue;                   // 0x0090(0x0070)()
	class FText                                   CallFunc_Conv_IntToText_ReturnValue;               // 0x0100(0x0018)()
	TArray<class FName>                           K2Node_MakeArray_Array;                            // 0x0118(0x0010)(ReferenceParm)
	TArray<struct FPalStaticItemIdAndNum>         CallFunc_CollectLocalPlayerControllableItemInfos_OutItemInfos; // 0x0128(0x0010)(ReferenceParm)
	class FText                                   CallFunc_GetItemName_outName;                      // 0x0138(0x0018)()
	struct FPalStaticItemIdAndNum                 CallFunc_Array_Get_Item;                           // 0x0150(0x000C)(NoDestructor)
	bool                                          CallFunc_Array_IsEmpty_ReturnValue;                // 0x015C(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_15D[0x3];                                      // 0x015D(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	class FText                                   CallFunc_Conv_IntToText_ReturnValue_1;             // 0x0160(0x0018)()
};
static_assert(alignof(WBP_IngameMenu_WorkSpace_C_OnClickedRecipeSlot) == 0x000008, "Wrong alignment on WBP_IngameMenu_WorkSpace_C_OnClickedRecipeSlot");
static_assert(sizeof(WBP_IngameMenu_WorkSpace_C_OnClickedRecipeSlot) == 0x000178, "Wrong size on WBP_IngameMenu_WorkSpace_C_OnClickedRecipeSlot");
static_assert(offsetof(WBP_IngameMenu_WorkSpace_C_OnClickedRecipeSlot, Slot_0) == 0x000000, "Member 'WBP_IngameMenu_WorkSpace_C_OnClickedRecipeSlot::Slot_0' has a wrong offset!");
static_assert(offsetof(WBP_IngameMenu_WorkSpace_C_OnClickedRecipeSlot, MaterialDetails) == 0x000008, "Member 'WBP_IngameMenu_WorkSpace_C_OnClickedRecipeSlot::MaterialDetails' has a wrong offset!");
static_assert(offsetof(WBP_IngameMenu_WorkSpace_C_OnClickedRecipeSlot, K2Node_MakeStruct_PalSlateNavigationSetting) == 0x000058, "Member 'WBP_IngameMenu_WorkSpace_C_OnClickedRecipeSlot::K2Node_MakeStruct_PalSlateNavigationSetting' has a wrong offset!");
static_assert(offsetof(WBP_IngameMenu_WorkSpace_C_OnClickedRecipeSlot, CallFunc_CalcMaxProductableNum_ReturnValue) == 0x000060, "Member 'WBP_IngameMenu_WorkSpace_C_OnClickedRecipeSlot::CallFunc_CalcMaxProductableNum_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_IngameMenu_WorkSpace_C_OnClickedRecipeSlot, CallFunc_Max_ReturnValue) == 0x000064, "Member 'WBP_IngameMenu_WorkSpace_C_OnClickedRecipeSlot::CallFunc_Max_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_IngameMenu_WorkSpace_C_OnClickedRecipeSlot, CallFunc_Conv_IntToInt64_ReturnValue) == 0x000068, "Member 'WBP_IngameMenu_WorkSpace_C_OnClickedRecipeSlot::CallFunc_Conv_IntToInt64_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_IngameMenu_WorkSpace_C_OnClickedRecipeSlot, CallFunc_GetRecipeID_recipeID) == 0x000070, "Member 'WBP_IngameMenu_WorkSpace_C_OnClickedRecipeSlot::CallFunc_GetRecipeID_recipeID' has a wrong offset!");
static_assert(offsetof(WBP_IngameMenu_WorkSpace_C_OnClickedRecipeSlot, CallFunc_NotEqual_ObjectObject_ReturnValue) == 0x000078, "Member 'WBP_IngameMenu_WorkSpace_C_OnClickedRecipeSlot::CallFunc_NotEqual_ObjectObject_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_IngameMenu_WorkSpace_C_OnClickedRecipeSlot, CallFunc_IsValid_ReturnValue) == 0x000079, "Member 'WBP_IngameMenu_WorkSpace_C_OnClickedRecipeSlot::CallFunc_IsValid_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_IngameMenu_WorkSpace_C_OnClickedRecipeSlot, CallFunc_GetItemRecipeDataTableAccess_ReturnValue) == 0x000080, "Member 'WBP_IngameMenu_WorkSpace_C_OnClickedRecipeSlot::CallFunc_GetItemRecipeDataTableAccess_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_IngameMenu_WorkSpace_C_OnClickedRecipeSlot, CallFunc_BP_FindRow_bResult) == 0x000088, "Member 'WBP_IngameMenu_WorkSpace_C_OnClickedRecipeSlot::CallFunc_BP_FindRow_bResult' has a wrong offset!");
static_assert(offsetof(WBP_IngameMenu_WorkSpace_C_OnClickedRecipeSlot, CallFunc_BP_FindRow_ReturnValue) == 0x000090, "Member 'WBP_IngameMenu_WorkSpace_C_OnClickedRecipeSlot::CallFunc_BP_FindRow_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_IngameMenu_WorkSpace_C_OnClickedRecipeSlot, CallFunc_Conv_IntToText_ReturnValue) == 0x000100, "Member 'WBP_IngameMenu_WorkSpace_C_OnClickedRecipeSlot::CallFunc_Conv_IntToText_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_IngameMenu_WorkSpace_C_OnClickedRecipeSlot, K2Node_MakeArray_Array) == 0x000118, "Member 'WBP_IngameMenu_WorkSpace_C_OnClickedRecipeSlot::K2Node_MakeArray_Array' has a wrong offset!");
static_assert(offsetof(WBP_IngameMenu_WorkSpace_C_OnClickedRecipeSlot, CallFunc_CollectLocalPlayerControllableItemInfos_OutItemInfos) == 0x000128, "Member 'WBP_IngameMenu_WorkSpace_C_OnClickedRecipeSlot::CallFunc_CollectLocalPlayerControllableItemInfos_OutItemInfos' has a wrong offset!");
static_assert(offsetof(WBP_IngameMenu_WorkSpace_C_OnClickedRecipeSlot, CallFunc_GetItemName_outName) == 0x000138, "Member 'WBP_IngameMenu_WorkSpace_C_OnClickedRecipeSlot::CallFunc_GetItemName_outName' has a wrong offset!");
static_assert(offsetof(WBP_IngameMenu_WorkSpace_C_OnClickedRecipeSlot, CallFunc_Array_Get_Item) == 0x000150, "Member 'WBP_IngameMenu_WorkSpace_C_OnClickedRecipeSlot::CallFunc_Array_Get_Item' has a wrong offset!");
static_assert(offsetof(WBP_IngameMenu_WorkSpace_C_OnClickedRecipeSlot, CallFunc_Array_IsEmpty_ReturnValue) == 0x00015C, "Member 'WBP_IngameMenu_WorkSpace_C_OnClickedRecipeSlot::CallFunc_Array_IsEmpty_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_IngameMenu_WorkSpace_C_OnClickedRecipeSlot, CallFunc_Conv_IntToText_ReturnValue_1) == 0x000160, "Member 'WBP_IngameMenu_WorkSpace_C_OnClickedRecipeSlot::CallFunc_Conv_IntToText_ReturnValue_1' has a wrong offset!");

// Function WBP_IngameMenu_WorkSpace.WBP_IngameMenu_WorkSpace_C.OnHoveredRecipeSlot
// 0x0140 (0x0140 - 0x0000)
struct WBP_IngameMenu_WorkSpace_C_OnHoveredRecipeSlot final
{
public:
	class UWBP_PalConvertItemMenu_RecipeSlotButton_C* Slot_0;                                        // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	class FName                                   CallFunc_GetRecipeID_recipeID;                     // 0x0008(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UPalMapObjectConvertItemModel*          CallFunc_TryGetConcreteModel_Model;                // 0x0010(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_TryGetConcreteModel_ReturnValue;          // 0x0018(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_19[0x7];                                       // 0x0019(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UPalHUDService*                         CallFunc_GetHUDService_ReturnValue;                // 0x0020(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	TMap<class FName, int32>                      CallFunc_GetProductItemRequiredMaterialInfoMap_OutRequiredMaterialInfoMap; // 0x0028(0x0050)()
	struct FPalUICommonItemInfoDisplayData        K2Node_MakeStruct_PalUICommonItemInfoDisplayData;  // 0x0078(0x00C8)(ContainsInstancedReference)
};
static_assert(alignof(WBP_IngameMenu_WorkSpace_C_OnHoveredRecipeSlot) == 0x000008, "Wrong alignment on WBP_IngameMenu_WorkSpace_C_OnHoveredRecipeSlot");
static_assert(sizeof(WBP_IngameMenu_WorkSpace_C_OnHoveredRecipeSlot) == 0x000140, "Wrong size on WBP_IngameMenu_WorkSpace_C_OnHoveredRecipeSlot");
static_assert(offsetof(WBP_IngameMenu_WorkSpace_C_OnHoveredRecipeSlot, Slot_0) == 0x000000, "Member 'WBP_IngameMenu_WorkSpace_C_OnHoveredRecipeSlot::Slot_0' has a wrong offset!");
static_assert(offsetof(WBP_IngameMenu_WorkSpace_C_OnHoveredRecipeSlot, CallFunc_GetRecipeID_recipeID) == 0x000008, "Member 'WBP_IngameMenu_WorkSpace_C_OnHoveredRecipeSlot::CallFunc_GetRecipeID_recipeID' has a wrong offset!");
static_assert(offsetof(WBP_IngameMenu_WorkSpace_C_OnHoveredRecipeSlot, CallFunc_TryGetConcreteModel_Model) == 0x000010, "Member 'WBP_IngameMenu_WorkSpace_C_OnHoveredRecipeSlot::CallFunc_TryGetConcreteModel_Model' has a wrong offset!");
static_assert(offsetof(WBP_IngameMenu_WorkSpace_C_OnHoveredRecipeSlot, CallFunc_TryGetConcreteModel_ReturnValue) == 0x000018, "Member 'WBP_IngameMenu_WorkSpace_C_OnHoveredRecipeSlot::CallFunc_TryGetConcreteModel_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_IngameMenu_WorkSpace_C_OnHoveredRecipeSlot, CallFunc_GetHUDService_ReturnValue) == 0x000020, "Member 'WBP_IngameMenu_WorkSpace_C_OnHoveredRecipeSlot::CallFunc_GetHUDService_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_IngameMenu_WorkSpace_C_OnHoveredRecipeSlot, CallFunc_GetProductItemRequiredMaterialInfoMap_OutRequiredMaterialInfoMap) == 0x000028, "Member 'WBP_IngameMenu_WorkSpace_C_OnHoveredRecipeSlot::CallFunc_GetProductItemRequiredMaterialInfoMap_OutRequiredMaterialInfoMap' has a wrong offset!");
static_assert(offsetof(WBP_IngameMenu_WorkSpace_C_OnHoveredRecipeSlot, K2Node_MakeStruct_PalUICommonItemInfoDisplayData) == 0x000078, "Member 'WBP_IngameMenu_WorkSpace_C_OnHoveredRecipeSlot::K2Node_MakeStruct_PalUICommonItemInfoDisplayData' has a wrong offset!");

// Function WBP_IngameMenu_WorkSpace.WBP_IngameMenu_WorkSpace_C.OnUnhoveredRecipeSlot
// 0x0010 (0x0010 - 0x0000)
struct WBP_IngameMenu_WorkSpace_C_OnUnhoveredRecipeSlot final
{
public:
	class UWBP_PalConvertItemMenu_RecipeSlotButton_C* Slot_0;                                        // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	class UPalHUDService*                         CallFunc_GetHUDService_ReturnValue;                // 0x0008(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WBP_IngameMenu_WorkSpace_C_OnUnhoveredRecipeSlot) == 0x000008, "Wrong alignment on WBP_IngameMenu_WorkSpace_C_OnUnhoveredRecipeSlot");
static_assert(sizeof(WBP_IngameMenu_WorkSpace_C_OnUnhoveredRecipeSlot) == 0x000010, "Wrong size on WBP_IngameMenu_WorkSpace_C_OnUnhoveredRecipeSlot");
static_assert(offsetof(WBP_IngameMenu_WorkSpace_C_OnUnhoveredRecipeSlot, Slot_0) == 0x000000, "Member 'WBP_IngameMenu_WorkSpace_C_OnUnhoveredRecipeSlot::Slot_0' has a wrong offset!");
static_assert(offsetof(WBP_IngameMenu_WorkSpace_C_OnUnhoveredRecipeSlot, CallFunc_GetHUDService_ReturnValue) == 0x000008, "Member 'WBP_IngameMenu_WorkSpace_C_OnUnhoveredRecipeSlot::CallFunc_GetHUDService_ReturnValue' has a wrong offset!");

// Function WBP_IngameMenu_WorkSpace.WBP_IngameMenu_WorkSpace_C.OnUpdateCanTransportOut
// 0x0001 (0x0001 - 0x0000)
struct WBP_IngameMenu_WorkSpace_C_OnUpdateCanTransportOut final
{
public:
	bool                                          bOn;                                               // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WBP_IngameMenu_WorkSpace_C_OnUpdateCanTransportOut) == 0x000001, "Wrong alignment on WBP_IngameMenu_WorkSpace_C_OnUpdateCanTransportOut");
static_assert(sizeof(WBP_IngameMenu_WorkSpace_C_OnUpdateCanTransportOut) == 0x000001, "Wrong size on WBP_IngameMenu_WorkSpace_C_OnUpdateCanTransportOut");
static_assert(offsetof(WBP_IngameMenu_WorkSpace_C_OnUpdateCanTransportOut, bOn) == 0x000000, "Member 'WBP_IngameMenu_WorkSpace_C_OnUpdateCanTransportOut::bOn' has a wrong offset!");

// Function WBP_IngameMenu_WorkSpace.WBP_IngameMenu_WorkSpace_C.Setup
// 0x0140 (0x0140 - 0x0000)
struct WBP_IngameMenu_WorkSpace_C_Setup final
{
public:
	ESlateVisibility                              Temp_byte_Variable;                                // 0x0000(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_1[0x3];                                        // 0x0001(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	TDelegate<void(bool bOn)>                     K2Node_CreateDelegate_OutputDelegate;              // 0x0004(0x0010)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	TDelegate<void()>                             K2Node_CreateDelegate_OutputDelegate_1;            // 0x0014(0x0010)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	struct FPalUIActionBindData                   CallFunc_RegisterActionBinding_ReturnValue;        // 0x0024(0x0004)(NoDestructor)
	ESlateVisibility                              Temp_byte_Variable_1;                              // 0x0028(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_29[0x3];                                       // 0x0029(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	TDelegate<void()>                             K2Node_CreateDelegate_OutputDelegate_2;            // 0x002C(0x0010)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	TDelegate<void()>                             K2Node_CreateDelegate_OutputDelegate_3;            // 0x003C(0x0010)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	struct FPalUIActionBindData                   CallFunc_RegisterActionBinding_ReturnValue_1;      // 0x004C(0x0004)(NoDestructor)
	TDelegate<void()>                             K2Node_CreateDelegate_OutputDelegate_4;            // 0x0050(0x0010)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	TDelegate<void()>                             K2Node_CreateDelegate_OutputDelegate_5;            // 0x0060(0x0010)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	struct FPalUIActionBindData                   CallFunc_RegisterActionBinding_ReturnValue_2;      // 0x0070(0x0004)(NoDestructor)
	struct FPalUIActionBindData                   CallFunc_RegisterActionBinding_ReturnValue_3;      // 0x0074(0x0004)(NoDestructor)
	TDelegate<void(class UWBP_PalConvertItemMenu_RecipeSlotButton_C* Widget)> K2Node_CreateDelegate_OutputDelegate_6; // 0x0078(0x0010)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	TDelegate<void(class UWBP_PalConvertItemMenu_RecipeSlotButton_C* Widget)> K2Node_CreateDelegate_OutputDelegate_7; // 0x0088(0x0010)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          Temp_bool_Variable;                                // 0x0098(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_99[0x3];                                       // 0x0099(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	TDelegate<void(class UWBP_PalConvertItemMenu_RecipeSlotButton_C* Widget)> K2Node_CreateDelegate_OutputDelegate_8; // 0x009C(0x0010)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_AC[0x4];                                       // 0x00AC(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UPalHUDDispatchParameterBase*           CallFunc_GetParam_ReturnValue;                     // 0x00B0(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class UPalMapObjectConvertItemModel*          CallFunc_TryGetConcreteModel_Model;                // 0x00B8(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_TryGetConcreteModel_ReturnValue;          // 0x00C0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_C1[0x7];                                       // 0x00C1(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UPalHUDDispatchParameter_ConvertItem*   K2Node_DynamicCast_AsPal_HUDDispatch_Parameter_Convert_Item; // 0x00C8(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x00D0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_D1[0x7];                                       // 0x00D1(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<class FName>                           CallFunc_GetRecipes_ReturnValue;                   // 0x00D8(0x0010)(ConstParm, ReferenceParm)
	class FName                                   CallFunc_TryGetMapObjectId_ReturnValue;            // 0x00E8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TArray<class FName>                           CallFunc_FilteringRecipe_FilteredArray;            // 0x00F0(0x0010)(ReferenceParm)
	class FText                                   CallFunc_GetMapObjectName_outName;                 // 0x0100(0x0018)()
	TArray<class FName>                           CallFunc_FilterSkillUnlocker_FilteredRecipes;      // 0x0118(0x0010)(ReferenceParm)
	bool                                          CallFunc_Array_IsEmpty_ReturnValue;                // 0x0128(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ESlateVisibility                              K2Node_Select_Default;                             // 0x0129(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_12A[0x6];                                      // 0x012A(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	class UBP_PalUIConvertItemModel_C*            CallFunc_SpawnObject_ReturnValue;                  // 0x0130(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class UWBP_ConvertItemMenuScrollListBlock_C*  CallFunc_AddRecipeSet_createdBlock;                // 0x0138(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WBP_IngameMenu_WorkSpace_C_Setup) == 0x000008, "Wrong alignment on WBP_IngameMenu_WorkSpace_C_Setup");
static_assert(sizeof(WBP_IngameMenu_WorkSpace_C_Setup) == 0x000140, "Wrong size on WBP_IngameMenu_WorkSpace_C_Setup");
static_assert(offsetof(WBP_IngameMenu_WorkSpace_C_Setup, Temp_byte_Variable) == 0x000000, "Member 'WBP_IngameMenu_WorkSpace_C_Setup::Temp_byte_Variable' has a wrong offset!");
static_assert(offsetof(WBP_IngameMenu_WorkSpace_C_Setup, K2Node_CreateDelegate_OutputDelegate) == 0x000004, "Member 'WBP_IngameMenu_WorkSpace_C_Setup::K2Node_CreateDelegate_OutputDelegate' has a wrong offset!");
static_assert(offsetof(WBP_IngameMenu_WorkSpace_C_Setup, K2Node_CreateDelegate_OutputDelegate_1) == 0x000014, "Member 'WBP_IngameMenu_WorkSpace_C_Setup::K2Node_CreateDelegate_OutputDelegate_1' has a wrong offset!");
static_assert(offsetof(WBP_IngameMenu_WorkSpace_C_Setup, CallFunc_RegisterActionBinding_ReturnValue) == 0x000024, "Member 'WBP_IngameMenu_WorkSpace_C_Setup::CallFunc_RegisterActionBinding_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_IngameMenu_WorkSpace_C_Setup, Temp_byte_Variable_1) == 0x000028, "Member 'WBP_IngameMenu_WorkSpace_C_Setup::Temp_byte_Variable_1' has a wrong offset!");
static_assert(offsetof(WBP_IngameMenu_WorkSpace_C_Setup, K2Node_CreateDelegate_OutputDelegate_2) == 0x00002C, "Member 'WBP_IngameMenu_WorkSpace_C_Setup::K2Node_CreateDelegate_OutputDelegate_2' has a wrong offset!");
static_assert(offsetof(WBP_IngameMenu_WorkSpace_C_Setup, K2Node_CreateDelegate_OutputDelegate_3) == 0x00003C, "Member 'WBP_IngameMenu_WorkSpace_C_Setup::K2Node_CreateDelegate_OutputDelegate_3' has a wrong offset!");
static_assert(offsetof(WBP_IngameMenu_WorkSpace_C_Setup, CallFunc_RegisterActionBinding_ReturnValue_1) == 0x00004C, "Member 'WBP_IngameMenu_WorkSpace_C_Setup::CallFunc_RegisterActionBinding_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(WBP_IngameMenu_WorkSpace_C_Setup, K2Node_CreateDelegate_OutputDelegate_4) == 0x000050, "Member 'WBP_IngameMenu_WorkSpace_C_Setup::K2Node_CreateDelegate_OutputDelegate_4' has a wrong offset!");
static_assert(offsetof(WBP_IngameMenu_WorkSpace_C_Setup, K2Node_CreateDelegate_OutputDelegate_5) == 0x000060, "Member 'WBP_IngameMenu_WorkSpace_C_Setup::K2Node_CreateDelegate_OutputDelegate_5' has a wrong offset!");
static_assert(offsetof(WBP_IngameMenu_WorkSpace_C_Setup, CallFunc_RegisterActionBinding_ReturnValue_2) == 0x000070, "Member 'WBP_IngameMenu_WorkSpace_C_Setup::CallFunc_RegisterActionBinding_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(WBP_IngameMenu_WorkSpace_C_Setup, CallFunc_RegisterActionBinding_ReturnValue_3) == 0x000074, "Member 'WBP_IngameMenu_WorkSpace_C_Setup::CallFunc_RegisterActionBinding_ReturnValue_3' has a wrong offset!");
static_assert(offsetof(WBP_IngameMenu_WorkSpace_C_Setup, K2Node_CreateDelegate_OutputDelegate_6) == 0x000078, "Member 'WBP_IngameMenu_WorkSpace_C_Setup::K2Node_CreateDelegate_OutputDelegate_6' has a wrong offset!");
static_assert(offsetof(WBP_IngameMenu_WorkSpace_C_Setup, K2Node_CreateDelegate_OutputDelegate_7) == 0x000088, "Member 'WBP_IngameMenu_WorkSpace_C_Setup::K2Node_CreateDelegate_OutputDelegate_7' has a wrong offset!");
static_assert(offsetof(WBP_IngameMenu_WorkSpace_C_Setup, Temp_bool_Variable) == 0x000098, "Member 'WBP_IngameMenu_WorkSpace_C_Setup::Temp_bool_Variable' has a wrong offset!");
static_assert(offsetof(WBP_IngameMenu_WorkSpace_C_Setup, K2Node_CreateDelegate_OutputDelegate_8) == 0x00009C, "Member 'WBP_IngameMenu_WorkSpace_C_Setup::K2Node_CreateDelegate_OutputDelegate_8' has a wrong offset!");
static_assert(offsetof(WBP_IngameMenu_WorkSpace_C_Setup, CallFunc_GetParam_ReturnValue) == 0x0000B0, "Member 'WBP_IngameMenu_WorkSpace_C_Setup::CallFunc_GetParam_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_IngameMenu_WorkSpace_C_Setup, CallFunc_TryGetConcreteModel_Model) == 0x0000B8, "Member 'WBP_IngameMenu_WorkSpace_C_Setup::CallFunc_TryGetConcreteModel_Model' has a wrong offset!");
static_assert(offsetof(WBP_IngameMenu_WorkSpace_C_Setup, CallFunc_TryGetConcreteModel_ReturnValue) == 0x0000C0, "Member 'WBP_IngameMenu_WorkSpace_C_Setup::CallFunc_TryGetConcreteModel_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_IngameMenu_WorkSpace_C_Setup, K2Node_DynamicCast_AsPal_HUDDispatch_Parameter_Convert_Item) == 0x0000C8, "Member 'WBP_IngameMenu_WorkSpace_C_Setup::K2Node_DynamicCast_AsPal_HUDDispatch_Parameter_Convert_Item' has a wrong offset!");
static_assert(offsetof(WBP_IngameMenu_WorkSpace_C_Setup, K2Node_DynamicCast_bSuccess) == 0x0000D0, "Member 'WBP_IngameMenu_WorkSpace_C_Setup::K2Node_DynamicCast_bSuccess' has a wrong offset!");
static_assert(offsetof(WBP_IngameMenu_WorkSpace_C_Setup, CallFunc_GetRecipes_ReturnValue) == 0x0000D8, "Member 'WBP_IngameMenu_WorkSpace_C_Setup::CallFunc_GetRecipes_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_IngameMenu_WorkSpace_C_Setup, CallFunc_TryGetMapObjectId_ReturnValue) == 0x0000E8, "Member 'WBP_IngameMenu_WorkSpace_C_Setup::CallFunc_TryGetMapObjectId_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_IngameMenu_WorkSpace_C_Setup, CallFunc_FilteringRecipe_FilteredArray) == 0x0000F0, "Member 'WBP_IngameMenu_WorkSpace_C_Setup::CallFunc_FilteringRecipe_FilteredArray' has a wrong offset!");
static_assert(offsetof(WBP_IngameMenu_WorkSpace_C_Setup, CallFunc_GetMapObjectName_outName) == 0x000100, "Member 'WBP_IngameMenu_WorkSpace_C_Setup::CallFunc_GetMapObjectName_outName' has a wrong offset!");
static_assert(offsetof(WBP_IngameMenu_WorkSpace_C_Setup, CallFunc_FilterSkillUnlocker_FilteredRecipes) == 0x000118, "Member 'WBP_IngameMenu_WorkSpace_C_Setup::CallFunc_FilterSkillUnlocker_FilteredRecipes' has a wrong offset!");
static_assert(offsetof(WBP_IngameMenu_WorkSpace_C_Setup, CallFunc_Array_IsEmpty_ReturnValue) == 0x000128, "Member 'WBP_IngameMenu_WorkSpace_C_Setup::CallFunc_Array_IsEmpty_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_IngameMenu_WorkSpace_C_Setup, K2Node_Select_Default) == 0x000129, "Member 'WBP_IngameMenu_WorkSpace_C_Setup::K2Node_Select_Default' has a wrong offset!");
static_assert(offsetof(WBP_IngameMenu_WorkSpace_C_Setup, CallFunc_SpawnObject_ReturnValue) == 0x000130, "Member 'WBP_IngameMenu_WorkSpace_C_Setup::CallFunc_SpawnObject_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_IngameMenu_WorkSpace_C_Setup, CallFunc_AddRecipeSet_createdBlock) == 0x000138, "Member 'WBP_IngameMenu_WorkSpace_C_Setup::CallFunc_AddRecipeSet_createdBlock' has a wrong offset!");

// Function WBP_IngameMenu_WorkSpace.WBP_IngameMenu_WorkSpace_C.Update Recipe Detail
// 0x0040 (0x0040 - 0x0000)
struct WBP_IngameMenu_WorkSpace_C_Update_Recipe_Detail final
{
public:
	EPalUIConvertItemRequestStartResponse         CallFunc_CanStartProduction_ReturnValue;           // 0x0000(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_NotEqual_ByteByte_ReturnValue;            // 0x0001(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Not_PreBool_ReturnValue;                  // 0x0002(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_3[0x5];                                        // 0x0003(0x0005)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<struct FPalStaticItemIdAndNum>         CallFunc_GetRequiredMaterialInfos_RequiredMaterialInfos; // 0x0008(0x0010)(ReferenceParm)
	float                                         CallFunc_CalcWorkAmount_ReturnValue;               // 0x0018(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_WorkAmountToManMonth_ReturnValue;         // 0x001C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FText                                   CallFunc_Conv_DoubleToText_ReturnValue;            // 0x0020(0x0018)()
	double                                        CallFunc_Conv_DoubleToText_Value_ImplicitCast;     // 0x0038(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WBP_IngameMenu_WorkSpace_C_Update_Recipe_Detail) == 0x000008, "Wrong alignment on WBP_IngameMenu_WorkSpace_C_Update_Recipe_Detail");
static_assert(sizeof(WBP_IngameMenu_WorkSpace_C_Update_Recipe_Detail) == 0x000040, "Wrong size on WBP_IngameMenu_WorkSpace_C_Update_Recipe_Detail");
static_assert(offsetof(WBP_IngameMenu_WorkSpace_C_Update_Recipe_Detail, CallFunc_CanStartProduction_ReturnValue) == 0x000000, "Member 'WBP_IngameMenu_WorkSpace_C_Update_Recipe_Detail::CallFunc_CanStartProduction_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_IngameMenu_WorkSpace_C_Update_Recipe_Detail, CallFunc_NotEqual_ByteByte_ReturnValue) == 0x000001, "Member 'WBP_IngameMenu_WorkSpace_C_Update_Recipe_Detail::CallFunc_NotEqual_ByteByte_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_IngameMenu_WorkSpace_C_Update_Recipe_Detail, CallFunc_Not_PreBool_ReturnValue) == 0x000002, "Member 'WBP_IngameMenu_WorkSpace_C_Update_Recipe_Detail::CallFunc_Not_PreBool_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_IngameMenu_WorkSpace_C_Update_Recipe_Detail, CallFunc_GetRequiredMaterialInfos_RequiredMaterialInfos) == 0x000008, "Member 'WBP_IngameMenu_WorkSpace_C_Update_Recipe_Detail::CallFunc_GetRequiredMaterialInfos_RequiredMaterialInfos' has a wrong offset!");
static_assert(offsetof(WBP_IngameMenu_WorkSpace_C_Update_Recipe_Detail, CallFunc_CalcWorkAmount_ReturnValue) == 0x000018, "Member 'WBP_IngameMenu_WorkSpace_C_Update_Recipe_Detail::CallFunc_CalcWorkAmount_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_IngameMenu_WorkSpace_C_Update_Recipe_Detail, CallFunc_WorkAmountToManMonth_ReturnValue) == 0x00001C, "Member 'WBP_IngameMenu_WorkSpace_C_Update_Recipe_Detail::CallFunc_WorkAmountToManMonth_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_IngameMenu_WorkSpace_C_Update_Recipe_Detail, CallFunc_Conv_DoubleToText_ReturnValue) == 0x000020, "Member 'WBP_IngameMenu_WorkSpace_C_Update_Recipe_Detail::CallFunc_Conv_DoubleToText_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_IngameMenu_WorkSpace_C_Update_Recipe_Detail, CallFunc_Conv_DoubleToText_Value_ImplicitCast) == 0x000038, "Member 'WBP_IngameMenu_WorkSpace_C_Update_Recipe_Detail::CallFunc_Conv_DoubleToText_Value_ImplicitCast' has a wrong offset!");

// Function WBP_IngameMenu_WorkSpace.WBP_IngameMenu_WorkSpace_C.BP_GetDesiredFocusTarget
// 0x0020 (0x0020 - 0x0000)
struct WBP_IngameMenu_WorkSpace_C_BP_GetDesiredFocusTarget final
{
public:
	class UWidget*                                ReturnValue;                                       // 0x0000(0x0008)(Parm, OutParm, ZeroConstructor, ReturnParm, InstancedReference, NoDestructor, HasGetValueTypeHash)
	bool                                          Temp_bool_Variable;                                // 0x0008(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_9[0x7];                                        // 0x0009(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UWidget*                                CallFunc_GetFocusTarget_target;                    // 0x0010(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	class UWidget*                                K2Node_Select_Default;                             // 0x0018(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WBP_IngameMenu_WorkSpace_C_BP_GetDesiredFocusTarget) == 0x000008, "Wrong alignment on WBP_IngameMenu_WorkSpace_C_BP_GetDesiredFocusTarget");
static_assert(sizeof(WBP_IngameMenu_WorkSpace_C_BP_GetDesiredFocusTarget) == 0x000020, "Wrong size on WBP_IngameMenu_WorkSpace_C_BP_GetDesiredFocusTarget");
static_assert(offsetof(WBP_IngameMenu_WorkSpace_C_BP_GetDesiredFocusTarget, ReturnValue) == 0x000000, "Member 'WBP_IngameMenu_WorkSpace_C_BP_GetDesiredFocusTarget::ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_IngameMenu_WorkSpace_C_BP_GetDesiredFocusTarget, Temp_bool_Variable) == 0x000008, "Member 'WBP_IngameMenu_WorkSpace_C_BP_GetDesiredFocusTarget::Temp_bool_Variable' has a wrong offset!");
static_assert(offsetof(WBP_IngameMenu_WorkSpace_C_BP_GetDesiredFocusTarget, CallFunc_GetFocusTarget_target) == 0x000010, "Member 'WBP_IngameMenu_WorkSpace_C_BP_GetDesiredFocusTarget::CallFunc_GetFocusTarget_target' has a wrong offset!");
static_assert(offsetof(WBP_IngameMenu_WorkSpace_C_BP_GetDesiredFocusTarget, K2Node_Select_Default) == 0x000018, "Member 'WBP_IngameMenu_WorkSpace_C_BP_GetDesiredFocusTarget::K2Node_Select_Default' has a wrong offset!");

}

