#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_Arena_TopMenu

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "Pal_structs.hpp"
#include "Pal_classes.hpp"
#include "UMG_structs.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass WBP_Arena_TopMenu.WBP_Arena_TopMenu_C
// 0x0070 (0x04A0 - 0x0430)
class UWBP_Arena_TopMenu_C final : public UPalUserWidgetOverlayUI
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0430(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UWidgetAnimation*                       Anm_ButtonOut;                                     // 0x0438(0x0008)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, RepSkip, NoDestructor, HasGetValueTypeHash)
	class UWidgetAnimation*                       Anm_MenuInOut;                                     // 0x0440(0x0008)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, RepSkip, NoDestructor, HasGetValueTypeHash)
	class UWidgetAnimation*                       Anm_Out;                                           // 0x0448(0x0008)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, RepSkip, NoDestructor, HasGetValueTypeHash)
	class UWidgetAnimation*                       Anm_In;                                            // 0x0450(0x0008)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, RepSkip, NoDestructor, HasGetValueTypeHash)
	class UCanvasPanel*                           Canvas_MenuGuideText;                              // 0x0458(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UCanvasPanel*                           Canvas_Wait;                                       // 0x0460(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UBP_PalTextBlock_C*                     Text_MenuGuide;                                    // 0x0468(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWBP_Arena_PlayerRank_C*                WBP_Arena_PlayerRank;                              // 0x0470(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWBP_Arena_TopMenuButton_C*             WBP_Arena_TopMenuButton_PvP;                       // 0x0478(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWBP_Arena_TopMenuButton_C*             WBP_Arena_TopMenuButton_Solo;                      // 0x0480(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWBP_Arena_TopMenuButton_C*             WBP_Arena_TopMenuButton_Spectate;                  // 0x0488(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class APalArenaEntrance*                      Entrance;                                          // 0x0490(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnTemplate, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)
	int32                                         LastFocusIndex;                                    // 0x0498(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          MenuOut;                                           // 0x049C(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	EPalArenaMenuActionType                       LastAction;                                        // 0x049D(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void AnmEvent_In();
	void AnmEvent_MenuIn();
	void AnmEvent_MenuOut();
	void AnmEvent_Out();
	void BndEvt__WBP_Arena_TopMenu_WBP_Arena_TopMenuButton_PvP_K2Node_ComponentBoundEvent_1_OnArenaButtonClicked__DelegateSignature();
	void BndEvt__WBP_Arena_TopMenu_WBP_Arena_TopMenuButton_PvP_K2Node_ComponentBoundEvent_5_OnArenaButtonHovered__DelegateSignature();
	void BndEvt__WBP_Arena_TopMenu_WBP_Arena_TopMenuButton_PvP_K2Node_ComponentBoundEvent_6_OnArenaButtonUnhovered__DelegateSignature();
	void BndEvt__WBP_Arena_TopMenu_WBP_Arena_TopMenuButton_Solo_K2Node_ComponentBoundEvent_0_OnArenaButtonClicked__DelegateSignature();
	void BndEvt__WBP_Arena_TopMenu_WBP_Arena_TopMenuButton_Solo_K2Node_ComponentBoundEvent_3_OnArenaButtonHovered__DelegateSignature();
	void BndEvt__WBP_Arena_TopMenu_WBP_Arena_TopMenuButton_Solo_K2Node_ComponentBoundEvent_4_OnArenaButtonUnhovered__DelegateSignature();
	void BndEvt__WBP_Arena_TopMenu_WBP_Arena_TopMenuButton_Spectate_K2Node_ComponentBoundEvent_2_OnArenaButtonClicked__DelegateSignature();
	void BndEvt__WBP_Arena_TopMenu_WBP_Arena_TopMenuButton_Spectate_K2Node_ComponentBoundEvent_7_OnArenaButtonHovered__DelegateSignature();
	void BndEvt__WBP_Arena_TopMenu_WBP_Arena_TopMenuButton_Spectate_K2Node_ComponentBoundEvent_8_OnArenaButtonUnhovered__DelegateSignature();
	void CancelAction();
	void ChangeInfo(int32 Index_0, bool IsEnable);
	void Construct();
	void EmptyEvent(bool bResult);
	void ExecuteUbergraph_WBP_Arena_TopMenu(int32 EntryPoint);
	void Finished_55E66A6745B17F175A5608B05FCBDDC7();
	void OnInitialized();
	void OnSetup();
	void Setup();
	void Top_Menu_Action(EPalArenaMenuActionType ActionType);

	class UWidget* BP_GetDesiredFocusTarget() const;

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"WBP_Arena_TopMenu_C">();
	}
	static class UWBP_Arena_TopMenu_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_Arena_TopMenu_C>();
	}
};
static_assert(alignof(UWBP_Arena_TopMenu_C) == 0x000008, "Wrong alignment on UWBP_Arena_TopMenu_C");
static_assert(sizeof(UWBP_Arena_TopMenu_C) == 0x0004A0, "Wrong size on UWBP_Arena_TopMenu_C");
static_assert(offsetof(UWBP_Arena_TopMenu_C, UberGraphFrame) == 0x000430, "Member 'UWBP_Arena_TopMenu_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(UWBP_Arena_TopMenu_C, Anm_ButtonOut) == 0x000438, "Member 'UWBP_Arena_TopMenu_C::Anm_ButtonOut' has a wrong offset!");
static_assert(offsetof(UWBP_Arena_TopMenu_C, Anm_MenuInOut) == 0x000440, "Member 'UWBP_Arena_TopMenu_C::Anm_MenuInOut' has a wrong offset!");
static_assert(offsetof(UWBP_Arena_TopMenu_C, Anm_Out) == 0x000448, "Member 'UWBP_Arena_TopMenu_C::Anm_Out' has a wrong offset!");
static_assert(offsetof(UWBP_Arena_TopMenu_C, Anm_In) == 0x000450, "Member 'UWBP_Arena_TopMenu_C::Anm_In' has a wrong offset!");
static_assert(offsetof(UWBP_Arena_TopMenu_C, Canvas_MenuGuideText) == 0x000458, "Member 'UWBP_Arena_TopMenu_C::Canvas_MenuGuideText' has a wrong offset!");
static_assert(offsetof(UWBP_Arena_TopMenu_C, Canvas_Wait) == 0x000460, "Member 'UWBP_Arena_TopMenu_C::Canvas_Wait' has a wrong offset!");
static_assert(offsetof(UWBP_Arena_TopMenu_C, Text_MenuGuide) == 0x000468, "Member 'UWBP_Arena_TopMenu_C::Text_MenuGuide' has a wrong offset!");
static_assert(offsetof(UWBP_Arena_TopMenu_C, WBP_Arena_PlayerRank) == 0x000470, "Member 'UWBP_Arena_TopMenu_C::WBP_Arena_PlayerRank' has a wrong offset!");
static_assert(offsetof(UWBP_Arena_TopMenu_C, WBP_Arena_TopMenuButton_PvP) == 0x000478, "Member 'UWBP_Arena_TopMenu_C::WBP_Arena_TopMenuButton_PvP' has a wrong offset!");
static_assert(offsetof(UWBP_Arena_TopMenu_C, WBP_Arena_TopMenuButton_Solo) == 0x000480, "Member 'UWBP_Arena_TopMenu_C::WBP_Arena_TopMenuButton_Solo' has a wrong offset!");
static_assert(offsetof(UWBP_Arena_TopMenu_C, WBP_Arena_TopMenuButton_Spectate) == 0x000488, "Member 'UWBP_Arena_TopMenu_C::WBP_Arena_TopMenuButton_Spectate' has a wrong offset!");
static_assert(offsetof(UWBP_Arena_TopMenu_C, Entrance) == 0x000490, "Member 'UWBP_Arena_TopMenu_C::Entrance' has a wrong offset!");
static_assert(offsetof(UWBP_Arena_TopMenu_C, LastFocusIndex) == 0x000498, "Member 'UWBP_Arena_TopMenu_C::LastFocusIndex' has a wrong offset!");
static_assert(offsetof(UWBP_Arena_TopMenu_C, MenuOut) == 0x00049C, "Member 'UWBP_Arena_TopMenu_C::MenuOut' has a wrong offset!");
static_assert(offsetof(UWBP_Arena_TopMenu_C, LastAction) == 0x00049D, "Member 'UWBP_Arena_TopMenu_C::LastAction' has a wrong offset!");

}

