#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_Ingame_Message

#include "Basic.hpp"


namespace SDK::Params
{

// Function WBP_Ingame_Message.WBP_Ingame_Message_C.ExecuteUbergraph_WBP_Ingame_Message
// 0x0028 (0x0028 - 0x0000)
struct WBP_Ingame_Message_C_ExecuteUbergraph_WBP_Ingame_Message final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4[0x4];                                        // 0x0004(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UUMGSequencePlayer*                     CallFunc_PlayAnimation_ReturnValue;                // 0x0008(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsAnimationPlaying_ReturnValue;           // 0x0010(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_11[0x7];                                       // 0x0011(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UUMGSequencePlayer*                     CallFunc_PlayAnimation_ReturnValue_1;              // 0x0018(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsAnimationPlaying_ReturnValue_1;         // 0x0020(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WBP_Ingame_Message_C_ExecuteUbergraph_WBP_Ingame_Message) == 0x000008, "Wrong alignment on WBP_Ingame_Message_C_ExecuteUbergraph_WBP_Ingame_Message");
static_assert(sizeof(WBP_Ingame_Message_C_ExecuteUbergraph_WBP_Ingame_Message) == 0x000028, "Wrong size on WBP_Ingame_Message_C_ExecuteUbergraph_WBP_Ingame_Message");
static_assert(offsetof(WBP_Ingame_Message_C_ExecuteUbergraph_WBP_Ingame_Message, EntryPoint) == 0x000000, "Member 'WBP_Ingame_Message_C_ExecuteUbergraph_WBP_Ingame_Message::EntryPoint' has a wrong offset!");
static_assert(offsetof(WBP_Ingame_Message_C_ExecuteUbergraph_WBP_Ingame_Message, CallFunc_PlayAnimation_ReturnValue) == 0x000008, "Member 'WBP_Ingame_Message_C_ExecuteUbergraph_WBP_Ingame_Message::CallFunc_PlayAnimation_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_Ingame_Message_C_ExecuteUbergraph_WBP_Ingame_Message, CallFunc_IsAnimationPlaying_ReturnValue) == 0x000010, "Member 'WBP_Ingame_Message_C_ExecuteUbergraph_WBP_Ingame_Message::CallFunc_IsAnimationPlaying_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_Ingame_Message_C_ExecuteUbergraph_WBP_Ingame_Message, CallFunc_PlayAnimation_ReturnValue_1) == 0x000018, "Member 'WBP_Ingame_Message_C_ExecuteUbergraph_WBP_Ingame_Message::CallFunc_PlayAnimation_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(WBP_Ingame_Message_C_ExecuteUbergraph_WBP_Ingame_Message, CallFunc_IsAnimationPlaying_ReturnValue_1) == 0x000020, "Member 'WBP_Ingame_Message_C_ExecuteUbergraph_WBP_Ingame_Message::CallFunc_IsAnimationPlaying_ReturnValue_1' has a wrong offset!");

// Function WBP_Ingame_Message.WBP_Ingame_Message_C.SetMessageText
// 0x0020 (0x0020 - 0x0000)
struct WBP_Ingame_Message_C_SetMessageText final
{
public:
	class FName                                   TextId;                                            // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FText                                   CallFunc_GetLocalizedText_ReturnValue;             // 0x0008(0x0018)()
};
static_assert(alignof(WBP_Ingame_Message_C_SetMessageText) == 0x000008, "Wrong alignment on WBP_Ingame_Message_C_SetMessageText");
static_assert(sizeof(WBP_Ingame_Message_C_SetMessageText) == 0x000020, "Wrong size on WBP_Ingame_Message_C_SetMessageText");
static_assert(offsetof(WBP_Ingame_Message_C_SetMessageText, TextId) == 0x000000, "Member 'WBP_Ingame_Message_C_SetMessageText::TextId' has a wrong offset!");
static_assert(offsetof(WBP_Ingame_Message_C_SetMessageText, CallFunc_GetLocalizedText_ReturnValue) == 0x000008, "Member 'WBP_Ingame_Message_C_SetMessageText::CallFunc_GetLocalizedText_ReturnValue' has a wrong offset!");

}

