#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_Ingame_Chat

#include "Basic.hpp"

#include "SlateCore_structs.hpp"
#include "Pal_structs.hpp"
#include "UMG_structs.hpp"
#include "CommonInput_structs.hpp"
#include "CoreUObject_structs.hpp"
#include "Engine_structs.hpp"
#include "InputCore_structs.hpp"


namespace SDK::Params
{

// Function WBP_Ingame_Chat.WBP_Ingame_Chat_C.AddChatMessage
// 0x02C0 (0x02C0 - 0x0000)
struct WBP_Ingame_Chat_C_AddChatMessage final
{
public:
	struct FPalChatMessage                        Message;                                           // 0x0000(0x0048)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
	struct FLinearColor                           MessageColor;                                      // 0x0048(0x0010)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UPalGameInstance*                       CallFunc_GetPalGameInstance_ReturnValue;           // 0x0058(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class UPalGameInstance*                       CallFunc_GetPalGameInstance_ReturnValue_1;         // 0x0060(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_CanChat_Result;                           // 0x0068(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_69[0x7];                                       // 0x0069(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class FText                                   CallFunc_Conv_StringToText_ReturnValue;            // 0x0070(0x0018)()
	bool                                          CallFunc_IsDenyCommunicationByPlayerUId_bOutDeny;  // 0x0088(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsDenyCommunicationByPlayerUId_ReturnValue; // 0x0089(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_8A[0x6];                                       // 0x008A(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	struct FFormatArgumentData                    K2Node_MakeStruct_FormatArgumentData;              // 0x0090(0x0050)(HasGetValueTypeHash)
	bool                                          CallFunc_IsBlockPlayerByPlayerUId_bOutBlock;       // 0x00E0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsBlockPlayerByPlayerUId_ReturnValue;     // 0x00E1(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsMutePlayerByPlayerUId_bOutMute;         // 0x00E2(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsMutePlayerByPlayerUId_ReturnValue;      // 0x00E3(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_E4[0x4];                                       // 0x00E4(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class FString                                 CallFunc_WithOnlineId_OutName;                     // 0x00E8(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	bool                                          CallFunc_BooleanOR_ReturnValue;                    // 0x00F8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_F9[0x7];                                       // 0x00F9(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class FText                                   CallFunc_Conv_StringToText_ReturnValue_1;          // 0x0100(0x0018)()
	bool                                          CallFunc_BooleanOR_ReturnValue_1;                  // 0x0118(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_119[0x7];                                      // 0x0119(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	struct FFormatArgumentData                    K2Node_MakeStruct_FormatArgumentData_1;            // 0x0120(0x0050)(HasGetValueTypeHash)
	TArray<struct FFormatArgumentData>            K2Node_MakeArray_Array;                            // 0x0170(0x0010)(ReferenceParm)
	class FString                                 CallFunc_WithOnlineId_OutName_1;                   // 0x0180(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	class FText                                   CallFunc_Format_ReturnValue;                       // 0x0190(0x0018)()
	class FText                                   CallFunc_Conv_StringToText_ReturnValue_2;          // 0x01A8(0x0018)()
	bool                                          CallFunc_EqualEqual_StrStr_ReturnValue;            // 0x01C0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_1C1[0x7];                                      // 0x01C1(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	struct FFormatArgumentData                    K2Node_MakeStruct_FormatArgumentData_2;            // 0x01C8(0x0050)(HasGetValueTypeHash)
	TArray<struct FFormatArgumentData>            K2Node_MakeArray_Array_1;                          // 0x0218(0x0010)(ReferenceParm)
	bool                                          K2Node_SwitchEnum_CmpSuccess;                      // 0x0228(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_229[0x7];                                      // 0x0229(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class FText                                   CallFunc_Format_ReturnValue_1;                     // 0x0230(0x0018)()
	struct FLinearColor                           K2Node_MakeStruct_LinearColor;                     // 0x0248(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FSlateColor                            K2Node_MakeStruct_SlateColor;                      // 0x0258(0x0014)()
	struct FLinearColor                           K2Node_MakeStruct_LinearColor_1;                   // 0x026C(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FLinearColor                           K2Node_MakeStruct_LinearColor_2;                   // 0x027C(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_28C[0x4];                                      // 0x028C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class APlayerController*                      CallFunc_GetLocalPlayerController_ReturnValue;     // 0x0290(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class UScrollBox*                             CallFunc_GetScrollBox_ScrollBox;                   // 0x0298(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	class UWBP_Ingame_ChatListContent_C*          CallFunc_Create_ReturnValue;                       // 0x02A0(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	class UWidget*                                CallFunc_GetChildAt_ReturnValue;                   // 0x02A8(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	class UPanelSlot*                             CallFunc_AddChild_ReturnValue;                     // 0x02B0(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_GetChildrenCount_ReturnValue;             // 0x02B8(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Greater_IntInt_ReturnValue;               // 0x02BC(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WBP_Ingame_Chat_C_AddChatMessage) == 0x000008, "Wrong alignment on WBP_Ingame_Chat_C_AddChatMessage");
static_assert(sizeof(WBP_Ingame_Chat_C_AddChatMessage) == 0x0002C0, "Wrong size on WBP_Ingame_Chat_C_AddChatMessage");
static_assert(offsetof(WBP_Ingame_Chat_C_AddChatMessage, Message) == 0x000000, "Member 'WBP_Ingame_Chat_C_AddChatMessage::Message' has a wrong offset!");
static_assert(offsetof(WBP_Ingame_Chat_C_AddChatMessage, MessageColor) == 0x000048, "Member 'WBP_Ingame_Chat_C_AddChatMessage::MessageColor' has a wrong offset!");
static_assert(offsetof(WBP_Ingame_Chat_C_AddChatMessage, CallFunc_GetPalGameInstance_ReturnValue) == 0x000058, "Member 'WBP_Ingame_Chat_C_AddChatMessage::CallFunc_GetPalGameInstance_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_Ingame_Chat_C_AddChatMessage, CallFunc_GetPalGameInstance_ReturnValue_1) == 0x000060, "Member 'WBP_Ingame_Chat_C_AddChatMessage::CallFunc_GetPalGameInstance_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(WBP_Ingame_Chat_C_AddChatMessage, CallFunc_CanChat_Result) == 0x000068, "Member 'WBP_Ingame_Chat_C_AddChatMessage::CallFunc_CanChat_Result' has a wrong offset!");
static_assert(offsetof(WBP_Ingame_Chat_C_AddChatMessage, CallFunc_Conv_StringToText_ReturnValue) == 0x000070, "Member 'WBP_Ingame_Chat_C_AddChatMessage::CallFunc_Conv_StringToText_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_Ingame_Chat_C_AddChatMessage, CallFunc_IsDenyCommunicationByPlayerUId_bOutDeny) == 0x000088, "Member 'WBP_Ingame_Chat_C_AddChatMessage::CallFunc_IsDenyCommunicationByPlayerUId_bOutDeny' has a wrong offset!");
static_assert(offsetof(WBP_Ingame_Chat_C_AddChatMessage, CallFunc_IsDenyCommunicationByPlayerUId_ReturnValue) == 0x000089, "Member 'WBP_Ingame_Chat_C_AddChatMessage::CallFunc_IsDenyCommunicationByPlayerUId_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_Ingame_Chat_C_AddChatMessage, K2Node_MakeStruct_FormatArgumentData) == 0x000090, "Member 'WBP_Ingame_Chat_C_AddChatMessage::K2Node_MakeStruct_FormatArgumentData' has a wrong offset!");
static_assert(offsetof(WBP_Ingame_Chat_C_AddChatMessage, CallFunc_IsBlockPlayerByPlayerUId_bOutBlock) == 0x0000E0, "Member 'WBP_Ingame_Chat_C_AddChatMessage::CallFunc_IsBlockPlayerByPlayerUId_bOutBlock' has a wrong offset!");
static_assert(offsetof(WBP_Ingame_Chat_C_AddChatMessage, CallFunc_IsBlockPlayerByPlayerUId_ReturnValue) == 0x0000E1, "Member 'WBP_Ingame_Chat_C_AddChatMessage::CallFunc_IsBlockPlayerByPlayerUId_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_Ingame_Chat_C_AddChatMessage, CallFunc_IsMutePlayerByPlayerUId_bOutMute) == 0x0000E2, "Member 'WBP_Ingame_Chat_C_AddChatMessage::CallFunc_IsMutePlayerByPlayerUId_bOutMute' has a wrong offset!");
static_assert(offsetof(WBP_Ingame_Chat_C_AddChatMessage, CallFunc_IsMutePlayerByPlayerUId_ReturnValue) == 0x0000E3, "Member 'WBP_Ingame_Chat_C_AddChatMessage::CallFunc_IsMutePlayerByPlayerUId_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_Ingame_Chat_C_AddChatMessage, CallFunc_WithOnlineId_OutName) == 0x0000E8, "Member 'WBP_Ingame_Chat_C_AddChatMessage::CallFunc_WithOnlineId_OutName' has a wrong offset!");
static_assert(offsetof(WBP_Ingame_Chat_C_AddChatMessage, CallFunc_BooleanOR_ReturnValue) == 0x0000F8, "Member 'WBP_Ingame_Chat_C_AddChatMessage::CallFunc_BooleanOR_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_Ingame_Chat_C_AddChatMessage, CallFunc_Conv_StringToText_ReturnValue_1) == 0x000100, "Member 'WBP_Ingame_Chat_C_AddChatMessage::CallFunc_Conv_StringToText_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(WBP_Ingame_Chat_C_AddChatMessage, CallFunc_BooleanOR_ReturnValue_1) == 0x000118, "Member 'WBP_Ingame_Chat_C_AddChatMessage::CallFunc_BooleanOR_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(WBP_Ingame_Chat_C_AddChatMessage, K2Node_MakeStruct_FormatArgumentData_1) == 0x000120, "Member 'WBP_Ingame_Chat_C_AddChatMessage::K2Node_MakeStruct_FormatArgumentData_1' has a wrong offset!");
static_assert(offsetof(WBP_Ingame_Chat_C_AddChatMessage, K2Node_MakeArray_Array) == 0x000170, "Member 'WBP_Ingame_Chat_C_AddChatMessage::K2Node_MakeArray_Array' has a wrong offset!");
static_assert(offsetof(WBP_Ingame_Chat_C_AddChatMessage, CallFunc_WithOnlineId_OutName_1) == 0x000180, "Member 'WBP_Ingame_Chat_C_AddChatMessage::CallFunc_WithOnlineId_OutName_1' has a wrong offset!");
static_assert(offsetof(WBP_Ingame_Chat_C_AddChatMessage, CallFunc_Format_ReturnValue) == 0x000190, "Member 'WBP_Ingame_Chat_C_AddChatMessage::CallFunc_Format_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_Ingame_Chat_C_AddChatMessage, CallFunc_Conv_StringToText_ReturnValue_2) == 0x0001A8, "Member 'WBP_Ingame_Chat_C_AddChatMessage::CallFunc_Conv_StringToText_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(WBP_Ingame_Chat_C_AddChatMessage, CallFunc_EqualEqual_StrStr_ReturnValue) == 0x0001C0, "Member 'WBP_Ingame_Chat_C_AddChatMessage::CallFunc_EqualEqual_StrStr_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_Ingame_Chat_C_AddChatMessage, K2Node_MakeStruct_FormatArgumentData_2) == 0x0001C8, "Member 'WBP_Ingame_Chat_C_AddChatMessage::K2Node_MakeStruct_FormatArgumentData_2' has a wrong offset!");
static_assert(offsetof(WBP_Ingame_Chat_C_AddChatMessage, K2Node_MakeArray_Array_1) == 0x000218, "Member 'WBP_Ingame_Chat_C_AddChatMessage::K2Node_MakeArray_Array_1' has a wrong offset!");
static_assert(offsetof(WBP_Ingame_Chat_C_AddChatMessage, K2Node_SwitchEnum_CmpSuccess) == 0x000228, "Member 'WBP_Ingame_Chat_C_AddChatMessage::K2Node_SwitchEnum_CmpSuccess' has a wrong offset!");
static_assert(offsetof(WBP_Ingame_Chat_C_AddChatMessage, CallFunc_Format_ReturnValue_1) == 0x000230, "Member 'WBP_Ingame_Chat_C_AddChatMessage::CallFunc_Format_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(WBP_Ingame_Chat_C_AddChatMessage, K2Node_MakeStruct_LinearColor) == 0x000248, "Member 'WBP_Ingame_Chat_C_AddChatMessage::K2Node_MakeStruct_LinearColor' has a wrong offset!");
static_assert(offsetof(WBP_Ingame_Chat_C_AddChatMessage, K2Node_MakeStruct_SlateColor) == 0x000258, "Member 'WBP_Ingame_Chat_C_AddChatMessage::K2Node_MakeStruct_SlateColor' has a wrong offset!");
static_assert(offsetof(WBP_Ingame_Chat_C_AddChatMessage, K2Node_MakeStruct_LinearColor_1) == 0x00026C, "Member 'WBP_Ingame_Chat_C_AddChatMessage::K2Node_MakeStruct_LinearColor_1' has a wrong offset!");
static_assert(offsetof(WBP_Ingame_Chat_C_AddChatMessage, K2Node_MakeStruct_LinearColor_2) == 0x00027C, "Member 'WBP_Ingame_Chat_C_AddChatMessage::K2Node_MakeStruct_LinearColor_2' has a wrong offset!");
static_assert(offsetof(WBP_Ingame_Chat_C_AddChatMessage, CallFunc_GetLocalPlayerController_ReturnValue) == 0x000290, "Member 'WBP_Ingame_Chat_C_AddChatMessage::CallFunc_GetLocalPlayerController_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_Ingame_Chat_C_AddChatMessage, CallFunc_GetScrollBox_ScrollBox) == 0x000298, "Member 'WBP_Ingame_Chat_C_AddChatMessage::CallFunc_GetScrollBox_ScrollBox' has a wrong offset!");
static_assert(offsetof(WBP_Ingame_Chat_C_AddChatMessage, CallFunc_Create_ReturnValue) == 0x0002A0, "Member 'WBP_Ingame_Chat_C_AddChatMessage::CallFunc_Create_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_Ingame_Chat_C_AddChatMessage, CallFunc_GetChildAt_ReturnValue) == 0x0002A8, "Member 'WBP_Ingame_Chat_C_AddChatMessage::CallFunc_GetChildAt_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_Ingame_Chat_C_AddChatMessage, CallFunc_AddChild_ReturnValue) == 0x0002B0, "Member 'WBP_Ingame_Chat_C_AddChatMessage::CallFunc_AddChild_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_Ingame_Chat_C_AddChatMessage, CallFunc_GetChildrenCount_ReturnValue) == 0x0002B8, "Member 'WBP_Ingame_Chat_C_AddChatMessage::CallFunc_GetChildrenCount_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_Ingame_Chat_C_AddChatMessage, CallFunc_Greater_IntInt_ReturnValue) == 0x0002BC, "Member 'WBP_Ingame_Chat_C_AddChatMessage::CallFunc_Greater_IntInt_ReturnValue' has a wrong offset!");

// Function WBP_Ingame_Chat.WBP_Ingame_Chat_C.BndEvt__WBP_Ingame_Chat_PalMultiLineEditableTextBox_220_K2Node_ComponentBoundEvent_5_OnMultiLineEditableTextBoxCommittedEvent__DelegateSignature
// 0x0020 (0x0020 - 0x0000)
struct WBP_Ingame_Chat_C_BndEvt__WBP_Ingame_Chat_PalMultiLineEditableTextBox_220_K2Node_ComponentBoundEvent_5_OnMultiLineEditableTextBoxCommittedEvent__DelegateSignature final
{
public:
	class FText                                   Text;                                              // 0x0000(0x0018)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
	ETextCommit                                   CommitMethod;                                      // 0x0018(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WBP_Ingame_Chat_C_BndEvt__WBP_Ingame_Chat_PalMultiLineEditableTextBox_220_K2Node_ComponentBoundEvent_5_OnMultiLineEditableTextBoxCommittedEvent__DelegateSignature) == 0x000008, "Wrong alignment on WBP_Ingame_Chat_C_BndEvt__WBP_Ingame_Chat_PalMultiLineEditableTextBox_220_K2Node_ComponentBoundEvent_5_OnMultiLineEditableTextBoxCommittedEvent__DelegateSignature");
static_assert(sizeof(WBP_Ingame_Chat_C_BndEvt__WBP_Ingame_Chat_PalMultiLineEditableTextBox_220_K2Node_ComponentBoundEvent_5_OnMultiLineEditableTextBoxCommittedEvent__DelegateSignature) == 0x000020, "Wrong size on WBP_Ingame_Chat_C_BndEvt__WBP_Ingame_Chat_PalMultiLineEditableTextBox_220_K2Node_ComponentBoundEvent_5_OnMultiLineEditableTextBoxCommittedEvent__DelegateSignature");
static_assert(offsetof(WBP_Ingame_Chat_C_BndEvt__WBP_Ingame_Chat_PalMultiLineEditableTextBox_220_K2Node_ComponentBoundEvent_5_OnMultiLineEditableTextBoxCommittedEvent__DelegateSignature, Text) == 0x000000, "Member 'WBP_Ingame_Chat_C_BndEvt__WBP_Ingame_Chat_PalMultiLineEditableTextBox_220_K2Node_ComponentBoundEvent_5_OnMultiLineEditableTextBoxCommittedEvent__DelegateSignature::Text' has a wrong offset!");
static_assert(offsetof(WBP_Ingame_Chat_C_BndEvt__WBP_Ingame_Chat_PalMultiLineEditableTextBox_220_K2Node_ComponentBoundEvent_5_OnMultiLineEditableTextBoxCommittedEvent__DelegateSignature, CommitMethod) == 0x000018, "Member 'WBP_Ingame_Chat_C_BndEvt__WBP_Ingame_Chat_PalMultiLineEditableTextBox_220_K2Node_ComponentBoundEvent_5_OnMultiLineEditableTextBoxCommittedEvent__DelegateSignature::CommitMethod' has a wrong offset!");

// Function WBP_Ingame_Chat.WBP_Ingame_Chat_C.CanChat
// 0x0038 (0x0038 - 0x0000)
struct WBP_Ingame_Chat_C_CanChat final
{
public:
	bool                                          Result;                                            // 0x0000(0x0001)(Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_1[0x7];                                        // 0x0001(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UPalGameInstance*                       CallFunc_GetPalGameInstance_ReturnValue;           // 0x0008(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsChatBlocked_ReturnValue;                // 0x0010(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsUGCFilter_ReturnValue;                  // 0x0011(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsChatDisabled_ReturnValue;               // 0x0012(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_BooleanOR_ReturnValue;                    // 0x0013(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_BooleanOR_ReturnValue_1;                  // 0x0014(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_15[0x3];                                       // 0x0015(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	class UPalOptionSubsystem*                    CallFunc_GetOptionSubsystem_ReturnValue;           // 0x0018(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	struct FPalOptionKeyboardSettings             CallFunc_GetKeyboardSettings_ReturnValue;          // 0x0020(0x0014)(ConstParm, NoDestructor)
};
static_assert(alignof(WBP_Ingame_Chat_C_CanChat) == 0x000008, "Wrong alignment on WBP_Ingame_Chat_C_CanChat");
static_assert(sizeof(WBP_Ingame_Chat_C_CanChat) == 0x000038, "Wrong size on WBP_Ingame_Chat_C_CanChat");
static_assert(offsetof(WBP_Ingame_Chat_C_CanChat, Result) == 0x000000, "Member 'WBP_Ingame_Chat_C_CanChat::Result' has a wrong offset!");
static_assert(offsetof(WBP_Ingame_Chat_C_CanChat, CallFunc_GetPalGameInstance_ReturnValue) == 0x000008, "Member 'WBP_Ingame_Chat_C_CanChat::CallFunc_GetPalGameInstance_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_Ingame_Chat_C_CanChat, CallFunc_IsChatBlocked_ReturnValue) == 0x000010, "Member 'WBP_Ingame_Chat_C_CanChat::CallFunc_IsChatBlocked_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_Ingame_Chat_C_CanChat, CallFunc_IsUGCFilter_ReturnValue) == 0x000011, "Member 'WBP_Ingame_Chat_C_CanChat::CallFunc_IsUGCFilter_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_Ingame_Chat_C_CanChat, CallFunc_IsChatDisabled_ReturnValue) == 0x000012, "Member 'WBP_Ingame_Chat_C_CanChat::CallFunc_IsChatDisabled_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_Ingame_Chat_C_CanChat, CallFunc_BooleanOR_ReturnValue) == 0x000013, "Member 'WBP_Ingame_Chat_C_CanChat::CallFunc_BooleanOR_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_Ingame_Chat_C_CanChat, CallFunc_BooleanOR_ReturnValue_1) == 0x000014, "Member 'WBP_Ingame_Chat_C_CanChat::CallFunc_BooleanOR_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(WBP_Ingame_Chat_C_CanChat, CallFunc_GetOptionSubsystem_ReturnValue) == 0x000018, "Member 'WBP_Ingame_Chat_C_CanChat::CallFunc_GetOptionSubsystem_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_Ingame_Chat_C_CanChat, CallFunc_GetKeyboardSettings_ReturnValue) == 0x000020, "Member 'WBP_Ingame_Chat_C_CanChat::CallFunc_GetKeyboardSettings_ReturnValue' has a wrong offset!");

// Function WBP_Ingame_Chat.WBP_Ingame_Chat_C.ChangeCategory
// 0x00F8 (0x00F8 - 0x0000)
struct WBP_Ingame_Chat_C_ChangeCategory final
{
public:
	struct FLinearColor                           NewLocalVar;                                       // 0x0000(0x0010)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FLinearColor                           K2Node_MakeStruct_LinearColor;                     // 0x0010(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FSlateColor                            K2Node_MakeStruct_SlateColor;                      // 0x0020(0x0014)()
	struct FLinearColor                           K2Node_MakeStruct_LinearColor_1;                   // 0x0034(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FLinearColor                           K2Node_MakeStruct_LinearColor_2;                   // 0x0044(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_SwitchEnum_CmpSuccess;                      // 0x0054(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_55[0x3];                                       // 0x0055(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	class FString                                 CallFunc_GetEnumeratorUserFriendlyName_ReturnValue; // 0x0058(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	class FText                                   CallFunc_Conv_StringToText_ReturnValue;            // 0x0068(0x0018)()
	struct FFormatArgumentData                    K2Node_MakeStruct_FormatArgumentData;              // 0x0080(0x0050)(HasGetValueTypeHash)
	TArray<struct FFormatArgumentData>            K2Node_MakeArray_Array;                            // 0x00D0(0x0010)(ReferenceParm)
	class FText                                   CallFunc_Format_ReturnValue;                       // 0x00E0(0x0018)()
};
static_assert(alignof(WBP_Ingame_Chat_C_ChangeCategory) == 0x000008, "Wrong alignment on WBP_Ingame_Chat_C_ChangeCategory");
static_assert(sizeof(WBP_Ingame_Chat_C_ChangeCategory) == 0x0000F8, "Wrong size on WBP_Ingame_Chat_C_ChangeCategory");
static_assert(offsetof(WBP_Ingame_Chat_C_ChangeCategory, NewLocalVar) == 0x000000, "Member 'WBP_Ingame_Chat_C_ChangeCategory::NewLocalVar' has a wrong offset!");
static_assert(offsetof(WBP_Ingame_Chat_C_ChangeCategory, K2Node_MakeStruct_LinearColor) == 0x000010, "Member 'WBP_Ingame_Chat_C_ChangeCategory::K2Node_MakeStruct_LinearColor' has a wrong offset!");
static_assert(offsetof(WBP_Ingame_Chat_C_ChangeCategory, K2Node_MakeStruct_SlateColor) == 0x000020, "Member 'WBP_Ingame_Chat_C_ChangeCategory::K2Node_MakeStruct_SlateColor' has a wrong offset!");
static_assert(offsetof(WBP_Ingame_Chat_C_ChangeCategory, K2Node_MakeStruct_LinearColor_1) == 0x000034, "Member 'WBP_Ingame_Chat_C_ChangeCategory::K2Node_MakeStruct_LinearColor_1' has a wrong offset!");
static_assert(offsetof(WBP_Ingame_Chat_C_ChangeCategory, K2Node_MakeStruct_LinearColor_2) == 0x000044, "Member 'WBP_Ingame_Chat_C_ChangeCategory::K2Node_MakeStruct_LinearColor_2' has a wrong offset!");
static_assert(offsetof(WBP_Ingame_Chat_C_ChangeCategory, K2Node_SwitchEnum_CmpSuccess) == 0x000054, "Member 'WBP_Ingame_Chat_C_ChangeCategory::K2Node_SwitchEnum_CmpSuccess' has a wrong offset!");
static_assert(offsetof(WBP_Ingame_Chat_C_ChangeCategory, CallFunc_GetEnumeratorUserFriendlyName_ReturnValue) == 0x000058, "Member 'WBP_Ingame_Chat_C_ChangeCategory::CallFunc_GetEnumeratorUserFriendlyName_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_Ingame_Chat_C_ChangeCategory, CallFunc_Conv_StringToText_ReturnValue) == 0x000068, "Member 'WBP_Ingame_Chat_C_ChangeCategory::CallFunc_Conv_StringToText_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_Ingame_Chat_C_ChangeCategory, K2Node_MakeStruct_FormatArgumentData) == 0x000080, "Member 'WBP_Ingame_Chat_C_ChangeCategory::K2Node_MakeStruct_FormatArgumentData' has a wrong offset!");
static_assert(offsetof(WBP_Ingame_Chat_C_ChangeCategory, K2Node_MakeArray_Array) == 0x0000D0, "Member 'WBP_Ingame_Chat_C_ChangeCategory::K2Node_MakeArray_Array' has a wrong offset!");
static_assert(offsetof(WBP_Ingame_Chat_C_ChangeCategory, CallFunc_Format_ReturnValue) == 0x0000E0, "Member 'WBP_Ingame_Chat_C_ChangeCategory::CallFunc_Format_ReturnValue' has a wrong offset!");

// Function WBP_Ingame_Chat.WBP_Ingame_Chat_C.ExecuteUbergraph_WBP_Ingame_Chat
// 0x0130 (0x0130 - 0x0000)
struct WBP_Ingame_Chat_C_ExecuteUbergraph_WBP_Ingame_Chat final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TDelegate<void(const struct FPalChatMessage& Message)> K2Node_CreateDelegate_OutputDelegate;     // 0x0004(0x0010)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	TDelegate<void()>                             K2Node_CreateDelegate_OutputDelegate_1;            // 0x0014(0x0010)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_CanChat_Result;                           // 0x0024(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_CanChat_Result_1;                         // 0x0025(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_CanChat_Result_2;                         // 0x0026(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_27[0x1];                                       // 0x0027(0x0001)(Fixing Size After Last Property [ Dumper-7 ])
	class FText                                   CallFunc_GetLocalizedTextFromHandle_Text;          // 0x0028(0x0018)()
	class UPalOptionSubsystem*                    CallFunc_GetOptionSubsystem_ReturnValue;           // 0x0040(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class FText                                   K2Node_ComponentBoundEvent_Text;                   // 0x0048(0x0018)(ConstParm)
	ETextCommit                                   K2Node_ComponentBoundEvent_CommitMethod;           // 0x0060(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_61[0x3];                                       // 0x0061(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	struct FPalOptionUISettings                   CallFunc_GetUISettings_ReturnValue;                // 0x0064(0x001C)(ConstParm, NoDestructor)
	bool                                          K2Node_SwitchEnum_CmpSuccess;                      // 0x0080(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_81[0x7];                                       // 0x0081(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	struct FTimerHandle                           CallFunc_K2_SetTimerDelegate_ReturnValue;          // 0x0088(0x0008)(NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_TextIsEmpty_ReturnValue;                  // 0x0090(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_91[0x7];                                       // 0x0091(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UScrollBox*                             CallFunc_GetScrollBox_ScrollBox;                   // 0x0098(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsVisible_ReturnValue;                    // 0x00A0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_A1[0x7];                                       // 0x00A1(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	struct FGeometry                              K2Node_Event_MyGeometry;                           // 0x00A8(0x0040)(IsPlainOldData, NoDestructor)
	float                                         K2Node_Event_InDeltaTime;                          // 0x00E8(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TDelegate<void(ECommonInputType bNewInputType)> K2Node_CreateDelegate_OutputDelegate_2;          // 0x00EC(0x0010)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_FC[0x4];                                       // 0x00FC(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UCommonInputSubsystem*                  CallFunc_GetLocalPlayerSubsystem_ReturnValue;      // 0x0100(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	TDelegate<void(ECommonInputType bNewInputType)> K2Node_CreateDelegate_OutputDelegate_3;          // 0x0108(0x0010)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class APlayerController*                      CallFunc_GetLocalPlayerController_ReturnValue;     // 0x0118(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class UCommonInputSubsystem*                  CallFunc_GetLocalPlayerSubsystem_ReturnValue_1;    // 0x0120(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x0128(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ECommonInputType                              CallFunc_GetCurrentInputType_ReturnValue;          // 0x0129(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsSteamDeck_ReturnValue;                  // 0x012A(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WBP_Ingame_Chat_C_ExecuteUbergraph_WBP_Ingame_Chat) == 0x000008, "Wrong alignment on WBP_Ingame_Chat_C_ExecuteUbergraph_WBP_Ingame_Chat");
static_assert(sizeof(WBP_Ingame_Chat_C_ExecuteUbergraph_WBP_Ingame_Chat) == 0x000130, "Wrong size on WBP_Ingame_Chat_C_ExecuteUbergraph_WBP_Ingame_Chat");
static_assert(offsetof(WBP_Ingame_Chat_C_ExecuteUbergraph_WBP_Ingame_Chat, EntryPoint) == 0x000000, "Member 'WBP_Ingame_Chat_C_ExecuteUbergraph_WBP_Ingame_Chat::EntryPoint' has a wrong offset!");
static_assert(offsetof(WBP_Ingame_Chat_C_ExecuteUbergraph_WBP_Ingame_Chat, K2Node_CreateDelegate_OutputDelegate) == 0x000004, "Member 'WBP_Ingame_Chat_C_ExecuteUbergraph_WBP_Ingame_Chat::K2Node_CreateDelegate_OutputDelegate' has a wrong offset!");
static_assert(offsetof(WBP_Ingame_Chat_C_ExecuteUbergraph_WBP_Ingame_Chat, K2Node_CreateDelegate_OutputDelegate_1) == 0x000014, "Member 'WBP_Ingame_Chat_C_ExecuteUbergraph_WBP_Ingame_Chat::K2Node_CreateDelegate_OutputDelegate_1' has a wrong offset!");
static_assert(offsetof(WBP_Ingame_Chat_C_ExecuteUbergraph_WBP_Ingame_Chat, CallFunc_CanChat_Result) == 0x000024, "Member 'WBP_Ingame_Chat_C_ExecuteUbergraph_WBP_Ingame_Chat::CallFunc_CanChat_Result' has a wrong offset!");
static_assert(offsetof(WBP_Ingame_Chat_C_ExecuteUbergraph_WBP_Ingame_Chat, CallFunc_CanChat_Result_1) == 0x000025, "Member 'WBP_Ingame_Chat_C_ExecuteUbergraph_WBP_Ingame_Chat::CallFunc_CanChat_Result_1' has a wrong offset!");
static_assert(offsetof(WBP_Ingame_Chat_C_ExecuteUbergraph_WBP_Ingame_Chat, CallFunc_CanChat_Result_2) == 0x000026, "Member 'WBP_Ingame_Chat_C_ExecuteUbergraph_WBP_Ingame_Chat::CallFunc_CanChat_Result_2' has a wrong offset!");
static_assert(offsetof(WBP_Ingame_Chat_C_ExecuteUbergraph_WBP_Ingame_Chat, CallFunc_GetLocalizedTextFromHandle_Text) == 0x000028, "Member 'WBP_Ingame_Chat_C_ExecuteUbergraph_WBP_Ingame_Chat::CallFunc_GetLocalizedTextFromHandle_Text' has a wrong offset!");
static_assert(offsetof(WBP_Ingame_Chat_C_ExecuteUbergraph_WBP_Ingame_Chat, CallFunc_GetOptionSubsystem_ReturnValue) == 0x000040, "Member 'WBP_Ingame_Chat_C_ExecuteUbergraph_WBP_Ingame_Chat::CallFunc_GetOptionSubsystem_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_Ingame_Chat_C_ExecuteUbergraph_WBP_Ingame_Chat, K2Node_ComponentBoundEvent_Text) == 0x000048, "Member 'WBP_Ingame_Chat_C_ExecuteUbergraph_WBP_Ingame_Chat::K2Node_ComponentBoundEvent_Text' has a wrong offset!");
static_assert(offsetof(WBP_Ingame_Chat_C_ExecuteUbergraph_WBP_Ingame_Chat, K2Node_ComponentBoundEvent_CommitMethod) == 0x000060, "Member 'WBP_Ingame_Chat_C_ExecuteUbergraph_WBP_Ingame_Chat::K2Node_ComponentBoundEvent_CommitMethod' has a wrong offset!");
static_assert(offsetof(WBP_Ingame_Chat_C_ExecuteUbergraph_WBP_Ingame_Chat, CallFunc_GetUISettings_ReturnValue) == 0x000064, "Member 'WBP_Ingame_Chat_C_ExecuteUbergraph_WBP_Ingame_Chat::CallFunc_GetUISettings_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_Ingame_Chat_C_ExecuteUbergraph_WBP_Ingame_Chat, K2Node_SwitchEnum_CmpSuccess) == 0x000080, "Member 'WBP_Ingame_Chat_C_ExecuteUbergraph_WBP_Ingame_Chat::K2Node_SwitchEnum_CmpSuccess' has a wrong offset!");
static_assert(offsetof(WBP_Ingame_Chat_C_ExecuteUbergraph_WBP_Ingame_Chat, CallFunc_K2_SetTimerDelegate_ReturnValue) == 0x000088, "Member 'WBP_Ingame_Chat_C_ExecuteUbergraph_WBP_Ingame_Chat::CallFunc_K2_SetTimerDelegate_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_Ingame_Chat_C_ExecuteUbergraph_WBP_Ingame_Chat, CallFunc_TextIsEmpty_ReturnValue) == 0x000090, "Member 'WBP_Ingame_Chat_C_ExecuteUbergraph_WBP_Ingame_Chat::CallFunc_TextIsEmpty_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_Ingame_Chat_C_ExecuteUbergraph_WBP_Ingame_Chat, CallFunc_GetScrollBox_ScrollBox) == 0x000098, "Member 'WBP_Ingame_Chat_C_ExecuteUbergraph_WBP_Ingame_Chat::CallFunc_GetScrollBox_ScrollBox' has a wrong offset!");
static_assert(offsetof(WBP_Ingame_Chat_C_ExecuteUbergraph_WBP_Ingame_Chat, CallFunc_IsVisible_ReturnValue) == 0x0000A0, "Member 'WBP_Ingame_Chat_C_ExecuteUbergraph_WBP_Ingame_Chat::CallFunc_IsVisible_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_Ingame_Chat_C_ExecuteUbergraph_WBP_Ingame_Chat, K2Node_Event_MyGeometry) == 0x0000A8, "Member 'WBP_Ingame_Chat_C_ExecuteUbergraph_WBP_Ingame_Chat::K2Node_Event_MyGeometry' has a wrong offset!");
static_assert(offsetof(WBP_Ingame_Chat_C_ExecuteUbergraph_WBP_Ingame_Chat, K2Node_Event_InDeltaTime) == 0x0000E8, "Member 'WBP_Ingame_Chat_C_ExecuteUbergraph_WBP_Ingame_Chat::K2Node_Event_InDeltaTime' has a wrong offset!");
static_assert(offsetof(WBP_Ingame_Chat_C_ExecuteUbergraph_WBP_Ingame_Chat, K2Node_CreateDelegate_OutputDelegate_2) == 0x0000EC, "Member 'WBP_Ingame_Chat_C_ExecuteUbergraph_WBP_Ingame_Chat::K2Node_CreateDelegate_OutputDelegate_2' has a wrong offset!");
static_assert(offsetof(WBP_Ingame_Chat_C_ExecuteUbergraph_WBP_Ingame_Chat, CallFunc_GetLocalPlayerSubsystem_ReturnValue) == 0x000100, "Member 'WBP_Ingame_Chat_C_ExecuteUbergraph_WBP_Ingame_Chat::CallFunc_GetLocalPlayerSubsystem_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_Ingame_Chat_C_ExecuteUbergraph_WBP_Ingame_Chat, K2Node_CreateDelegate_OutputDelegate_3) == 0x000108, "Member 'WBP_Ingame_Chat_C_ExecuteUbergraph_WBP_Ingame_Chat::K2Node_CreateDelegate_OutputDelegate_3' has a wrong offset!");
static_assert(offsetof(WBP_Ingame_Chat_C_ExecuteUbergraph_WBP_Ingame_Chat, CallFunc_GetLocalPlayerController_ReturnValue) == 0x000118, "Member 'WBP_Ingame_Chat_C_ExecuteUbergraph_WBP_Ingame_Chat::CallFunc_GetLocalPlayerController_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_Ingame_Chat_C_ExecuteUbergraph_WBP_Ingame_Chat, CallFunc_GetLocalPlayerSubsystem_ReturnValue_1) == 0x000120, "Member 'WBP_Ingame_Chat_C_ExecuteUbergraph_WBP_Ingame_Chat::CallFunc_GetLocalPlayerSubsystem_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(WBP_Ingame_Chat_C_ExecuteUbergraph_WBP_Ingame_Chat, CallFunc_IsValid_ReturnValue) == 0x000128, "Member 'WBP_Ingame_Chat_C_ExecuteUbergraph_WBP_Ingame_Chat::CallFunc_IsValid_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_Ingame_Chat_C_ExecuteUbergraph_WBP_Ingame_Chat, CallFunc_GetCurrentInputType_ReturnValue) == 0x000129, "Member 'WBP_Ingame_Chat_C_ExecuteUbergraph_WBP_Ingame_Chat::CallFunc_GetCurrentInputType_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_Ingame_Chat_C_ExecuteUbergraph_WBP_Ingame_Chat, CallFunc_IsSteamDeck_ReturnValue) == 0x00012A, "Member 'WBP_Ingame_Chat_C_ExecuteUbergraph_WBP_Ingame_Chat::CallFunc_IsSteamDeck_ReturnValue' has a wrong offset!");

// Function WBP_Ingame_Chat.WBP_Ingame_Chat_C.LoadChatMessages
// 0x0070 (0x0070 - 0x0000)
struct WBP_Ingame_Chat_C_LoadChatMessages final
{
public:
	int32                                         Temp_int_Array_Index_Variable;                     // 0x0000(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Loop_Counter_Variable;                    // 0x0004(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Add_IntInt_ReturnValue;                   // 0x0008(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_C[0x4];                                        // 0x000C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class APalGameStateInGame*                    CallFunc_GetPalGameStateInGame_ReturnValue;        // 0x0010(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class UScrollBox*                             CallFunc_GetScrollBox_ScrollBox;                   // 0x0018(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	struct FPalChatMessage                        CallFunc_Array_Get_Item;                           // 0x0020(0x0048)()
	int32                                         CallFunc_Array_Length_ReturnValue;                 // 0x0068(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Less_IntInt_ReturnValue;                  // 0x006C(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WBP_Ingame_Chat_C_LoadChatMessages) == 0x000008, "Wrong alignment on WBP_Ingame_Chat_C_LoadChatMessages");
static_assert(sizeof(WBP_Ingame_Chat_C_LoadChatMessages) == 0x000070, "Wrong size on WBP_Ingame_Chat_C_LoadChatMessages");
static_assert(offsetof(WBP_Ingame_Chat_C_LoadChatMessages, Temp_int_Array_Index_Variable) == 0x000000, "Member 'WBP_Ingame_Chat_C_LoadChatMessages::Temp_int_Array_Index_Variable' has a wrong offset!");
static_assert(offsetof(WBP_Ingame_Chat_C_LoadChatMessages, Temp_int_Loop_Counter_Variable) == 0x000004, "Member 'WBP_Ingame_Chat_C_LoadChatMessages::Temp_int_Loop_Counter_Variable' has a wrong offset!");
static_assert(offsetof(WBP_Ingame_Chat_C_LoadChatMessages, CallFunc_Add_IntInt_ReturnValue) == 0x000008, "Member 'WBP_Ingame_Chat_C_LoadChatMessages::CallFunc_Add_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_Ingame_Chat_C_LoadChatMessages, CallFunc_GetPalGameStateInGame_ReturnValue) == 0x000010, "Member 'WBP_Ingame_Chat_C_LoadChatMessages::CallFunc_GetPalGameStateInGame_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_Ingame_Chat_C_LoadChatMessages, CallFunc_GetScrollBox_ScrollBox) == 0x000018, "Member 'WBP_Ingame_Chat_C_LoadChatMessages::CallFunc_GetScrollBox_ScrollBox' has a wrong offset!");
static_assert(offsetof(WBP_Ingame_Chat_C_LoadChatMessages, CallFunc_Array_Get_Item) == 0x000020, "Member 'WBP_Ingame_Chat_C_LoadChatMessages::CallFunc_Array_Get_Item' has a wrong offset!");
static_assert(offsetof(WBP_Ingame_Chat_C_LoadChatMessages, CallFunc_Array_Length_ReturnValue) == 0x000068, "Member 'WBP_Ingame_Chat_C_LoadChatMessages::CallFunc_Array_Length_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_Ingame_Chat_C_LoadChatMessages, CallFunc_Less_IntInt_ReturnValue) == 0x00006C, "Member 'WBP_Ingame_Chat_C_LoadChatMessages::CallFunc_Less_IntInt_ReturnValue' has a wrong offset!");

// Function WBP_Ingame_Chat.WBP_Ingame_Chat_C.On Recived Chat
// 0x00A0 (0x00A0 - 0x0000)
struct WBP_Ingame_Chat_C_On_Recived_Chat final
{
public:
	struct FPalChatMessage                        Message;                                           // 0x0000(0x0048)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
	struct FLinearColor                           MessageColor;                                      // 0x0048(0x0010)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_CanChat_Result;                           // 0x0058(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_59[0x7];                                       // 0x0059(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UPalOptionSubsystem*                    CallFunc_GetOptionSubsystem_ReturnValue;           // 0x0060(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	struct FPalOptionUISettings                   CallFunc_GetUISettings_ReturnValue;                // 0x0068(0x001C)(ConstParm, NoDestructor)
	TDelegate<void()>                             K2Node_CreateDelegate_OutputDelegate;              // 0x0084(0x0010)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_94[0x4];                                       // 0x0094(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	struct FTimerHandle                           CallFunc_K2_SetTimerDelegate_ReturnValue;          // 0x0098(0x0008)(NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WBP_Ingame_Chat_C_On_Recived_Chat) == 0x000008, "Wrong alignment on WBP_Ingame_Chat_C_On_Recived_Chat");
static_assert(sizeof(WBP_Ingame_Chat_C_On_Recived_Chat) == 0x0000A0, "Wrong size on WBP_Ingame_Chat_C_On_Recived_Chat");
static_assert(offsetof(WBP_Ingame_Chat_C_On_Recived_Chat, Message) == 0x000000, "Member 'WBP_Ingame_Chat_C_On_Recived_Chat::Message' has a wrong offset!");
static_assert(offsetof(WBP_Ingame_Chat_C_On_Recived_Chat, MessageColor) == 0x000048, "Member 'WBP_Ingame_Chat_C_On_Recived_Chat::MessageColor' has a wrong offset!");
static_assert(offsetof(WBP_Ingame_Chat_C_On_Recived_Chat, CallFunc_CanChat_Result) == 0x000058, "Member 'WBP_Ingame_Chat_C_On_Recived_Chat::CallFunc_CanChat_Result' has a wrong offset!");
static_assert(offsetof(WBP_Ingame_Chat_C_On_Recived_Chat, CallFunc_GetOptionSubsystem_ReturnValue) == 0x000060, "Member 'WBP_Ingame_Chat_C_On_Recived_Chat::CallFunc_GetOptionSubsystem_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_Ingame_Chat_C_On_Recived_Chat, CallFunc_GetUISettings_ReturnValue) == 0x000068, "Member 'WBP_Ingame_Chat_C_On_Recived_Chat::CallFunc_GetUISettings_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_Ingame_Chat_C_On_Recived_Chat, K2Node_CreateDelegate_OutputDelegate) == 0x000084, "Member 'WBP_Ingame_Chat_C_On_Recived_Chat::K2Node_CreateDelegate_OutputDelegate' has a wrong offset!");
static_assert(offsetof(WBP_Ingame_Chat_C_On_Recived_Chat, CallFunc_K2_SetTimerDelegate_ReturnValue) == 0x000098, "Member 'WBP_Ingame_Chat_C_On_Recived_Chat::CallFunc_K2_SetTimerDelegate_ReturnValue' has a wrong offset!");

// Function WBP_Ingame_Chat.WBP_Ingame_Chat_C.OnChangedInputType
// 0x0002 (0x0002 - 0x0000)
struct WBP_Ingame_Chat_C_OnChangedInputType final
{
public:
	ECommonInputType                              bNewInputType;                                     // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_SwitchEnum_CmpSuccess;                      // 0x0001(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WBP_Ingame_Chat_C_OnChangedInputType) == 0x000001, "Wrong alignment on WBP_Ingame_Chat_C_OnChangedInputType");
static_assert(sizeof(WBP_Ingame_Chat_C_OnChangedInputType) == 0x000002, "Wrong size on WBP_Ingame_Chat_C_OnChangedInputType");
static_assert(offsetof(WBP_Ingame_Chat_C_OnChangedInputType, bNewInputType) == 0x000000, "Member 'WBP_Ingame_Chat_C_OnChangedInputType::bNewInputType' has a wrong offset!");
static_assert(offsetof(WBP_Ingame_Chat_C_OnChangedInputType, K2Node_SwitchEnum_CmpSuccess) == 0x000001, "Member 'WBP_Ingame_Chat_C_OnChangedInputType::K2Node_SwitchEnum_CmpSuccess' has a wrong offset!");

// Function WBP_Ingame_Chat.WBP_Ingame_Chat_C.OnPreviewKeyDown
// 0x02E0 (0x02E0 - 0x0000)
struct WBP_Ingame_Chat_C_OnPreviewKeyDown final
{
public:
	struct FGeometry                              MyGeometry;                                        // 0x0000(0x0040)(BlueprintVisible, BlueprintReadOnly, Parm, IsPlainOldData, NoDestructor)
	struct FKeyEvent                              InKeyEvent;                                        // 0x0040(0x0040)(BlueprintVisible, BlueprintReadOnly, Parm)
	struct FEventReply                            ReturnValue;                                       // 0x0080(0x00B8)(Parm, OutParm, ReturnParm)
	struct FKey                                   CallFunc_GetKey_ReturnValue;                       // 0x0138(0x0018)(HasGetValueTypeHash)
	class FText                                   CallFunc_GetText_ReturnValue;                      // 0x0150(0x0018)()
	bool                                          CallFunc_EqualEqual_KeyKey_ReturnValue;            // 0x0168(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_169[0x7];                                      // 0x0169(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	struct FEventReply                            CallFunc_Unhandled_ReturnValue;                    // 0x0170(0x00B8)()
	struct FEventReply                            CallFunc_Handled_ReturnValue;                      // 0x0228(0x00B8)()
};
static_assert(alignof(WBP_Ingame_Chat_C_OnPreviewKeyDown) == 0x000008, "Wrong alignment on WBP_Ingame_Chat_C_OnPreviewKeyDown");
static_assert(sizeof(WBP_Ingame_Chat_C_OnPreviewKeyDown) == 0x0002E0, "Wrong size on WBP_Ingame_Chat_C_OnPreviewKeyDown");
static_assert(offsetof(WBP_Ingame_Chat_C_OnPreviewKeyDown, MyGeometry) == 0x000000, "Member 'WBP_Ingame_Chat_C_OnPreviewKeyDown::MyGeometry' has a wrong offset!");
static_assert(offsetof(WBP_Ingame_Chat_C_OnPreviewKeyDown, InKeyEvent) == 0x000040, "Member 'WBP_Ingame_Chat_C_OnPreviewKeyDown::InKeyEvent' has a wrong offset!");
static_assert(offsetof(WBP_Ingame_Chat_C_OnPreviewKeyDown, ReturnValue) == 0x000080, "Member 'WBP_Ingame_Chat_C_OnPreviewKeyDown::ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_Ingame_Chat_C_OnPreviewKeyDown, CallFunc_GetKey_ReturnValue) == 0x000138, "Member 'WBP_Ingame_Chat_C_OnPreviewKeyDown::CallFunc_GetKey_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_Ingame_Chat_C_OnPreviewKeyDown, CallFunc_GetText_ReturnValue) == 0x000150, "Member 'WBP_Ingame_Chat_C_OnPreviewKeyDown::CallFunc_GetText_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_Ingame_Chat_C_OnPreviewKeyDown, CallFunc_EqualEqual_KeyKey_ReturnValue) == 0x000168, "Member 'WBP_Ingame_Chat_C_OnPreviewKeyDown::CallFunc_EqualEqual_KeyKey_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_Ingame_Chat_C_OnPreviewKeyDown, CallFunc_Unhandled_ReturnValue) == 0x000170, "Member 'WBP_Ingame_Chat_C_OnPreviewKeyDown::CallFunc_Unhandled_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_Ingame_Chat_C_OnPreviewKeyDown, CallFunc_Handled_ReturnValue) == 0x000228, "Member 'WBP_Ingame_Chat_C_OnPreviewKeyDown::CallFunc_Handled_ReturnValue' has a wrong offset!");

// Function WBP_Ingame_Chat.WBP_Ingame_Chat_C.OnTextCommittedInternal
// 0x0030 (0x0030 - 0x0000)
struct WBP_Ingame_Chat_C_OnTextCommittedInternal final
{
public:
	class FText                                   InText;                                            // 0x0000(0x0018)(BlueprintVisible, BlueprintReadOnly, Parm)
	ETextCommit                                   InTextCommit;                                      // 0x0018(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_SwitchEnum_CmpSuccess;                      // 0x0019(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_1A[0x6];                                       // 0x001A(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	class APalPlayerState*                        CallFunc_GetLocalPlayerState_ReturnValue;          // 0x0020(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_EnterChat_ReturnValue;                    // 0x0028(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WBP_Ingame_Chat_C_OnTextCommittedInternal) == 0x000008, "Wrong alignment on WBP_Ingame_Chat_C_OnTextCommittedInternal");
static_assert(sizeof(WBP_Ingame_Chat_C_OnTextCommittedInternal) == 0x000030, "Wrong size on WBP_Ingame_Chat_C_OnTextCommittedInternal");
static_assert(offsetof(WBP_Ingame_Chat_C_OnTextCommittedInternal, InText) == 0x000000, "Member 'WBP_Ingame_Chat_C_OnTextCommittedInternal::InText' has a wrong offset!");
static_assert(offsetof(WBP_Ingame_Chat_C_OnTextCommittedInternal, InTextCommit) == 0x000018, "Member 'WBP_Ingame_Chat_C_OnTextCommittedInternal::InTextCommit' has a wrong offset!");
static_assert(offsetof(WBP_Ingame_Chat_C_OnTextCommittedInternal, K2Node_SwitchEnum_CmpSuccess) == 0x000019, "Member 'WBP_Ingame_Chat_C_OnTextCommittedInternal::K2Node_SwitchEnum_CmpSuccess' has a wrong offset!");
static_assert(offsetof(WBP_Ingame_Chat_C_OnTextCommittedInternal, CallFunc_GetLocalPlayerState_ReturnValue) == 0x000020, "Member 'WBP_Ingame_Chat_C_OnTextCommittedInternal::CallFunc_GetLocalPlayerState_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_Ingame_Chat_C_OnTextCommittedInternal, CallFunc_EnterChat_ReturnValue) == 0x000028, "Member 'WBP_Ingame_Chat_C_OnTextCommittedInternal::CallFunc_EnterChat_ReturnValue' has a wrong offset!");

// Function WBP_Ingame_Chat.WBP_Ingame_Chat_C.ResetFocus
// 0x0001 (0x0001 - 0x0000)
struct WBP_Ingame_Chat_C_ResetFocus final
{
public:
	bool                                          CallFunc_HasKeyboardFocus_ReturnValue;             // 0x0000(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WBP_Ingame_Chat_C_ResetFocus) == 0x000001, "Wrong alignment on WBP_Ingame_Chat_C_ResetFocus");
static_assert(sizeof(WBP_Ingame_Chat_C_ResetFocus) == 0x000001, "Wrong size on WBP_Ingame_Chat_C_ResetFocus");
static_assert(offsetof(WBP_Ingame_Chat_C_ResetFocus, CallFunc_HasKeyboardFocus_ReturnValue) == 0x000000, "Member 'WBP_Ingame_Chat_C_ResetFocus::CallFunc_HasKeyboardFocus_ReturnValue' has a wrong offset!");

// Function WBP_Ingame_Chat.WBP_Ingame_Chat_C.Tick
// 0x0048 (0x0048 - 0x0000)
struct WBP_Ingame_Chat_C_Tick final
{
public:
	struct FGeometry                              MyGeometry;                                        // 0x0000(0x0040)(BlueprintVisible, BlueprintReadOnly, Parm, IsPlainOldData, NoDestructor)
	float                                         InDeltaTime;                                       // 0x0040(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WBP_Ingame_Chat_C_Tick) == 0x000008, "Wrong alignment on WBP_Ingame_Chat_C_Tick");
static_assert(sizeof(WBP_Ingame_Chat_C_Tick) == 0x000048, "Wrong size on WBP_Ingame_Chat_C_Tick");
static_assert(offsetof(WBP_Ingame_Chat_C_Tick, MyGeometry) == 0x000000, "Member 'WBP_Ingame_Chat_C_Tick::MyGeometry' has a wrong offset!");
static_assert(offsetof(WBP_Ingame_Chat_C_Tick, InDeltaTime) == 0x000040, "Member 'WBP_Ingame_Chat_C_Tick::InDeltaTime' has a wrong offset!");

}

