#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_QuickStackCheckPopup

#include "Basic.hpp"

#include "InputCore_structs.hpp"
#include "SlateCore_structs.hpp"
#include "UMG_structs.hpp"


namespace SDK::Params
{

// Function WBP_QuickStackCheckPopup.WBP_QuickStackCheckPopup_C.ExecuteUbergraph_WBP_QuickStackCheckPopup
// 0x0020 (0x0020 - 0x0000)
struct WBP_QuickStackCheckPopup_C_ExecuteUbergraph_WBP_QuickStackCheckPopup final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4[0x4];                                        // 0x0004(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UPalHUDDispatchParameterBase*           CallFunc_GetParam_ReturnValue;                     // 0x0008(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class UBP_HUDDispatchParameter_QuickStackConfirm_C* K2Node_DynamicCast_AsBP_HUDDispatch_Parameter_Quick_Stack_Confirm; // 0x0010(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x0018(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WBP_QuickStackCheckPopup_C_ExecuteUbergraph_WBP_QuickStackCheckPopup) == 0x000008, "Wrong alignment on WBP_QuickStackCheckPopup_C_ExecuteUbergraph_WBP_QuickStackCheckPopup");
static_assert(sizeof(WBP_QuickStackCheckPopup_C_ExecuteUbergraph_WBP_QuickStackCheckPopup) == 0x000020, "Wrong size on WBP_QuickStackCheckPopup_C_ExecuteUbergraph_WBP_QuickStackCheckPopup");
static_assert(offsetof(WBP_QuickStackCheckPopup_C_ExecuteUbergraph_WBP_QuickStackCheckPopup, EntryPoint) == 0x000000, "Member 'WBP_QuickStackCheckPopup_C_ExecuteUbergraph_WBP_QuickStackCheckPopup::EntryPoint' has a wrong offset!");
static_assert(offsetof(WBP_QuickStackCheckPopup_C_ExecuteUbergraph_WBP_QuickStackCheckPopup, CallFunc_GetParam_ReturnValue) == 0x000008, "Member 'WBP_QuickStackCheckPopup_C_ExecuteUbergraph_WBP_QuickStackCheckPopup::CallFunc_GetParam_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_QuickStackCheckPopup_C_ExecuteUbergraph_WBP_QuickStackCheckPopup, K2Node_DynamicCast_AsBP_HUDDispatch_Parameter_Quick_Stack_Confirm) == 0x000010, "Member 'WBP_QuickStackCheckPopup_C_ExecuteUbergraph_WBP_QuickStackCheckPopup::K2Node_DynamicCast_AsBP_HUDDispatch_Parameter_Quick_Stack_Confirm' has a wrong offset!");
static_assert(offsetof(WBP_QuickStackCheckPopup_C_ExecuteUbergraph_WBP_QuickStackCheckPopup, K2Node_DynamicCast_bSuccess) == 0x000018, "Member 'WBP_QuickStackCheckPopup_C_ExecuteUbergraph_WBP_QuickStackCheckPopup::K2Node_DynamicCast_bSuccess' has a wrong offset!");

// Function WBP_QuickStackCheckPopup.WBP_QuickStackCheckPopup_C.GetLeftButton
// 0x0008 (0x0008 - 0x0000)
struct WBP_QuickStackCheckPopup_C_GetLeftButton final
{
public:
	class UCommonButtonBase*                      rightButton;                                       // 0x0000(0x0008)(Parm, OutParm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WBP_QuickStackCheckPopup_C_GetLeftButton) == 0x000008, "Wrong alignment on WBP_QuickStackCheckPopup_C_GetLeftButton");
static_assert(sizeof(WBP_QuickStackCheckPopup_C_GetLeftButton) == 0x000008, "Wrong size on WBP_QuickStackCheckPopup_C_GetLeftButton");
static_assert(offsetof(WBP_QuickStackCheckPopup_C_GetLeftButton, rightButton) == 0x000000, "Member 'WBP_QuickStackCheckPopup_C_GetLeftButton::rightButton' has a wrong offset!");

// Function WBP_QuickStackCheckPopup.WBP_QuickStackCheckPopup_C.GetRightButton
// 0x0008 (0x0008 - 0x0000)
struct WBP_QuickStackCheckPopup_C_GetRightButton final
{
public:
	class UCommonButtonBase*                      Button;                                            // 0x0000(0x0008)(Parm, OutParm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WBP_QuickStackCheckPopup_C_GetRightButton) == 0x000008, "Wrong alignment on WBP_QuickStackCheckPopup_C_GetRightButton");
static_assert(sizeof(WBP_QuickStackCheckPopup_C_GetRightButton) == 0x000008, "Wrong size on WBP_QuickStackCheckPopup_C_GetRightButton");
static_assert(offsetof(WBP_QuickStackCheckPopup_C_GetRightButton, Button) == 0x000000, "Member 'WBP_QuickStackCheckPopup_C_GetRightButton::Button' has a wrong offset!");

// Function WBP_QuickStackCheckPopup.WBP_QuickStackCheckPopup_C.OnAnalogValueChanged
// 0x0360 (0x0360 - 0x0000)
struct WBP_QuickStackCheckPopup_C_OnAnalogValueChanged final
{
public:
	struct FGeometry                              MyGeometry;                                        // 0x0000(0x0040)(BlueprintVisible, BlueprintReadOnly, Parm, IsPlainOldData, NoDestructor)
	struct FAnalogInputEvent                      InAnalogInputEvent;                                // 0x0040(0x0048)(BlueprintVisible, BlueprintReadOnly, Parm)
	struct FEventReply                            ReturnValue;                                       // 0x0088(0x00B8)(Parm, OutParm, ReturnParm)
	float                                         CallFunc_GetAnalogValue_ReturnValue;               // 0x0140(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_GetScrollOffset_ReturnValue;              // 0x0144(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_Multiply_DoubleDouble_ReturnValue;        // 0x0148(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_GetScrollOffsetOfEnd_ReturnValue;         // 0x0150(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_154[0x4];                                      // 0x0154(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	double                                        CallFunc_Add_DoubleDouble_ReturnValue;             // 0x0158(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FKeyEvent                              CallFunc_GetKeyEventFromAnalogInputEvent_ReturnValue; // 0x0160(0x0040)()
	double                                        CallFunc_FMax_ReturnValue;                         // 0x01A0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FKey                                   CallFunc_GetKey_ReturnValue;                       // 0x01A8(0x0018)(HasGetValueTypeHash)
	double                                        CallFunc_FMin_ReturnValue;                         // 0x01C0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_EqualEqual_KeyKey_ReturnValue;            // 0x01C8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_1C9[0x7];                                      // 0x01C9(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	struct FEventReply                            CallFunc_Handled_ReturnValue;                      // 0x01D0(0x00B8)()
	struct FEventReply                            CallFunc_Unhandled_ReturnValue;                    // 0x0288(0x00B8)()
	double                                        CallFunc_Multiply_DoubleDouble_A_ImplicitCast;     // 0x0340(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_Add_DoubleDouble_A_ImplicitCast;          // 0x0348(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_FMin_B_ImplicitCast;                      // 0x0350(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_SetScrollOffset_NewScrollOffset_ImplicitCast; // 0x0358(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WBP_QuickStackCheckPopup_C_OnAnalogValueChanged) == 0x000008, "Wrong alignment on WBP_QuickStackCheckPopup_C_OnAnalogValueChanged");
static_assert(sizeof(WBP_QuickStackCheckPopup_C_OnAnalogValueChanged) == 0x000360, "Wrong size on WBP_QuickStackCheckPopup_C_OnAnalogValueChanged");
static_assert(offsetof(WBP_QuickStackCheckPopup_C_OnAnalogValueChanged, MyGeometry) == 0x000000, "Member 'WBP_QuickStackCheckPopup_C_OnAnalogValueChanged::MyGeometry' has a wrong offset!");
static_assert(offsetof(WBP_QuickStackCheckPopup_C_OnAnalogValueChanged, InAnalogInputEvent) == 0x000040, "Member 'WBP_QuickStackCheckPopup_C_OnAnalogValueChanged::InAnalogInputEvent' has a wrong offset!");
static_assert(offsetof(WBP_QuickStackCheckPopup_C_OnAnalogValueChanged, ReturnValue) == 0x000088, "Member 'WBP_QuickStackCheckPopup_C_OnAnalogValueChanged::ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_QuickStackCheckPopup_C_OnAnalogValueChanged, CallFunc_GetAnalogValue_ReturnValue) == 0x000140, "Member 'WBP_QuickStackCheckPopup_C_OnAnalogValueChanged::CallFunc_GetAnalogValue_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_QuickStackCheckPopup_C_OnAnalogValueChanged, CallFunc_GetScrollOffset_ReturnValue) == 0x000144, "Member 'WBP_QuickStackCheckPopup_C_OnAnalogValueChanged::CallFunc_GetScrollOffset_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_QuickStackCheckPopup_C_OnAnalogValueChanged, CallFunc_Multiply_DoubleDouble_ReturnValue) == 0x000148, "Member 'WBP_QuickStackCheckPopup_C_OnAnalogValueChanged::CallFunc_Multiply_DoubleDouble_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_QuickStackCheckPopup_C_OnAnalogValueChanged, CallFunc_GetScrollOffsetOfEnd_ReturnValue) == 0x000150, "Member 'WBP_QuickStackCheckPopup_C_OnAnalogValueChanged::CallFunc_GetScrollOffsetOfEnd_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_QuickStackCheckPopup_C_OnAnalogValueChanged, CallFunc_Add_DoubleDouble_ReturnValue) == 0x000158, "Member 'WBP_QuickStackCheckPopup_C_OnAnalogValueChanged::CallFunc_Add_DoubleDouble_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_QuickStackCheckPopup_C_OnAnalogValueChanged, CallFunc_GetKeyEventFromAnalogInputEvent_ReturnValue) == 0x000160, "Member 'WBP_QuickStackCheckPopup_C_OnAnalogValueChanged::CallFunc_GetKeyEventFromAnalogInputEvent_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_QuickStackCheckPopup_C_OnAnalogValueChanged, CallFunc_FMax_ReturnValue) == 0x0001A0, "Member 'WBP_QuickStackCheckPopup_C_OnAnalogValueChanged::CallFunc_FMax_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_QuickStackCheckPopup_C_OnAnalogValueChanged, CallFunc_GetKey_ReturnValue) == 0x0001A8, "Member 'WBP_QuickStackCheckPopup_C_OnAnalogValueChanged::CallFunc_GetKey_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_QuickStackCheckPopup_C_OnAnalogValueChanged, CallFunc_FMin_ReturnValue) == 0x0001C0, "Member 'WBP_QuickStackCheckPopup_C_OnAnalogValueChanged::CallFunc_FMin_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_QuickStackCheckPopup_C_OnAnalogValueChanged, CallFunc_EqualEqual_KeyKey_ReturnValue) == 0x0001C8, "Member 'WBP_QuickStackCheckPopup_C_OnAnalogValueChanged::CallFunc_EqualEqual_KeyKey_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_QuickStackCheckPopup_C_OnAnalogValueChanged, CallFunc_Handled_ReturnValue) == 0x0001D0, "Member 'WBP_QuickStackCheckPopup_C_OnAnalogValueChanged::CallFunc_Handled_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_QuickStackCheckPopup_C_OnAnalogValueChanged, CallFunc_Unhandled_ReturnValue) == 0x000288, "Member 'WBP_QuickStackCheckPopup_C_OnAnalogValueChanged::CallFunc_Unhandled_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_QuickStackCheckPopup_C_OnAnalogValueChanged, CallFunc_Multiply_DoubleDouble_A_ImplicitCast) == 0x000340, "Member 'WBP_QuickStackCheckPopup_C_OnAnalogValueChanged::CallFunc_Multiply_DoubleDouble_A_ImplicitCast' has a wrong offset!");
static_assert(offsetof(WBP_QuickStackCheckPopup_C_OnAnalogValueChanged, CallFunc_Add_DoubleDouble_A_ImplicitCast) == 0x000348, "Member 'WBP_QuickStackCheckPopup_C_OnAnalogValueChanged::CallFunc_Add_DoubleDouble_A_ImplicitCast' has a wrong offset!");
static_assert(offsetof(WBP_QuickStackCheckPopup_C_OnAnalogValueChanged, CallFunc_FMin_B_ImplicitCast) == 0x000350, "Member 'WBP_QuickStackCheckPopup_C_OnAnalogValueChanged::CallFunc_FMin_B_ImplicitCast' has a wrong offset!");
static_assert(offsetof(WBP_QuickStackCheckPopup_C_OnAnalogValueChanged, CallFunc_SetScrollOffset_NewScrollOffset_ImplicitCast) == 0x000358, "Member 'WBP_QuickStackCheckPopup_C_OnAnalogValueChanged::CallFunc_SetScrollOffset_NewScrollOffset_ImplicitCast' has a wrong offset!");

// Function WBP_QuickStackCheckPopup.WBP_QuickStackCheckPopup_C.Setup
// 0x0048 (0x0048 - 0x0000)
struct WBP_QuickStackCheckPopup_C_Setup final
{
public:
	int32                                         Temp_int_Array_Index_Variable;                     // 0x0000(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Loop_Counter_Variable;                    // 0x0004(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Add_IntInt_ReturnValue;                   // 0x0008(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_C[0x4];                                        // 0x000C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class APlayerController*                      CallFunc_GetLocalPlayerController_ReturnValue;     // 0x0010(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class UPalItemSlot*                           CallFunc_Array_Get_Item;                           // 0x0018(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class UWBP_PalInGameMenuItemSlotButton_C*     CallFunc_Create_ReturnValue;                       // 0x0020(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Array_Length_ReturnValue;                 // 0x0028(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_2C[0x4];                                       // 0x002C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class USizeBox*                               CallFunc_WrapSizeBox_CreatedSizeBox;               // 0x0030(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Less_IntInt_ReturnValue;                  // 0x0038(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_39[0x7];                                       // 0x0039(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UWrapBoxSlot*                           CallFunc_AddChildToWrapBox_ReturnValue;            // 0x0040(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WBP_QuickStackCheckPopup_C_Setup) == 0x000008, "Wrong alignment on WBP_QuickStackCheckPopup_C_Setup");
static_assert(sizeof(WBP_QuickStackCheckPopup_C_Setup) == 0x000048, "Wrong size on WBP_QuickStackCheckPopup_C_Setup");
static_assert(offsetof(WBP_QuickStackCheckPopup_C_Setup, Temp_int_Array_Index_Variable) == 0x000000, "Member 'WBP_QuickStackCheckPopup_C_Setup::Temp_int_Array_Index_Variable' has a wrong offset!");
static_assert(offsetof(WBP_QuickStackCheckPopup_C_Setup, Temp_int_Loop_Counter_Variable) == 0x000004, "Member 'WBP_QuickStackCheckPopup_C_Setup::Temp_int_Loop_Counter_Variable' has a wrong offset!");
static_assert(offsetof(WBP_QuickStackCheckPopup_C_Setup, CallFunc_Add_IntInt_ReturnValue) == 0x000008, "Member 'WBP_QuickStackCheckPopup_C_Setup::CallFunc_Add_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_QuickStackCheckPopup_C_Setup, CallFunc_GetLocalPlayerController_ReturnValue) == 0x000010, "Member 'WBP_QuickStackCheckPopup_C_Setup::CallFunc_GetLocalPlayerController_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_QuickStackCheckPopup_C_Setup, CallFunc_Array_Get_Item) == 0x000018, "Member 'WBP_QuickStackCheckPopup_C_Setup::CallFunc_Array_Get_Item' has a wrong offset!");
static_assert(offsetof(WBP_QuickStackCheckPopup_C_Setup, CallFunc_Create_ReturnValue) == 0x000020, "Member 'WBP_QuickStackCheckPopup_C_Setup::CallFunc_Create_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_QuickStackCheckPopup_C_Setup, CallFunc_Array_Length_ReturnValue) == 0x000028, "Member 'WBP_QuickStackCheckPopup_C_Setup::CallFunc_Array_Length_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_QuickStackCheckPopup_C_Setup, CallFunc_WrapSizeBox_CreatedSizeBox) == 0x000030, "Member 'WBP_QuickStackCheckPopup_C_Setup::CallFunc_WrapSizeBox_CreatedSizeBox' has a wrong offset!");
static_assert(offsetof(WBP_QuickStackCheckPopup_C_Setup, CallFunc_Less_IntInt_ReturnValue) == 0x000038, "Member 'WBP_QuickStackCheckPopup_C_Setup::CallFunc_Less_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_QuickStackCheckPopup_C_Setup, CallFunc_AddChildToWrapBox_ReturnValue) == 0x000040, "Member 'WBP_QuickStackCheckPopup_C_Setup::CallFunc_AddChildToWrapBox_ReturnValue' has a wrong offset!");

// Function WBP_QuickStackCheckPopup.WBP_QuickStackCheckPopup_C.BP_GetDesiredFocusTarget
// 0x0008 (0x0008 - 0x0000)
struct WBP_QuickStackCheckPopup_C_BP_GetDesiredFocusTarget final
{
public:
	class UWidget*                                ReturnValue;                                       // 0x0000(0x0008)(Parm, OutParm, ZeroConstructor, ReturnParm, InstancedReference, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WBP_QuickStackCheckPopup_C_BP_GetDesiredFocusTarget) == 0x000008, "Wrong alignment on WBP_QuickStackCheckPopup_C_BP_GetDesiredFocusTarget");
static_assert(sizeof(WBP_QuickStackCheckPopup_C_BP_GetDesiredFocusTarget) == 0x000008, "Wrong size on WBP_QuickStackCheckPopup_C_BP_GetDesiredFocusTarget");
static_assert(offsetof(WBP_QuickStackCheckPopup_C_BP_GetDesiredFocusTarget, ReturnValue) == 0x000000, "Member 'WBP_QuickStackCheckPopup_C_BP_GetDesiredFocusTarget::ReturnValue' has a wrong offset!");

}

