#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_PalQuestTrackingIcon

#include "Basic.hpp"

#include "WBP_LoupeBase_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass WBP_PalQuestTrackingIcon.WBP_PalQuestTrackingIcon_C
// 0x0048 (0x04D0 - 0x0488)
class UWBP_PalQuestTrackingIcon_C final : public UWBP_LoupeBase_C
{
public:
	class UWBP_NPC_OverheadQuest_C*               WBP_NPC_OverheadQuest;                             // 0x0488(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	TSoftObjectPtr<class UPalLocationPoint_QuestBase> SoftLocationData;                              // 0x0490(0x0030)(Edit, BlueprintVisible, DisableEditOnInstance, HasGetValueTypeHash)
	double                                        HeadOffset;                                        // 0x04C0(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FName                                   MyQuestId;                                         // 0x04C8(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void CalcScreenPosition();
	void GetLoupeWidgetSize(struct FVector2D* widgetSize_0);
	void GetTargetWidgetSize(struct FVector2D* outVector);
	void GetTargetWorldLocation(struct FVector* outVector);
	bool IsEnableLoupe();
	void SetFinalWidgetOpacity(double calcedOpacity);
	void Setup(TSoftObjectPtr<class UPalLocationPoint_QuestBase> SoftQuestLocation);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"WBP_PalQuestTrackingIcon_C">();
	}
	static class UWBP_PalQuestTrackingIcon_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_PalQuestTrackingIcon_C>();
	}
};
static_assert(alignof(UWBP_PalQuestTrackingIcon_C) == 0x000008, "Wrong alignment on UWBP_PalQuestTrackingIcon_C");
static_assert(sizeof(UWBP_PalQuestTrackingIcon_C) == 0x0004D0, "Wrong size on UWBP_PalQuestTrackingIcon_C");
static_assert(offsetof(UWBP_PalQuestTrackingIcon_C, WBP_NPC_OverheadQuest) == 0x000488, "Member 'UWBP_PalQuestTrackingIcon_C::WBP_NPC_OverheadQuest' has a wrong offset!");
static_assert(offsetof(UWBP_PalQuestTrackingIcon_C, SoftLocationData) == 0x000490, "Member 'UWBP_PalQuestTrackingIcon_C::SoftLocationData' has a wrong offset!");
static_assert(offsetof(UWBP_PalQuestTrackingIcon_C, HeadOffset) == 0x0004C0, "Member 'UWBP_PalQuestTrackingIcon_C::HeadOffset' has a wrong offset!");
static_assert(offsetof(UWBP_PalQuestTrackingIcon_C, MyQuestId) == 0x0004C8, "Member 'UWBP_PalQuestTrackingIcon_C::MyQuestId' has a wrong offset!");

}

