#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_ActionFishingSuccess

#include "Basic.hpp"


namespace SDK::Params
{

// Function BP_ActionFishingSuccess.BP_ActionFishingSuccess_C.ExecuteUbergraph_BP_ActionFishingSuccess
// 0x0004 (0x0004 - 0x0000)
struct BP_ActionFishingSuccess_C_ExecuteUbergraph_BP_ActionFishingSuccess final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_ActionFishingSuccess_C_ExecuteUbergraph_BP_ActionFishingSuccess) == 0x000004, "Wrong alignment on BP_ActionFishingSuccess_C_ExecuteUbergraph_BP_ActionFishingSuccess");
static_assert(sizeof(BP_ActionFishingSuccess_C_ExecuteUbergraph_BP_ActionFishingSuccess) == 0x000004, "Wrong size on BP_ActionFishingSuccess_C_ExecuteUbergraph_BP_ActionFishingSuccess");
static_assert(offsetof(BP_ActionFishingSuccess_C_ExecuteUbergraph_BP_ActionFishingSuccess, EntryPoint) == 0x000000, "Member 'BP_ActionFishingSuccess_C_ExecuteUbergraph_BP_ActionFishingSuccess::EntryPoint' has a wrong offset!");

// Function BP_ActionFishingSuccess.BP_ActionFishingSuccess_C.NotifySalvageSuccessToWeapon
// 0x0038 (0x0038 - 0x0000)
struct BP_ActionFishingSuccess_C_NotifySalvageSuccessToWeapon final
{
public:
	class APalCharacter*                          CallFunc_GetActionCharacter_ReturnValue;           // 0x0000(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class UPalShooterComponent*                   CallFunc_GetComponentByClass_ReturnValue;          // 0x0008(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	class APalWeaponBase*                         CallFunc_GetHasWeapon_ReturnValue;                 // 0x0010(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x0018(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_19[0x7];                                       // 0x0019(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	TScriptInterface<class IBI_PalFishingNotifyInterface_C> K2Node_DynamicCast_AsBI_Pal_Fishing_Notify_Interface; // 0x0020(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x0030(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_ActionFishingSuccess_C_NotifySalvageSuccessToWeapon) == 0x000008, "Wrong alignment on BP_ActionFishingSuccess_C_NotifySalvageSuccessToWeapon");
static_assert(sizeof(BP_ActionFishingSuccess_C_NotifySalvageSuccessToWeapon) == 0x000038, "Wrong size on BP_ActionFishingSuccess_C_NotifySalvageSuccessToWeapon");
static_assert(offsetof(BP_ActionFishingSuccess_C_NotifySalvageSuccessToWeapon, CallFunc_GetActionCharacter_ReturnValue) == 0x000000, "Member 'BP_ActionFishingSuccess_C_NotifySalvageSuccessToWeapon::CallFunc_GetActionCharacter_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_ActionFishingSuccess_C_NotifySalvageSuccessToWeapon, CallFunc_GetComponentByClass_ReturnValue) == 0x000008, "Member 'BP_ActionFishingSuccess_C_NotifySalvageSuccessToWeapon::CallFunc_GetComponentByClass_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_ActionFishingSuccess_C_NotifySalvageSuccessToWeapon, CallFunc_GetHasWeapon_ReturnValue) == 0x000010, "Member 'BP_ActionFishingSuccess_C_NotifySalvageSuccessToWeapon::CallFunc_GetHasWeapon_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_ActionFishingSuccess_C_NotifySalvageSuccessToWeapon, CallFunc_IsValid_ReturnValue) == 0x000018, "Member 'BP_ActionFishingSuccess_C_NotifySalvageSuccessToWeapon::CallFunc_IsValid_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_ActionFishingSuccess_C_NotifySalvageSuccessToWeapon, K2Node_DynamicCast_AsBI_Pal_Fishing_Notify_Interface) == 0x000020, "Member 'BP_ActionFishingSuccess_C_NotifySalvageSuccessToWeapon::K2Node_DynamicCast_AsBI_Pal_Fishing_Notify_Interface' has a wrong offset!");
static_assert(offsetof(BP_ActionFishingSuccess_C_NotifySalvageSuccessToWeapon, K2Node_DynamicCast_bSuccess) == 0x000030, "Member 'BP_ActionFishingSuccess_C_NotifySalvageSuccessToWeapon::K2Node_DynamicCast_bSuccess' has a wrong offset!");

// Function BP_ActionFishingSuccess.BP_ActionFishingSuccess_C.SetUseUpperBodyOnly
// 0x0030 (0x0030 - 0x0000)
struct BP_ActionFishingSuccess_C_SetUseUpperBodyOnly final
{
public:
	bool                                          Enable;                                            // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_1[0x7];                                        // 0x0001(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class APalCharacter*                          CallFunc_GetActionCharacter_ReturnValue;           // 0x0008(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class UPalSkeletalMeshComponent*              CallFunc_GetMainMesh_ReturnValue;                  // 0x0010(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	class UAnimInstance*                          CallFunc_GetAnimInstance_ReturnValue;              // 0x0018(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class UPalAnimInstance*                       K2Node_DynamicCast_AsPal_Anim_Instance;            // 0x0020(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x0028(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_ActionFishingSuccess_C_SetUseUpperBodyOnly) == 0x000008, "Wrong alignment on BP_ActionFishingSuccess_C_SetUseUpperBodyOnly");
static_assert(sizeof(BP_ActionFishingSuccess_C_SetUseUpperBodyOnly) == 0x000030, "Wrong size on BP_ActionFishingSuccess_C_SetUseUpperBodyOnly");
static_assert(offsetof(BP_ActionFishingSuccess_C_SetUseUpperBodyOnly, Enable) == 0x000000, "Member 'BP_ActionFishingSuccess_C_SetUseUpperBodyOnly::Enable' has a wrong offset!");
static_assert(offsetof(BP_ActionFishingSuccess_C_SetUseUpperBodyOnly, CallFunc_GetActionCharacter_ReturnValue) == 0x000008, "Member 'BP_ActionFishingSuccess_C_SetUseUpperBodyOnly::CallFunc_GetActionCharacter_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_ActionFishingSuccess_C_SetUseUpperBodyOnly, CallFunc_GetMainMesh_ReturnValue) == 0x000010, "Member 'BP_ActionFishingSuccess_C_SetUseUpperBodyOnly::CallFunc_GetMainMesh_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_ActionFishingSuccess_C_SetUseUpperBodyOnly, CallFunc_GetAnimInstance_ReturnValue) == 0x000018, "Member 'BP_ActionFishingSuccess_C_SetUseUpperBodyOnly::CallFunc_GetAnimInstance_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_ActionFishingSuccess_C_SetUseUpperBodyOnly, K2Node_DynamicCast_AsPal_Anim_Instance) == 0x000020, "Member 'BP_ActionFishingSuccess_C_SetUseUpperBodyOnly::K2Node_DynamicCast_AsPal_Anim_Instance' has a wrong offset!");
static_assert(offsetof(BP_ActionFishingSuccess_C_SetUseUpperBodyOnly, K2Node_DynamicCast_bSuccess) == 0x000028, "Member 'BP_ActionFishingSuccess_C_SetUseUpperBodyOnly::K2Node_DynamicCast_bSuccess' has a wrong offset!");

}

