#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_MonsterAIController_YakushimaBoss002_Head

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "BP_MonsterAIController_RaidBoss_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_MonsterAIController_YakushimaBoss002_Head.BP_MonsterAIController_YakushimaBoss002_Head_C
// 0x0010 (0x05A0 - 0x0590)
class ABP_MonsterAIController_YakushimaBoss002_Head_C final : public ABP_MonsterAIController_RaidBoss_C
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame_BP_MonsterAIController_YakushimaBoss002_Head_C; // 0x0590(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class ABP_MonsterAIController_YakushimaBoss002_C* ParentController;                              // 0x0598(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnTemplate, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_BP_MonsterAIController_YakushimaBoss002_Head(int32 EntryPoint);
	void GetTargetCampID(struct FGuid* CampID);
	void IsReadyBosses(bool* IsStartBattle);
	void SetParentController(class ABP_MonsterAIController_YakushimaBoss002_C* ParentController_0);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_MonsterAIController_YakushimaBoss002_Head_C">();
	}
	static class ABP_MonsterAIController_YakushimaBoss002_Head_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_MonsterAIController_YakushimaBoss002_Head_C>();
	}
};
static_assert(alignof(ABP_MonsterAIController_YakushimaBoss002_Head_C) == 0x000008, "Wrong alignment on ABP_MonsterAIController_YakushimaBoss002_Head_C");
static_assert(sizeof(ABP_MonsterAIController_YakushimaBoss002_Head_C) == 0x0005A0, "Wrong size on ABP_MonsterAIController_YakushimaBoss002_Head_C");
static_assert(offsetof(ABP_MonsterAIController_YakushimaBoss002_Head_C, UberGraphFrame_BP_MonsterAIController_YakushimaBoss002_Head_C) == 0x000590, "Member 'ABP_MonsterAIController_YakushimaBoss002_Head_C::UberGraphFrame_BP_MonsterAIController_YakushimaBoss002_Head_C' has a wrong offset!");
static_assert(offsetof(ABP_MonsterAIController_YakushimaBoss002_Head_C, ParentController) == 0x000598, "Member 'ABP_MonsterAIController_YakushimaBoss002_Head_C::ParentController' has a wrong offset!");

}

