#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_MonoNPCSpawner_Debug

#include "Basic.hpp"

#include "BP_MonoNPCSpawner_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_MonoNPCSpawner_Debug.BP_MonoNPCSpawner_Debug_C
// 0x0000 (0x0480 - 0x0480)
class ABP_MonoNPCSpawner_Debug_C final : public ABP_MonoNPCSpawner_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_MonoNPCSpawner_Debug_C">();
	}
	static class ABP_MonoNPCSpawner_Debug_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_MonoNPCSpawner_Debug_C>();
	}
};
static_assert(alignof(ABP_MonoNPCSpawner_Debug_C) == 0x000008, "Wrong alignment on ABP_MonoNPCSpawner_Debug_C");
static_assert(sizeof(ABP_MonoNPCSpawner_Debug_C) == 0x000480, "Wrong size on ABP_MonoNPCSpawner_Debug_C");

}

