#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_PalBossNPCMarker

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "Pal_structs.hpp"
#include "ST_RideBossAnimation_structs.hpp"
#include "CoreUObject_structs.hpp"


namespace SDK::Params
{

// Function BP_PalBossNPCMarker.BP_PalBossNPCMarker_C.ExecuteUbergraph_BP_PalBossNPCMarker
// 0x03A0 (0x03A0 - 0x0000)
struct BP_PalBossNPCMarker_C_ExecuteUbergraph_BP_PalBossNPCMarker final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TDelegate<void(class FName NotifyName)>       K2Node_CreateDelegate_OutputDelegate;              // 0x0004(0x0010)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	TDelegate<void(class FName NotifyName)>       K2Node_CreateDelegate_OutputDelegate_1;            // 0x0014(0x0010)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class FName                                   K2Node_CustomEvent_NotifyName_16;                  // 0x0024(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FName                                   K2Node_CustomEvent_NotifyName_15;                  // 0x002C(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TDelegate<void(class FName NotifyName)>       K2Node_CreateDelegate_OutputDelegate_2;            // 0x0034(0x0010)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class FName                                   Temp_name_Variable;                                // 0x0044(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TDelegate<void(class FName NotifyName)>       K2Node_CreateDelegate_OutputDelegate_3;            // 0x004C(0x0010)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class FName                                   K2Node_CustomEvent_NotifyName_14;                  // 0x005C(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FName                                   K2Node_CustomEvent_NotifyName_13;                  // 0x0064(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TDelegate<void(class FName NotifyName)>       K2Node_CreateDelegate_OutputDelegate_4;            // 0x006C(0x0010)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class FName                                   K2Node_CustomEvent_NotifyName_12;                  // 0x007C(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TDelegate<void(class FName NotifyName)>       K2Node_CreateDelegate_OutputDelegate_5;            // 0x0084(0x0010)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class FName                                   K2Node_CustomEvent_NotifyName_11;                  // 0x0094(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TDelegate<void(class FName NotifyName)>       K2Node_CreateDelegate_OutputDelegate_6;            // 0x009C(0x0010)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class FName                                   K2Node_CustomEvent_NotifyName_10;                  // 0x00AC(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TDelegate<void(class FName NotifyName)>       K2Node_CreateDelegate_OutputDelegate_7;            // 0x00B4(0x0010)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class FName                                   Temp_name_Variable_1;                              // 0x00C4(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TDelegate<void(class FName NotifyName)>       K2Node_CreateDelegate_OutputDelegate_8;            // 0x00CC(0x0010)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class FName                                   K2Node_CustomEvent_NotifyName_9;                   // 0x00DC(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FName                                   K2Node_CustomEvent_NotifyName_8;                   // 0x00E4(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TDelegate<void(class FName NotifyName)>       K2Node_CreateDelegate_OutputDelegate_9;            // 0x00EC(0x0010)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class FName                                   K2Node_CustomEvent_NotifyName_7;                   // 0x00FC(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TDelegate<void(class FName NotifyName)>       K2Node_CreateDelegate_OutputDelegate_10;           // 0x0104(0x0010)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class FName                                   K2Node_CustomEvent_NotifyName_6;                   // 0x0114(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TDelegate<void(class FName NotifyName)>       K2Node_CreateDelegate_OutputDelegate_11;           // 0x011C(0x0010)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class FName                                   K2Node_CustomEvent_NotifyName_5;                   // 0x012C(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TDelegate<void(class FName NotifyName)>       K2Node_CreateDelegate_OutputDelegate_12;           // 0x0134(0x0010)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class FName                                   Temp_name_Variable_2;                              // 0x0144(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TDelegate<void(class FName NotifyName)>       K2Node_CreateDelegate_OutputDelegate_13;           // 0x014C(0x0010)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class FName                                   K2Node_CustomEvent_NotifyName_4;                   // 0x015C(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FName                                   K2Node_CustomEvent_NotifyName_3;                   // 0x0164(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TDelegate<void(class FName NotifyName)>       K2Node_CreateDelegate_OutputDelegate_14;           // 0x016C(0x0010)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class FName                                   K2Node_CustomEvent_NotifyName_2;                   // 0x017C(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TDelegate<void(class FName NotifyName)>       K2Node_CreateDelegate_OutputDelegate_15;           // 0x0184(0x0010)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class FName                                   K2Node_CustomEvent_NotifyName_1;                   // 0x0194(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TDelegate<void(class FName NotifyName)>       K2Node_CreateDelegate_OutputDelegate_16;           // 0x019C(0x0010)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class FName                                   K2Node_CustomEvent_NotifyName;                     // 0x01AC(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TDelegate<void(class FName NotifyName)>       K2Node_CreateDelegate_OutputDelegate_17;           // 0x01B4(0x0010)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class FName                                   Temp_name_Variable_3;                              // 0x01C4(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_1CC[0x4];                                      // 0x01CC(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UAnimInstance*                          CallFunc_GetAnimInstance_ReturnValue;              // 0x01D0(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class UABP_RidingBoss_C*                      K2Node_DynamicCast_AsABP_Riding_Boss;              // 0x01D8(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x01E0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_1E1[0x7];                                      // 0x01E1(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class AActor*                                 CallFunc_GetOwner_ReturnValue;                     // 0x01E8(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class UPalActionComponent*                    CallFunc_GetComponentByClass_ReturnValue;          // 0x01F0(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	const class UPalActionBase*                   K2Node_CustomEvent_action_1;                       // 0x01F8(0x0008)(ConstParm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class AActor*                                 CallFunc_GetOwner_ReturnValue_1;                   // 0x0200(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class UPalActionComponent*                    CallFunc_GetComponentByClass_ReturnValue_1;        // 0x0208(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	class FName                                   K2Node_CustomEvent_NotifyName_17;                  // 0x0210(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TDelegate<void(class FName NotifyName)>       K2Node_CreateDelegate_OutputDelegate_18;           // 0x0218(0x0010)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class UClass*                                 CallFunc_GetObjectClass_ReturnValue;               // 0x0228(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class UPalActionBase*                         K2Node_CustomEvent_action;                         // 0x0230(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	EPalActionType                                CallFunc_FindEActionFromAction_Eaction;            // 0x0238(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_NotEqual_ByteByte_ReturnValue;            // 0x0239(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_23A[0x6];                                      // 0x023A(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	struct FST_RideBossAnimation                  CallFunc_Map_Find_Value;                           // 0x0240(0x0018)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Map_Find_ReturnValue;                     // 0x0258(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_259[0x7];                                      // 0x0259(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class FString                                 CallFunc_GetDisplayName_ReturnValue;               // 0x0260(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	EPalActionType                                Temp_byte_Variable;                                // 0x0270(0x0001)(ConstParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_271[0x7];                                      // 0x0271(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UPlayMontageCallbackProxy*              CallFunc_CreateProxyObjectForPlayMontage_ReturnValue; // 0x0278(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	TSubclassOf<class UPalActionBase>             CallFunc_Map_Find_Value_1;                         // 0x0280(0x0008)(ZeroConstructor, NoDestructor, UObjectWrapper, HasGetValueTypeHash)
	bool                                          CallFunc_Map_Find_ReturnValue_1;                   // 0x0288(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_EqualEqual_ClassClass_ReturnValue;        // 0x0289(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x028A(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_28B[0x5];                                      // 0x028B(0x0005)(Fixing Size After Last Property [ Dumper-7 ])
	class UPlayMontageCallbackProxy*              CallFunc_CreateProxyObjectForPlayMontage_ReturnValue_1; // 0x0290(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue_1;                    // 0x0298(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_299[0x7];                                      // 0x0299(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class FString                                 CallFunc_GetDisplayName_ReturnValue_1;             // 0x02A0(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue_2;                    // 0x02B0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_2B1[0x7];                                      // 0x02B1(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UPlayMontageCallbackProxy*              CallFunc_CreateProxyObjectForPlayMontage_ReturnValue_2; // 0x02B8(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue_3;                    // 0x02C0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_2C1[0x3];                                      // 0x02C1(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	TDelegate<void()>                             K2Node_CreateDelegate_OutputDelegate_19;           // 0x02C4(0x0010)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	EPalActionType                                CallFunc_FindEActionFromAction_Eaction_1;          // 0x02D4(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_2D5[0x3];                                      // 0x02D5(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	class FName                                   K2Node_CustomEvent_NotifyName_18;                  // 0x02D8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_NotEqual_ByteByte_ReturnValue_1;          // 0x02E0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_2E1[0x7];                                      // 0x02E1(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	struct FST_RideBossAnimation                  CallFunc_Map_Find_Value_2;                         // 0x02E8(0x0018)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Map_Find_ReturnValue_2;                   // 0x0300(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_301[0x3];                                      // 0x0301(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	TDelegate<void(const class UPalActionBase* action)> K2Node_CreateDelegate_OutputDelegate_20;     // 0x0304(0x0010)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_314[0x4];                                      // 0x0314(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UPlayMontageCallbackProxy*              CallFunc_CreateProxyObjectForPlayMontage_ReturnValue_3; // 0x0318(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue_4;                    // 0x0320(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue_5;                    // 0x0321(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_322[0x6];                                      // 0x0322(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	class UAnimInstance*                          CallFunc_GetAnimInstance_ReturnValue_1;            // 0x0328(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Montage_IsPlaying_ReturnValue;            // 0x0330(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_331[0x7];                                      // 0x0331(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UAnimInstance*                          CallFunc_GetAnimInstance_ReturnValue_2;            // 0x0338(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	TDelegate<void(class FName NotifyName)>       K2Node_CreateDelegate_OutputDelegate_21;           // 0x0340(0x0010)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Montage_IsPlaying_ReturnValue_1;          // 0x0350(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	EPalActionType                                K2Node_CustomEvent_EAction_1;                      // 0x0351(0x0001)(ConstParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_352[0x6];                                      // 0x0352(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	struct FST_RideBossAnimation                  CallFunc_Map_Find_Value_3;                         // 0x0358(0x0018)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Map_Find_ReturnValue_3;                   // 0x0370(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue_6;                    // 0x0371(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_372[0x2];                                      // 0x0372(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	class FName                                   K2Node_CustomEvent_NotifyName_19;                  // 0x0374(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	EPalActionType                                K2Node_CustomEvent_EAction;                        // 0x037C(0x0001)(ConstParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_37D[0x3];                                      // 0x037D(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	struct FST_RideBossAnimation                  CallFunc_Map_Find_Value_4;                         // 0x0380(0x0018)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Map_Find_ReturnValue_4;                   // 0x0398(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue_7;                    // 0x0399(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValidClass_ReturnValue;                 // 0x039A(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_PalBossNPCMarker_C_ExecuteUbergraph_BP_PalBossNPCMarker) == 0x000008, "Wrong alignment on BP_PalBossNPCMarker_C_ExecuteUbergraph_BP_PalBossNPCMarker");
static_assert(sizeof(BP_PalBossNPCMarker_C_ExecuteUbergraph_BP_PalBossNPCMarker) == 0x0003A0, "Wrong size on BP_PalBossNPCMarker_C_ExecuteUbergraph_BP_PalBossNPCMarker");
static_assert(offsetof(BP_PalBossNPCMarker_C_ExecuteUbergraph_BP_PalBossNPCMarker, EntryPoint) == 0x000000, "Member 'BP_PalBossNPCMarker_C_ExecuteUbergraph_BP_PalBossNPCMarker::EntryPoint' has a wrong offset!");
static_assert(offsetof(BP_PalBossNPCMarker_C_ExecuteUbergraph_BP_PalBossNPCMarker, K2Node_CreateDelegate_OutputDelegate) == 0x000004, "Member 'BP_PalBossNPCMarker_C_ExecuteUbergraph_BP_PalBossNPCMarker::K2Node_CreateDelegate_OutputDelegate' has a wrong offset!");
static_assert(offsetof(BP_PalBossNPCMarker_C_ExecuteUbergraph_BP_PalBossNPCMarker, K2Node_CreateDelegate_OutputDelegate_1) == 0x000014, "Member 'BP_PalBossNPCMarker_C_ExecuteUbergraph_BP_PalBossNPCMarker::K2Node_CreateDelegate_OutputDelegate_1' has a wrong offset!");
static_assert(offsetof(BP_PalBossNPCMarker_C_ExecuteUbergraph_BP_PalBossNPCMarker, K2Node_CustomEvent_NotifyName_16) == 0x000024, "Member 'BP_PalBossNPCMarker_C_ExecuteUbergraph_BP_PalBossNPCMarker::K2Node_CustomEvent_NotifyName_16' has a wrong offset!");
static_assert(offsetof(BP_PalBossNPCMarker_C_ExecuteUbergraph_BP_PalBossNPCMarker, K2Node_CustomEvent_NotifyName_15) == 0x00002C, "Member 'BP_PalBossNPCMarker_C_ExecuteUbergraph_BP_PalBossNPCMarker::K2Node_CustomEvent_NotifyName_15' has a wrong offset!");
static_assert(offsetof(BP_PalBossNPCMarker_C_ExecuteUbergraph_BP_PalBossNPCMarker, K2Node_CreateDelegate_OutputDelegate_2) == 0x000034, "Member 'BP_PalBossNPCMarker_C_ExecuteUbergraph_BP_PalBossNPCMarker::K2Node_CreateDelegate_OutputDelegate_2' has a wrong offset!");
static_assert(offsetof(BP_PalBossNPCMarker_C_ExecuteUbergraph_BP_PalBossNPCMarker, Temp_name_Variable) == 0x000044, "Member 'BP_PalBossNPCMarker_C_ExecuteUbergraph_BP_PalBossNPCMarker::Temp_name_Variable' has a wrong offset!");
static_assert(offsetof(BP_PalBossNPCMarker_C_ExecuteUbergraph_BP_PalBossNPCMarker, K2Node_CreateDelegate_OutputDelegate_3) == 0x00004C, "Member 'BP_PalBossNPCMarker_C_ExecuteUbergraph_BP_PalBossNPCMarker::K2Node_CreateDelegate_OutputDelegate_3' has a wrong offset!");
static_assert(offsetof(BP_PalBossNPCMarker_C_ExecuteUbergraph_BP_PalBossNPCMarker, K2Node_CustomEvent_NotifyName_14) == 0x00005C, "Member 'BP_PalBossNPCMarker_C_ExecuteUbergraph_BP_PalBossNPCMarker::K2Node_CustomEvent_NotifyName_14' has a wrong offset!");
static_assert(offsetof(BP_PalBossNPCMarker_C_ExecuteUbergraph_BP_PalBossNPCMarker, K2Node_CustomEvent_NotifyName_13) == 0x000064, "Member 'BP_PalBossNPCMarker_C_ExecuteUbergraph_BP_PalBossNPCMarker::K2Node_CustomEvent_NotifyName_13' has a wrong offset!");
static_assert(offsetof(BP_PalBossNPCMarker_C_ExecuteUbergraph_BP_PalBossNPCMarker, K2Node_CreateDelegate_OutputDelegate_4) == 0x00006C, "Member 'BP_PalBossNPCMarker_C_ExecuteUbergraph_BP_PalBossNPCMarker::K2Node_CreateDelegate_OutputDelegate_4' has a wrong offset!");
static_assert(offsetof(BP_PalBossNPCMarker_C_ExecuteUbergraph_BP_PalBossNPCMarker, K2Node_CustomEvent_NotifyName_12) == 0x00007C, "Member 'BP_PalBossNPCMarker_C_ExecuteUbergraph_BP_PalBossNPCMarker::K2Node_CustomEvent_NotifyName_12' has a wrong offset!");
static_assert(offsetof(BP_PalBossNPCMarker_C_ExecuteUbergraph_BP_PalBossNPCMarker, K2Node_CreateDelegate_OutputDelegate_5) == 0x000084, "Member 'BP_PalBossNPCMarker_C_ExecuteUbergraph_BP_PalBossNPCMarker::K2Node_CreateDelegate_OutputDelegate_5' has a wrong offset!");
static_assert(offsetof(BP_PalBossNPCMarker_C_ExecuteUbergraph_BP_PalBossNPCMarker, K2Node_CustomEvent_NotifyName_11) == 0x000094, "Member 'BP_PalBossNPCMarker_C_ExecuteUbergraph_BP_PalBossNPCMarker::K2Node_CustomEvent_NotifyName_11' has a wrong offset!");
static_assert(offsetof(BP_PalBossNPCMarker_C_ExecuteUbergraph_BP_PalBossNPCMarker, K2Node_CreateDelegate_OutputDelegate_6) == 0x00009C, "Member 'BP_PalBossNPCMarker_C_ExecuteUbergraph_BP_PalBossNPCMarker::K2Node_CreateDelegate_OutputDelegate_6' has a wrong offset!");
static_assert(offsetof(BP_PalBossNPCMarker_C_ExecuteUbergraph_BP_PalBossNPCMarker, K2Node_CustomEvent_NotifyName_10) == 0x0000AC, "Member 'BP_PalBossNPCMarker_C_ExecuteUbergraph_BP_PalBossNPCMarker::K2Node_CustomEvent_NotifyName_10' has a wrong offset!");
static_assert(offsetof(BP_PalBossNPCMarker_C_ExecuteUbergraph_BP_PalBossNPCMarker, K2Node_CreateDelegate_OutputDelegate_7) == 0x0000B4, "Member 'BP_PalBossNPCMarker_C_ExecuteUbergraph_BP_PalBossNPCMarker::K2Node_CreateDelegate_OutputDelegate_7' has a wrong offset!");
static_assert(offsetof(BP_PalBossNPCMarker_C_ExecuteUbergraph_BP_PalBossNPCMarker, Temp_name_Variable_1) == 0x0000C4, "Member 'BP_PalBossNPCMarker_C_ExecuteUbergraph_BP_PalBossNPCMarker::Temp_name_Variable_1' has a wrong offset!");
static_assert(offsetof(BP_PalBossNPCMarker_C_ExecuteUbergraph_BP_PalBossNPCMarker, K2Node_CreateDelegate_OutputDelegate_8) == 0x0000CC, "Member 'BP_PalBossNPCMarker_C_ExecuteUbergraph_BP_PalBossNPCMarker::K2Node_CreateDelegate_OutputDelegate_8' has a wrong offset!");
static_assert(offsetof(BP_PalBossNPCMarker_C_ExecuteUbergraph_BP_PalBossNPCMarker, K2Node_CustomEvent_NotifyName_9) == 0x0000DC, "Member 'BP_PalBossNPCMarker_C_ExecuteUbergraph_BP_PalBossNPCMarker::K2Node_CustomEvent_NotifyName_9' has a wrong offset!");
static_assert(offsetof(BP_PalBossNPCMarker_C_ExecuteUbergraph_BP_PalBossNPCMarker, K2Node_CustomEvent_NotifyName_8) == 0x0000E4, "Member 'BP_PalBossNPCMarker_C_ExecuteUbergraph_BP_PalBossNPCMarker::K2Node_CustomEvent_NotifyName_8' has a wrong offset!");
static_assert(offsetof(BP_PalBossNPCMarker_C_ExecuteUbergraph_BP_PalBossNPCMarker, K2Node_CreateDelegate_OutputDelegate_9) == 0x0000EC, "Member 'BP_PalBossNPCMarker_C_ExecuteUbergraph_BP_PalBossNPCMarker::K2Node_CreateDelegate_OutputDelegate_9' has a wrong offset!");
static_assert(offsetof(BP_PalBossNPCMarker_C_ExecuteUbergraph_BP_PalBossNPCMarker, K2Node_CustomEvent_NotifyName_7) == 0x0000FC, "Member 'BP_PalBossNPCMarker_C_ExecuteUbergraph_BP_PalBossNPCMarker::K2Node_CustomEvent_NotifyName_7' has a wrong offset!");
static_assert(offsetof(BP_PalBossNPCMarker_C_ExecuteUbergraph_BP_PalBossNPCMarker, K2Node_CreateDelegate_OutputDelegate_10) == 0x000104, "Member 'BP_PalBossNPCMarker_C_ExecuteUbergraph_BP_PalBossNPCMarker::K2Node_CreateDelegate_OutputDelegate_10' has a wrong offset!");
static_assert(offsetof(BP_PalBossNPCMarker_C_ExecuteUbergraph_BP_PalBossNPCMarker, K2Node_CustomEvent_NotifyName_6) == 0x000114, "Member 'BP_PalBossNPCMarker_C_ExecuteUbergraph_BP_PalBossNPCMarker::K2Node_CustomEvent_NotifyName_6' has a wrong offset!");
static_assert(offsetof(BP_PalBossNPCMarker_C_ExecuteUbergraph_BP_PalBossNPCMarker, K2Node_CreateDelegate_OutputDelegate_11) == 0x00011C, "Member 'BP_PalBossNPCMarker_C_ExecuteUbergraph_BP_PalBossNPCMarker::K2Node_CreateDelegate_OutputDelegate_11' has a wrong offset!");
static_assert(offsetof(BP_PalBossNPCMarker_C_ExecuteUbergraph_BP_PalBossNPCMarker, K2Node_CustomEvent_NotifyName_5) == 0x00012C, "Member 'BP_PalBossNPCMarker_C_ExecuteUbergraph_BP_PalBossNPCMarker::K2Node_CustomEvent_NotifyName_5' has a wrong offset!");
static_assert(offsetof(BP_PalBossNPCMarker_C_ExecuteUbergraph_BP_PalBossNPCMarker, K2Node_CreateDelegate_OutputDelegate_12) == 0x000134, "Member 'BP_PalBossNPCMarker_C_ExecuteUbergraph_BP_PalBossNPCMarker::K2Node_CreateDelegate_OutputDelegate_12' has a wrong offset!");
static_assert(offsetof(BP_PalBossNPCMarker_C_ExecuteUbergraph_BP_PalBossNPCMarker, Temp_name_Variable_2) == 0x000144, "Member 'BP_PalBossNPCMarker_C_ExecuteUbergraph_BP_PalBossNPCMarker::Temp_name_Variable_2' has a wrong offset!");
static_assert(offsetof(BP_PalBossNPCMarker_C_ExecuteUbergraph_BP_PalBossNPCMarker, K2Node_CreateDelegate_OutputDelegate_13) == 0x00014C, "Member 'BP_PalBossNPCMarker_C_ExecuteUbergraph_BP_PalBossNPCMarker::K2Node_CreateDelegate_OutputDelegate_13' has a wrong offset!");
static_assert(offsetof(BP_PalBossNPCMarker_C_ExecuteUbergraph_BP_PalBossNPCMarker, K2Node_CustomEvent_NotifyName_4) == 0x00015C, "Member 'BP_PalBossNPCMarker_C_ExecuteUbergraph_BP_PalBossNPCMarker::K2Node_CustomEvent_NotifyName_4' has a wrong offset!");
static_assert(offsetof(BP_PalBossNPCMarker_C_ExecuteUbergraph_BP_PalBossNPCMarker, K2Node_CustomEvent_NotifyName_3) == 0x000164, "Member 'BP_PalBossNPCMarker_C_ExecuteUbergraph_BP_PalBossNPCMarker::K2Node_CustomEvent_NotifyName_3' has a wrong offset!");
static_assert(offsetof(BP_PalBossNPCMarker_C_ExecuteUbergraph_BP_PalBossNPCMarker, K2Node_CreateDelegate_OutputDelegate_14) == 0x00016C, "Member 'BP_PalBossNPCMarker_C_ExecuteUbergraph_BP_PalBossNPCMarker::K2Node_CreateDelegate_OutputDelegate_14' has a wrong offset!");
static_assert(offsetof(BP_PalBossNPCMarker_C_ExecuteUbergraph_BP_PalBossNPCMarker, K2Node_CustomEvent_NotifyName_2) == 0x00017C, "Member 'BP_PalBossNPCMarker_C_ExecuteUbergraph_BP_PalBossNPCMarker::K2Node_CustomEvent_NotifyName_2' has a wrong offset!");
static_assert(offsetof(BP_PalBossNPCMarker_C_ExecuteUbergraph_BP_PalBossNPCMarker, K2Node_CreateDelegate_OutputDelegate_15) == 0x000184, "Member 'BP_PalBossNPCMarker_C_ExecuteUbergraph_BP_PalBossNPCMarker::K2Node_CreateDelegate_OutputDelegate_15' has a wrong offset!");
static_assert(offsetof(BP_PalBossNPCMarker_C_ExecuteUbergraph_BP_PalBossNPCMarker, K2Node_CustomEvent_NotifyName_1) == 0x000194, "Member 'BP_PalBossNPCMarker_C_ExecuteUbergraph_BP_PalBossNPCMarker::K2Node_CustomEvent_NotifyName_1' has a wrong offset!");
static_assert(offsetof(BP_PalBossNPCMarker_C_ExecuteUbergraph_BP_PalBossNPCMarker, K2Node_CreateDelegate_OutputDelegate_16) == 0x00019C, "Member 'BP_PalBossNPCMarker_C_ExecuteUbergraph_BP_PalBossNPCMarker::K2Node_CreateDelegate_OutputDelegate_16' has a wrong offset!");
static_assert(offsetof(BP_PalBossNPCMarker_C_ExecuteUbergraph_BP_PalBossNPCMarker, K2Node_CustomEvent_NotifyName) == 0x0001AC, "Member 'BP_PalBossNPCMarker_C_ExecuteUbergraph_BP_PalBossNPCMarker::K2Node_CustomEvent_NotifyName' has a wrong offset!");
static_assert(offsetof(BP_PalBossNPCMarker_C_ExecuteUbergraph_BP_PalBossNPCMarker, K2Node_CreateDelegate_OutputDelegate_17) == 0x0001B4, "Member 'BP_PalBossNPCMarker_C_ExecuteUbergraph_BP_PalBossNPCMarker::K2Node_CreateDelegate_OutputDelegate_17' has a wrong offset!");
static_assert(offsetof(BP_PalBossNPCMarker_C_ExecuteUbergraph_BP_PalBossNPCMarker, Temp_name_Variable_3) == 0x0001C4, "Member 'BP_PalBossNPCMarker_C_ExecuteUbergraph_BP_PalBossNPCMarker::Temp_name_Variable_3' has a wrong offset!");
static_assert(offsetof(BP_PalBossNPCMarker_C_ExecuteUbergraph_BP_PalBossNPCMarker, CallFunc_GetAnimInstance_ReturnValue) == 0x0001D0, "Member 'BP_PalBossNPCMarker_C_ExecuteUbergraph_BP_PalBossNPCMarker::CallFunc_GetAnimInstance_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_PalBossNPCMarker_C_ExecuteUbergraph_BP_PalBossNPCMarker, K2Node_DynamicCast_AsABP_Riding_Boss) == 0x0001D8, "Member 'BP_PalBossNPCMarker_C_ExecuteUbergraph_BP_PalBossNPCMarker::K2Node_DynamicCast_AsABP_Riding_Boss' has a wrong offset!");
static_assert(offsetof(BP_PalBossNPCMarker_C_ExecuteUbergraph_BP_PalBossNPCMarker, K2Node_DynamicCast_bSuccess) == 0x0001E0, "Member 'BP_PalBossNPCMarker_C_ExecuteUbergraph_BP_PalBossNPCMarker::K2Node_DynamicCast_bSuccess' has a wrong offset!");
static_assert(offsetof(BP_PalBossNPCMarker_C_ExecuteUbergraph_BP_PalBossNPCMarker, CallFunc_GetOwner_ReturnValue) == 0x0001E8, "Member 'BP_PalBossNPCMarker_C_ExecuteUbergraph_BP_PalBossNPCMarker::CallFunc_GetOwner_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_PalBossNPCMarker_C_ExecuteUbergraph_BP_PalBossNPCMarker, CallFunc_GetComponentByClass_ReturnValue) == 0x0001F0, "Member 'BP_PalBossNPCMarker_C_ExecuteUbergraph_BP_PalBossNPCMarker::CallFunc_GetComponentByClass_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_PalBossNPCMarker_C_ExecuteUbergraph_BP_PalBossNPCMarker, K2Node_CustomEvent_action_1) == 0x0001F8, "Member 'BP_PalBossNPCMarker_C_ExecuteUbergraph_BP_PalBossNPCMarker::K2Node_CustomEvent_action_1' has a wrong offset!");
static_assert(offsetof(BP_PalBossNPCMarker_C_ExecuteUbergraph_BP_PalBossNPCMarker, CallFunc_GetOwner_ReturnValue_1) == 0x000200, "Member 'BP_PalBossNPCMarker_C_ExecuteUbergraph_BP_PalBossNPCMarker::CallFunc_GetOwner_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_PalBossNPCMarker_C_ExecuteUbergraph_BP_PalBossNPCMarker, CallFunc_GetComponentByClass_ReturnValue_1) == 0x000208, "Member 'BP_PalBossNPCMarker_C_ExecuteUbergraph_BP_PalBossNPCMarker::CallFunc_GetComponentByClass_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_PalBossNPCMarker_C_ExecuteUbergraph_BP_PalBossNPCMarker, K2Node_CustomEvent_NotifyName_17) == 0x000210, "Member 'BP_PalBossNPCMarker_C_ExecuteUbergraph_BP_PalBossNPCMarker::K2Node_CustomEvent_NotifyName_17' has a wrong offset!");
static_assert(offsetof(BP_PalBossNPCMarker_C_ExecuteUbergraph_BP_PalBossNPCMarker, K2Node_CreateDelegate_OutputDelegate_18) == 0x000218, "Member 'BP_PalBossNPCMarker_C_ExecuteUbergraph_BP_PalBossNPCMarker::K2Node_CreateDelegate_OutputDelegate_18' has a wrong offset!");
static_assert(offsetof(BP_PalBossNPCMarker_C_ExecuteUbergraph_BP_PalBossNPCMarker, CallFunc_GetObjectClass_ReturnValue) == 0x000228, "Member 'BP_PalBossNPCMarker_C_ExecuteUbergraph_BP_PalBossNPCMarker::CallFunc_GetObjectClass_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_PalBossNPCMarker_C_ExecuteUbergraph_BP_PalBossNPCMarker, K2Node_CustomEvent_action) == 0x000230, "Member 'BP_PalBossNPCMarker_C_ExecuteUbergraph_BP_PalBossNPCMarker::K2Node_CustomEvent_action' has a wrong offset!");
static_assert(offsetof(BP_PalBossNPCMarker_C_ExecuteUbergraph_BP_PalBossNPCMarker, CallFunc_FindEActionFromAction_Eaction) == 0x000238, "Member 'BP_PalBossNPCMarker_C_ExecuteUbergraph_BP_PalBossNPCMarker::CallFunc_FindEActionFromAction_Eaction' has a wrong offset!");
static_assert(offsetof(BP_PalBossNPCMarker_C_ExecuteUbergraph_BP_PalBossNPCMarker, CallFunc_NotEqual_ByteByte_ReturnValue) == 0x000239, "Member 'BP_PalBossNPCMarker_C_ExecuteUbergraph_BP_PalBossNPCMarker::CallFunc_NotEqual_ByteByte_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_PalBossNPCMarker_C_ExecuteUbergraph_BP_PalBossNPCMarker, CallFunc_Map_Find_Value) == 0x000240, "Member 'BP_PalBossNPCMarker_C_ExecuteUbergraph_BP_PalBossNPCMarker::CallFunc_Map_Find_Value' has a wrong offset!");
static_assert(offsetof(BP_PalBossNPCMarker_C_ExecuteUbergraph_BP_PalBossNPCMarker, CallFunc_Map_Find_ReturnValue) == 0x000258, "Member 'BP_PalBossNPCMarker_C_ExecuteUbergraph_BP_PalBossNPCMarker::CallFunc_Map_Find_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_PalBossNPCMarker_C_ExecuteUbergraph_BP_PalBossNPCMarker, CallFunc_GetDisplayName_ReturnValue) == 0x000260, "Member 'BP_PalBossNPCMarker_C_ExecuteUbergraph_BP_PalBossNPCMarker::CallFunc_GetDisplayName_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_PalBossNPCMarker_C_ExecuteUbergraph_BP_PalBossNPCMarker, Temp_byte_Variable) == 0x000270, "Member 'BP_PalBossNPCMarker_C_ExecuteUbergraph_BP_PalBossNPCMarker::Temp_byte_Variable' has a wrong offset!");
static_assert(offsetof(BP_PalBossNPCMarker_C_ExecuteUbergraph_BP_PalBossNPCMarker, CallFunc_CreateProxyObjectForPlayMontage_ReturnValue) == 0x000278, "Member 'BP_PalBossNPCMarker_C_ExecuteUbergraph_BP_PalBossNPCMarker::CallFunc_CreateProxyObjectForPlayMontage_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_PalBossNPCMarker_C_ExecuteUbergraph_BP_PalBossNPCMarker, CallFunc_Map_Find_Value_1) == 0x000280, "Member 'BP_PalBossNPCMarker_C_ExecuteUbergraph_BP_PalBossNPCMarker::CallFunc_Map_Find_Value_1' has a wrong offset!");
static_assert(offsetof(BP_PalBossNPCMarker_C_ExecuteUbergraph_BP_PalBossNPCMarker, CallFunc_Map_Find_ReturnValue_1) == 0x000288, "Member 'BP_PalBossNPCMarker_C_ExecuteUbergraph_BP_PalBossNPCMarker::CallFunc_Map_Find_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_PalBossNPCMarker_C_ExecuteUbergraph_BP_PalBossNPCMarker, CallFunc_EqualEqual_ClassClass_ReturnValue) == 0x000289, "Member 'BP_PalBossNPCMarker_C_ExecuteUbergraph_BP_PalBossNPCMarker::CallFunc_EqualEqual_ClassClass_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_PalBossNPCMarker_C_ExecuteUbergraph_BP_PalBossNPCMarker, CallFunc_IsValid_ReturnValue) == 0x00028A, "Member 'BP_PalBossNPCMarker_C_ExecuteUbergraph_BP_PalBossNPCMarker::CallFunc_IsValid_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_PalBossNPCMarker_C_ExecuteUbergraph_BP_PalBossNPCMarker, CallFunc_CreateProxyObjectForPlayMontage_ReturnValue_1) == 0x000290, "Member 'BP_PalBossNPCMarker_C_ExecuteUbergraph_BP_PalBossNPCMarker::CallFunc_CreateProxyObjectForPlayMontage_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_PalBossNPCMarker_C_ExecuteUbergraph_BP_PalBossNPCMarker, CallFunc_IsValid_ReturnValue_1) == 0x000298, "Member 'BP_PalBossNPCMarker_C_ExecuteUbergraph_BP_PalBossNPCMarker::CallFunc_IsValid_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_PalBossNPCMarker_C_ExecuteUbergraph_BP_PalBossNPCMarker, CallFunc_GetDisplayName_ReturnValue_1) == 0x0002A0, "Member 'BP_PalBossNPCMarker_C_ExecuteUbergraph_BP_PalBossNPCMarker::CallFunc_GetDisplayName_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_PalBossNPCMarker_C_ExecuteUbergraph_BP_PalBossNPCMarker, CallFunc_IsValid_ReturnValue_2) == 0x0002B0, "Member 'BP_PalBossNPCMarker_C_ExecuteUbergraph_BP_PalBossNPCMarker::CallFunc_IsValid_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(BP_PalBossNPCMarker_C_ExecuteUbergraph_BP_PalBossNPCMarker, CallFunc_CreateProxyObjectForPlayMontage_ReturnValue_2) == 0x0002B8, "Member 'BP_PalBossNPCMarker_C_ExecuteUbergraph_BP_PalBossNPCMarker::CallFunc_CreateProxyObjectForPlayMontage_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(BP_PalBossNPCMarker_C_ExecuteUbergraph_BP_PalBossNPCMarker, CallFunc_IsValid_ReturnValue_3) == 0x0002C0, "Member 'BP_PalBossNPCMarker_C_ExecuteUbergraph_BP_PalBossNPCMarker::CallFunc_IsValid_ReturnValue_3' has a wrong offset!");
static_assert(offsetof(BP_PalBossNPCMarker_C_ExecuteUbergraph_BP_PalBossNPCMarker, K2Node_CreateDelegate_OutputDelegate_19) == 0x0002C4, "Member 'BP_PalBossNPCMarker_C_ExecuteUbergraph_BP_PalBossNPCMarker::K2Node_CreateDelegate_OutputDelegate_19' has a wrong offset!");
static_assert(offsetof(BP_PalBossNPCMarker_C_ExecuteUbergraph_BP_PalBossNPCMarker, CallFunc_FindEActionFromAction_Eaction_1) == 0x0002D4, "Member 'BP_PalBossNPCMarker_C_ExecuteUbergraph_BP_PalBossNPCMarker::CallFunc_FindEActionFromAction_Eaction_1' has a wrong offset!");
static_assert(offsetof(BP_PalBossNPCMarker_C_ExecuteUbergraph_BP_PalBossNPCMarker, K2Node_CustomEvent_NotifyName_18) == 0x0002D8, "Member 'BP_PalBossNPCMarker_C_ExecuteUbergraph_BP_PalBossNPCMarker::K2Node_CustomEvent_NotifyName_18' has a wrong offset!");
static_assert(offsetof(BP_PalBossNPCMarker_C_ExecuteUbergraph_BP_PalBossNPCMarker, CallFunc_NotEqual_ByteByte_ReturnValue_1) == 0x0002E0, "Member 'BP_PalBossNPCMarker_C_ExecuteUbergraph_BP_PalBossNPCMarker::CallFunc_NotEqual_ByteByte_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_PalBossNPCMarker_C_ExecuteUbergraph_BP_PalBossNPCMarker, CallFunc_Map_Find_Value_2) == 0x0002E8, "Member 'BP_PalBossNPCMarker_C_ExecuteUbergraph_BP_PalBossNPCMarker::CallFunc_Map_Find_Value_2' has a wrong offset!");
static_assert(offsetof(BP_PalBossNPCMarker_C_ExecuteUbergraph_BP_PalBossNPCMarker, CallFunc_Map_Find_ReturnValue_2) == 0x000300, "Member 'BP_PalBossNPCMarker_C_ExecuteUbergraph_BP_PalBossNPCMarker::CallFunc_Map_Find_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(BP_PalBossNPCMarker_C_ExecuteUbergraph_BP_PalBossNPCMarker, K2Node_CreateDelegate_OutputDelegate_20) == 0x000304, "Member 'BP_PalBossNPCMarker_C_ExecuteUbergraph_BP_PalBossNPCMarker::K2Node_CreateDelegate_OutputDelegate_20' has a wrong offset!");
static_assert(offsetof(BP_PalBossNPCMarker_C_ExecuteUbergraph_BP_PalBossNPCMarker, CallFunc_CreateProxyObjectForPlayMontage_ReturnValue_3) == 0x000318, "Member 'BP_PalBossNPCMarker_C_ExecuteUbergraph_BP_PalBossNPCMarker::CallFunc_CreateProxyObjectForPlayMontage_ReturnValue_3' has a wrong offset!");
static_assert(offsetof(BP_PalBossNPCMarker_C_ExecuteUbergraph_BP_PalBossNPCMarker, CallFunc_IsValid_ReturnValue_4) == 0x000320, "Member 'BP_PalBossNPCMarker_C_ExecuteUbergraph_BP_PalBossNPCMarker::CallFunc_IsValid_ReturnValue_4' has a wrong offset!");
static_assert(offsetof(BP_PalBossNPCMarker_C_ExecuteUbergraph_BP_PalBossNPCMarker, CallFunc_IsValid_ReturnValue_5) == 0x000321, "Member 'BP_PalBossNPCMarker_C_ExecuteUbergraph_BP_PalBossNPCMarker::CallFunc_IsValid_ReturnValue_5' has a wrong offset!");
static_assert(offsetof(BP_PalBossNPCMarker_C_ExecuteUbergraph_BP_PalBossNPCMarker, CallFunc_GetAnimInstance_ReturnValue_1) == 0x000328, "Member 'BP_PalBossNPCMarker_C_ExecuteUbergraph_BP_PalBossNPCMarker::CallFunc_GetAnimInstance_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_PalBossNPCMarker_C_ExecuteUbergraph_BP_PalBossNPCMarker, CallFunc_Montage_IsPlaying_ReturnValue) == 0x000330, "Member 'BP_PalBossNPCMarker_C_ExecuteUbergraph_BP_PalBossNPCMarker::CallFunc_Montage_IsPlaying_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_PalBossNPCMarker_C_ExecuteUbergraph_BP_PalBossNPCMarker, CallFunc_GetAnimInstance_ReturnValue_2) == 0x000338, "Member 'BP_PalBossNPCMarker_C_ExecuteUbergraph_BP_PalBossNPCMarker::CallFunc_GetAnimInstance_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(BP_PalBossNPCMarker_C_ExecuteUbergraph_BP_PalBossNPCMarker, K2Node_CreateDelegate_OutputDelegate_21) == 0x000340, "Member 'BP_PalBossNPCMarker_C_ExecuteUbergraph_BP_PalBossNPCMarker::K2Node_CreateDelegate_OutputDelegate_21' has a wrong offset!");
static_assert(offsetof(BP_PalBossNPCMarker_C_ExecuteUbergraph_BP_PalBossNPCMarker, CallFunc_Montage_IsPlaying_ReturnValue_1) == 0x000350, "Member 'BP_PalBossNPCMarker_C_ExecuteUbergraph_BP_PalBossNPCMarker::CallFunc_Montage_IsPlaying_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_PalBossNPCMarker_C_ExecuteUbergraph_BP_PalBossNPCMarker, K2Node_CustomEvent_EAction_1) == 0x000351, "Member 'BP_PalBossNPCMarker_C_ExecuteUbergraph_BP_PalBossNPCMarker::K2Node_CustomEvent_EAction_1' has a wrong offset!");
static_assert(offsetof(BP_PalBossNPCMarker_C_ExecuteUbergraph_BP_PalBossNPCMarker, CallFunc_Map_Find_Value_3) == 0x000358, "Member 'BP_PalBossNPCMarker_C_ExecuteUbergraph_BP_PalBossNPCMarker::CallFunc_Map_Find_Value_3' has a wrong offset!");
static_assert(offsetof(BP_PalBossNPCMarker_C_ExecuteUbergraph_BP_PalBossNPCMarker, CallFunc_Map_Find_ReturnValue_3) == 0x000370, "Member 'BP_PalBossNPCMarker_C_ExecuteUbergraph_BP_PalBossNPCMarker::CallFunc_Map_Find_ReturnValue_3' has a wrong offset!");
static_assert(offsetof(BP_PalBossNPCMarker_C_ExecuteUbergraph_BP_PalBossNPCMarker, CallFunc_IsValid_ReturnValue_6) == 0x000371, "Member 'BP_PalBossNPCMarker_C_ExecuteUbergraph_BP_PalBossNPCMarker::CallFunc_IsValid_ReturnValue_6' has a wrong offset!");
static_assert(offsetof(BP_PalBossNPCMarker_C_ExecuteUbergraph_BP_PalBossNPCMarker, K2Node_CustomEvent_NotifyName_19) == 0x000374, "Member 'BP_PalBossNPCMarker_C_ExecuteUbergraph_BP_PalBossNPCMarker::K2Node_CustomEvent_NotifyName_19' has a wrong offset!");
static_assert(offsetof(BP_PalBossNPCMarker_C_ExecuteUbergraph_BP_PalBossNPCMarker, K2Node_CustomEvent_EAction) == 0x00037C, "Member 'BP_PalBossNPCMarker_C_ExecuteUbergraph_BP_PalBossNPCMarker::K2Node_CustomEvent_EAction' has a wrong offset!");
static_assert(offsetof(BP_PalBossNPCMarker_C_ExecuteUbergraph_BP_PalBossNPCMarker, CallFunc_Map_Find_Value_4) == 0x000380, "Member 'BP_PalBossNPCMarker_C_ExecuteUbergraph_BP_PalBossNPCMarker::CallFunc_Map_Find_Value_4' has a wrong offset!");
static_assert(offsetof(BP_PalBossNPCMarker_C_ExecuteUbergraph_BP_PalBossNPCMarker, CallFunc_Map_Find_ReturnValue_4) == 0x000398, "Member 'BP_PalBossNPCMarker_C_ExecuteUbergraph_BP_PalBossNPCMarker::CallFunc_Map_Find_ReturnValue_4' has a wrong offset!");
static_assert(offsetof(BP_PalBossNPCMarker_C_ExecuteUbergraph_BP_PalBossNPCMarker, CallFunc_IsValid_ReturnValue_7) == 0x000399, "Member 'BP_PalBossNPCMarker_C_ExecuteUbergraph_BP_PalBossNPCMarker::CallFunc_IsValid_ReturnValue_7' has a wrong offset!");
static_assert(offsetof(BP_PalBossNPCMarker_C_ExecuteUbergraph_BP_PalBossNPCMarker, CallFunc_IsValidClass_ReturnValue) == 0x00039A, "Member 'BP_PalBossNPCMarker_C_ExecuteUbergraph_BP_PalBossNPCMarker::CallFunc_IsValidClass_ReturnValue' has a wrong offset!");

// Function BP_PalBossNPCMarker.BP_PalBossNPCMarker_C.FindEActionFromAction
// 0x0108 (0x0108 - 0x0000)
struct BP_PalBossNPCMarker_C_FindEActionFromAction final
{
public:
	const class UObject*                          AnyAction;                                         // 0x0000(0x0008)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	EPalActionType                                Eaction_0;                                         // 0x0008(0x0001)(Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	EPalActionType                                NewLocalVar_0;                                     // 0x0009(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_A[0x6];                                        // 0x000A(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	TMap<EPalActionType, TSubclassOf<class UPalActionBase>> ActionMap;                               // 0x0010(0x0050)(Edit, BlueprintVisible)
	int32                                         Temp_int_Array_Index_Variable;                     // 0x0060(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Loop_Counter_Variable;                    // 0x0064(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Add_IntInt_ReturnValue;                   // 0x0068(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_6C[0x4];                                       // 0x006C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UClass*                                 CallFunc_GetObjectClass_ReturnValue;               // 0x0070(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	TMap<EPalActionType, TSubclassOf<class UPalActionBase>> K2Node_MakeVariable_MakeVariableOutput;  // 0x0078(0x0050)()
	class AActor*                                 CallFunc_GetOwner_ReturnValue;                     // 0x00C8(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class UPalActionComponent*                    CallFunc_GetComponentByClass_ReturnValue;          // 0x00D0(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	TArray<EPalActionType>                        CallFunc_Map_Keys_Keys;                            // 0x00D8(0x0010)(ReferenceParm)
	EPalActionType                                CallFunc_Array_Get_Item;                           // 0x00E8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_E9[0x3];                                       // 0x00E9(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_Array_Length_ReturnValue;                 // 0x00EC(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Less_IntInt_ReturnValue;                  // 0x00F0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_F1[0x7];                                       // 0x00F1(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	TSubclassOf<class UPalActionBase>             CallFunc_Map_Find_Value;                           // 0x00F8(0x0008)(ZeroConstructor, NoDestructor, UObjectWrapper, HasGetValueTypeHash)
	bool                                          CallFunc_Map_Find_ReturnValue;                     // 0x0100(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_EqualEqual_ClassClass_ReturnValue;        // 0x0101(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_ClassIsChildOf_ReturnValue;               // 0x0102(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_PalBossNPCMarker_C_FindEActionFromAction) == 0x000008, "Wrong alignment on BP_PalBossNPCMarker_C_FindEActionFromAction");
static_assert(sizeof(BP_PalBossNPCMarker_C_FindEActionFromAction) == 0x000108, "Wrong size on BP_PalBossNPCMarker_C_FindEActionFromAction");
static_assert(offsetof(BP_PalBossNPCMarker_C_FindEActionFromAction, AnyAction) == 0x000000, "Member 'BP_PalBossNPCMarker_C_FindEActionFromAction::AnyAction' has a wrong offset!");
static_assert(offsetof(BP_PalBossNPCMarker_C_FindEActionFromAction, Eaction_0) == 0x000008, "Member 'BP_PalBossNPCMarker_C_FindEActionFromAction::Eaction_0' has a wrong offset!");
static_assert(offsetof(BP_PalBossNPCMarker_C_FindEActionFromAction, NewLocalVar_0) == 0x000009, "Member 'BP_PalBossNPCMarker_C_FindEActionFromAction::NewLocalVar_0' has a wrong offset!");
static_assert(offsetof(BP_PalBossNPCMarker_C_FindEActionFromAction, ActionMap) == 0x000010, "Member 'BP_PalBossNPCMarker_C_FindEActionFromAction::ActionMap' has a wrong offset!");
static_assert(offsetof(BP_PalBossNPCMarker_C_FindEActionFromAction, Temp_int_Array_Index_Variable) == 0x000060, "Member 'BP_PalBossNPCMarker_C_FindEActionFromAction::Temp_int_Array_Index_Variable' has a wrong offset!");
static_assert(offsetof(BP_PalBossNPCMarker_C_FindEActionFromAction, Temp_int_Loop_Counter_Variable) == 0x000064, "Member 'BP_PalBossNPCMarker_C_FindEActionFromAction::Temp_int_Loop_Counter_Variable' has a wrong offset!");
static_assert(offsetof(BP_PalBossNPCMarker_C_FindEActionFromAction, CallFunc_Add_IntInt_ReturnValue) == 0x000068, "Member 'BP_PalBossNPCMarker_C_FindEActionFromAction::CallFunc_Add_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_PalBossNPCMarker_C_FindEActionFromAction, CallFunc_GetObjectClass_ReturnValue) == 0x000070, "Member 'BP_PalBossNPCMarker_C_FindEActionFromAction::CallFunc_GetObjectClass_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_PalBossNPCMarker_C_FindEActionFromAction, K2Node_MakeVariable_MakeVariableOutput) == 0x000078, "Member 'BP_PalBossNPCMarker_C_FindEActionFromAction::K2Node_MakeVariable_MakeVariableOutput' has a wrong offset!");
static_assert(offsetof(BP_PalBossNPCMarker_C_FindEActionFromAction, CallFunc_GetOwner_ReturnValue) == 0x0000C8, "Member 'BP_PalBossNPCMarker_C_FindEActionFromAction::CallFunc_GetOwner_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_PalBossNPCMarker_C_FindEActionFromAction, CallFunc_GetComponentByClass_ReturnValue) == 0x0000D0, "Member 'BP_PalBossNPCMarker_C_FindEActionFromAction::CallFunc_GetComponentByClass_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_PalBossNPCMarker_C_FindEActionFromAction, CallFunc_Map_Keys_Keys) == 0x0000D8, "Member 'BP_PalBossNPCMarker_C_FindEActionFromAction::CallFunc_Map_Keys_Keys' has a wrong offset!");
static_assert(offsetof(BP_PalBossNPCMarker_C_FindEActionFromAction, CallFunc_Array_Get_Item) == 0x0000E8, "Member 'BP_PalBossNPCMarker_C_FindEActionFromAction::CallFunc_Array_Get_Item' has a wrong offset!");
static_assert(offsetof(BP_PalBossNPCMarker_C_FindEActionFromAction, CallFunc_Array_Length_ReturnValue) == 0x0000EC, "Member 'BP_PalBossNPCMarker_C_FindEActionFromAction::CallFunc_Array_Length_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_PalBossNPCMarker_C_FindEActionFromAction, CallFunc_Less_IntInt_ReturnValue) == 0x0000F0, "Member 'BP_PalBossNPCMarker_C_FindEActionFromAction::CallFunc_Less_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_PalBossNPCMarker_C_FindEActionFromAction, CallFunc_Map_Find_Value) == 0x0000F8, "Member 'BP_PalBossNPCMarker_C_FindEActionFromAction::CallFunc_Map_Find_Value' has a wrong offset!");
static_assert(offsetof(BP_PalBossNPCMarker_C_FindEActionFromAction, CallFunc_Map_Find_ReturnValue) == 0x000100, "Member 'BP_PalBossNPCMarker_C_FindEActionFromAction::CallFunc_Map_Find_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_PalBossNPCMarker_C_FindEActionFromAction, CallFunc_EqualEqual_ClassClass_ReturnValue) == 0x000101, "Member 'BP_PalBossNPCMarker_C_FindEActionFromAction::CallFunc_EqualEqual_ClassClass_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_PalBossNPCMarker_C_FindEActionFromAction, CallFunc_ClassIsChildOf_ReturnValue) == 0x000102, "Member 'BP_PalBossNPCMarker_C_FindEActionFromAction::CallFunc_ClassIsChildOf_ReturnValue' has a wrong offset!");

// Function BP_PalBossNPCMarker.BP_PalBossNPCMarker_C.ForceEndAnimWithEAction
// 0x0001 (0x0001 - 0x0000)
struct BP_PalBossNPCMarker_C_ForceEndAnimWithEAction final
{
public:
	EPalActionType                                Eaction_0;                                         // 0x0000(0x0001)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ZeroConstructor, ReferenceParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_PalBossNPCMarker_C_ForceEndAnimWithEAction) == 0x000001, "Wrong alignment on BP_PalBossNPCMarker_C_ForceEndAnimWithEAction");
static_assert(sizeof(BP_PalBossNPCMarker_C_ForceEndAnimWithEAction) == 0x000001, "Wrong size on BP_PalBossNPCMarker_C_ForceEndAnimWithEAction");
static_assert(offsetof(BP_PalBossNPCMarker_C_ForceEndAnimWithEAction, Eaction_0) == 0x000000, "Member 'BP_PalBossNPCMarker_C_ForceEndAnimWithEAction::Eaction_0' has a wrong offset!");

// Function BP_PalBossNPCMarker.BP_PalBossNPCMarker_C.ForcePlayAnimWithEAction
// 0x0001 (0x0001 - 0x0000)
struct BP_PalBossNPCMarker_C_ForcePlayAnimWithEAction final
{
public:
	EPalActionType                                Eaction_0;                                         // 0x0000(0x0001)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ZeroConstructor, ReferenceParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_PalBossNPCMarker_C_ForcePlayAnimWithEAction) == 0x000001, "Wrong alignment on BP_PalBossNPCMarker_C_ForcePlayAnimWithEAction");
static_assert(sizeof(BP_PalBossNPCMarker_C_ForcePlayAnimWithEAction) == 0x000001, "Wrong size on BP_PalBossNPCMarker_C_ForcePlayAnimWithEAction");
static_assert(offsetof(BP_PalBossNPCMarker_C_ForcePlayAnimWithEAction, Eaction_0) == 0x000000, "Member 'BP_PalBossNPCMarker_C_ForcePlayAnimWithEAction::Eaction_0' has a wrong offset!");

// Function BP_PalBossNPCMarker.BP_PalBossNPCMarker_C.IsAbsoluteRotation
// 0x0008 (0x0008 - 0x0000)
struct BP_PalBossNPCMarker_C_IsAbsoluteRotation final
{
public:
	struct FTimerHandle                           CallFunc_K2_SetTimer_ReturnValue;                  // 0x0000(0x0008)(NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_PalBossNPCMarker_C_IsAbsoluteRotation) == 0x000008, "Wrong alignment on BP_PalBossNPCMarker_C_IsAbsoluteRotation");
static_assert(sizeof(BP_PalBossNPCMarker_C_IsAbsoluteRotation) == 0x000008, "Wrong size on BP_PalBossNPCMarker_C_IsAbsoluteRotation");
static_assert(offsetof(BP_PalBossNPCMarker_C_IsAbsoluteRotation, CallFunc_K2_SetTimer_ReturnValue) == 0x000000, "Member 'BP_PalBossNPCMarker_C_IsAbsoluteRotation::CallFunc_K2_SetTimer_ReturnValue' has a wrong offset!");

// Function BP_PalBossNPCMarker.BP_PalBossNPCMarker_C.OnAction
// 0x0008 (0x0008 - 0x0000)
struct BP_PalBossNPCMarker_C_OnAction final
{
public:
	const class UPalActionBase*                   action_0;                                          // 0x0000(0x0008)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_PalBossNPCMarker_C_OnAction) == 0x000008, "Wrong alignment on BP_PalBossNPCMarker_C_OnAction");
static_assert(sizeof(BP_PalBossNPCMarker_C_OnAction) == 0x000008, "Wrong size on BP_PalBossNPCMarker_C_OnAction");
static_assert(offsetof(BP_PalBossNPCMarker_C_OnAction, action_0) == 0x000000, "Member 'BP_PalBossNPCMarker_C_OnAction::action_0' has a wrong offset!");

// Function BP_PalBossNPCMarker.BP_PalBossNPCMarker_C.OnAnyAction_
// 0x0008 (0x0008 - 0x0000)
struct BP_PalBossNPCMarker_C_OnAnyAction_ final
{
public:
	class UPalActionBase*                         action_0;                                          // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_PalBossNPCMarker_C_OnAnyAction_) == 0x000008, "Wrong alignment on BP_PalBossNPCMarker_C_OnAnyAction_");
static_assert(sizeof(BP_PalBossNPCMarker_C_OnAnyAction_) == 0x000008, "Wrong size on BP_PalBossNPCMarker_C_OnAnyAction_");
static_assert(offsetof(BP_PalBossNPCMarker_C_OnAnyAction_, action_0) == 0x000000, "Member 'BP_PalBossNPCMarker_C_OnAnyAction_::action_0' has a wrong offset!");

// Function BP_PalBossNPCMarker.BP_PalBossNPCMarker_C.OnBlendOut_1FADD12E42BDE1A6BBA9A5942B550B40
// 0x0008 (0x0008 - 0x0000)
struct BP_PalBossNPCMarker_C_OnBlendOut_1FADD12E42BDE1A6BBA9A5942B550B40 final
{
public:
	class FName                                   NotifyName;                                        // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_PalBossNPCMarker_C_OnBlendOut_1FADD12E42BDE1A6BBA9A5942B550B40) == 0x000004, "Wrong alignment on BP_PalBossNPCMarker_C_OnBlendOut_1FADD12E42BDE1A6BBA9A5942B550B40");
static_assert(sizeof(BP_PalBossNPCMarker_C_OnBlendOut_1FADD12E42BDE1A6BBA9A5942B550B40) == 0x000008, "Wrong size on BP_PalBossNPCMarker_C_OnBlendOut_1FADD12E42BDE1A6BBA9A5942B550B40");
static_assert(offsetof(BP_PalBossNPCMarker_C_OnBlendOut_1FADD12E42BDE1A6BBA9A5942B550B40, NotifyName) == 0x000000, "Member 'BP_PalBossNPCMarker_C_OnBlendOut_1FADD12E42BDE1A6BBA9A5942B550B40::NotifyName' has a wrong offset!");

// Function BP_PalBossNPCMarker.BP_PalBossNPCMarker_C.OnBlendOut_3695005744180F167B404E8D464E2EA8
// 0x0008 (0x0008 - 0x0000)
struct BP_PalBossNPCMarker_C_OnBlendOut_3695005744180F167B404E8D464E2EA8 final
{
public:
	class FName                                   NotifyName;                                        // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_PalBossNPCMarker_C_OnBlendOut_3695005744180F167B404E8D464E2EA8) == 0x000004, "Wrong alignment on BP_PalBossNPCMarker_C_OnBlendOut_3695005744180F167B404E8D464E2EA8");
static_assert(sizeof(BP_PalBossNPCMarker_C_OnBlendOut_3695005744180F167B404E8D464E2EA8) == 0x000008, "Wrong size on BP_PalBossNPCMarker_C_OnBlendOut_3695005744180F167B404E8D464E2EA8");
static_assert(offsetof(BP_PalBossNPCMarker_C_OnBlendOut_3695005744180F167B404E8D464E2EA8, NotifyName) == 0x000000, "Member 'BP_PalBossNPCMarker_C_OnBlendOut_3695005744180F167B404E8D464E2EA8::NotifyName' has a wrong offset!");

// Function BP_PalBossNPCMarker.BP_PalBossNPCMarker_C.OnBlendOut_79DC72A149AE065376517699E9FF8157
// 0x0008 (0x0008 - 0x0000)
struct BP_PalBossNPCMarker_C_OnBlendOut_79DC72A149AE065376517699E9FF8157 final
{
public:
	class FName                                   NotifyName;                                        // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_PalBossNPCMarker_C_OnBlendOut_79DC72A149AE065376517699E9FF8157) == 0x000004, "Wrong alignment on BP_PalBossNPCMarker_C_OnBlendOut_79DC72A149AE065376517699E9FF8157");
static_assert(sizeof(BP_PalBossNPCMarker_C_OnBlendOut_79DC72A149AE065376517699E9FF8157) == 0x000008, "Wrong size on BP_PalBossNPCMarker_C_OnBlendOut_79DC72A149AE065376517699E9FF8157");
static_assert(offsetof(BP_PalBossNPCMarker_C_OnBlendOut_79DC72A149AE065376517699E9FF8157, NotifyName) == 0x000000, "Member 'BP_PalBossNPCMarker_C_OnBlendOut_79DC72A149AE065376517699E9FF8157::NotifyName' has a wrong offset!");

// Function BP_PalBossNPCMarker.BP_PalBossNPCMarker_C.OnBlendOut_DEAF772043DFD4BDE4BE3D9B4DB706D9
// 0x0008 (0x0008 - 0x0000)
struct BP_PalBossNPCMarker_C_OnBlendOut_DEAF772043DFD4BDE4BE3D9B4DB706D9 final
{
public:
	class FName                                   NotifyName;                                        // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_PalBossNPCMarker_C_OnBlendOut_DEAF772043DFD4BDE4BE3D9B4DB706D9) == 0x000004, "Wrong alignment on BP_PalBossNPCMarker_C_OnBlendOut_DEAF772043DFD4BDE4BE3D9B4DB706D9");
static_assert(sizeof(BP_PalBossNPCMarker_C_OnBlendOut_DEAF772043DFD4BDE4BE3D9B4DB706D9) == 0x000008, "Wrong size on BP_PalBossNPCMarker_C_OnBlendOut_DEAF772043DFD4BDE4BE3D9B4DB706D9");
static_assert(offsetof(BP_PalBossNPCMarker_C_OnBlendOut_DEAF772043DFD4BDE4BE3D9B4DB706D9, NotifyName) == 0x000000, "Member 'BP_PalBossNPCMarker_C_OnBlendOut_DEAF772043DFD4BDE4BE3D9B4DB706D9::NotifyName' has a wrong offset!");

// Function BP_PalBossNPCMarker.BP_PalBossNPCMarker_C.OnCompleted_1FADD12E42BDE1A6BBA9A5942B550B40
// 0x0008 (0x0008 - 0x0000)
struct BP_PalBossNPCMarker_C_OnCompleted_1FADD12E42BDE1A6BBA9A5942B550B40 final
{
public:
	class FName                                   NotifyName;                                        // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_PalBossNPCMarker_C_OnCompleted_1FADD12E42BDE1A6BBA9A5942B550B40) == 0x000004, "Wrong alignment on BP_PalBossNPCMarker_C_OnCompleted_1FADD12E42BDE1A6BBA9A5942B550B40");
static_assert(sizeof(BP_PalBossNPCMarker_C_OnCompleted_1FADD12E42BDE1A6BBA9A5942B550B40) == 0x000008, "Wrong size on BP_PalBossNPCMarker_C_OnCompleted_1FADD12E42BDE1A6BBA9A5942B550B40");
static_assert(offsetof(BP_PalBossNPCMarker_C_OnCompleted_1FADD12E42BDE1A6BBA9A5942B550B40, NotifyName) == 0x000000, "Member 'BP_PalBossNPCMarker_C_OnCompleted_1FADD12E42BDE1A6BBA9A5942B550B40::NotifyName' has a wrong offset!");

// Function BP_PalBossNPCMarker.BP_PalBossNPCMarker_C.OnCompleted_3695005744180F167B404E8D464E2EA8
// 0x0008 (0x0008 - 0x0000)
struct BP_PalBossNPCMarker_C_OnCompleted_3695005744180F167B404E8D464E2EA8 final
{
public:
	class FName                                   NotifyName;                                        // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_PalBossNPCMarker_C_OnCompleted_3695005744180F167B404E8D464E2EA8) == 0x000004, "Wrong alignment on BP_PalBossNPCMarker_C_OnCompleted_3695005744180F167B404E8D464E2EA8");
static_assert(sizeof(BP_PalBossNPCMarker_C_OnCompleted_3695005744180F167B404E8D464E2EA8) == 0x000008, "Wrong size on BP_PalBossNPCMarker_C_OnCompleted_3695005744180F167B404E8D464E2EA8");
static_assert(offsetof(BP_PalBossNPCMarker_C_OnCompleted_3695005744180F167B404E8D464E2EA8, NotifyName) == 0x000000, "Member 'BP_PalBossNPCMarker_C_OnCompleted_3695005744180F167B404E8D464E2EA8::NotifyName' has a wrong offset!");

// Function BP_PalBossNPCMarker.BP_PalBossNPCMarker_C.OnCompleted_79DC72A149AE065376517699E9FF8157
// 0x0008 (0x0008 - 0x0000)
struct BP_PalBossNPCMarker_C_OnCompleted_79DC72A149AE065376517699E9FF8157 final
{
public:
	class FName                                   NotifyName;                                        // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_PalBossNPCMarker_C_OnCompleted_79DC72A149AE065376517699E9FF8157) == 0x000004, "Wrong alignment on BP_PalBossNPCMarker_C_OnCompleted_79DC72A149AE065376517699E9FF8157");
static_assert(sizeof(BP_PalBossNPCMarker_C_OnCompleted_79DC72A149AE065376517699E9FF8157) == 0x000008, "Wrong size on BP_PalBossNPCMarker_C_OnCompleted_79DC72A149AE065376517699E9FF8157");
static_assert(offsetof(BP_PalBossNPCMarker_C_OnCompleted_79DC72A149AE065376517699E9FF8157, NotifyName) == 0x000000, "Member 'BP_PalBossNPCMarker_C_OnCompleted_79DC72A149AE065376517699E9FF8157::NotifyName' has a wrong offset!");

// Function BP_PalBossNPCMarker.BP_PalBossNPCMarker_C.OnCompleted_DEAF772043DFD4BDE4BE3D9B4DB706D9
// 0x0008 (0x0008 - 0x0000)
struct BP_PalBossNPCMarker_C_OnCompleted_DEAF772043DFD4BDE4BE3D9B4DB706D9 final
{
public:
	class FName                                   NotifyName;                                        // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_PalBossNPCMarker_C_OnCompleted_DEAF772043DFD4BDE4BE3D9B4DB706D9) == 0x000004, "Wrong alignment on BP_PalBossNPCMarker_C_OnCompleted_DEAF772043DFD4BDE4BE3D9B4DB706D9");
static_assert(sizeof(BP_PalBossNPCMarker_C_OnCompleted_DEAF772043DFD4BDE4BE3D9B4DB706D9) == 0x000008, "Wrong size on BP_PalBossNPCMarker_C_OnCompleted_DEAF772043DFD4BDE4BE3D9B4DB706D9");
static_assert(offsetof(BP_PalBossNPCMarker_C_OnCompleted_DEAF772043DFD4BDE4BE3D9B4DB706D9, NotifyName) == 0x000000, "Member 'BP_PalBossNPCMarker_C_OnCompleted_DEAF772043DFD4BDE4BE3D9B4DB706D9::NotifyName' has a wrong offset!");

// Function BP_PalBossNPCMarker.BP_PalBossNPCMarker_C.OnInterrupted_1FADD12E42BDE1A6BBA9A5942B550B40
// 0x0008 (0x0008 - 0x0000)
struct BP_PalBossNPCMarker_C_OnInterrupted_1FADD12E42BDE1A6BBA9A5942B550B40 final
{
public:
	class FName                                   NotifyName;                                        // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_PalBossNPCMarker_C_OnInterrupted_1FADD12E42BDE1A6BBA9A5942B550B40) == 0x000004, "Wrong alignment on BP_PalBossNPCMarker_C_OnInterrupted_1FADD12E42BDE1A6BBA9A5942B550B40");
static_assert(sizeof(BP_PalBossNPCMarker_C_OnInterrupted_1FADD12E42BDE1A6BBA9A5942B550B40) == 0x000008, "Wrong size on BP_PalBossNPCMarker_C_OnInterrupted_1FADD12E42BDE1A6BBA9A5942B550B40");
static_assert(offsetof(BP_PalBossNPCMarker_C_OnInterrupted_1FADD12E42BDE1A6BBA9A5942B550B40, NotifyName) == 0x000000, "Member 'BP_PalBossNPCMarker_C_OnInterrupted_1FADD12E42BDE1A6BBA9A5942B550B40::NotifyName' has a wrong offset!");

// Function BP_PalBossNPCMarker.BP_PalBossNPCMarker_C.OnInterrupted_3695005744180F167B404E8D464E2EA8
// 0x0008 (0x0008 - 0x0000)
struct BP_PalBossNPCMarker_C_OnInterrupted_3695005744180F167B404E8D464E2EA8 final
{
public:
	class FName                                   NotifyName;                                        // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_PalBossNPCMarker_C_OnInterrupted_3695005744180F167B404E8D464E2EA8) == 0x000004, "Wrong alignment on BP_PalBossNPCMarker_C_OnInterrupted_3695005744180F167B404E8D464E2EA8");
static_assert(sizeof(BP_PalBossNPCMarker_C_OnInterrupted_3695005744180F167B404E8D464E2EA8) == 0x000008, "Wrong size on BP_PalBossNPCMarker_C_OnInterrupted_3695005744180F167B404E8D464E2EA8");
static_assert(offsetof(BP_PalBossNPCMarker_C_OnInterrupted_3695005744180F167B404E8D464E2EA8, NotifyName) == 0x000000, "Member 'BP_PalBossNPCMarker_C_OnInterrupted_3695005744180F167B404E8D464E2EA8::NotifyName' has a wrong offset!");

// Function BP_PalBossNPCMarker.BP_PalBossNPCMarker_C.OnInterrupted_79DC72A149AE065376517699E9FF8157
// 0x0008 (0x0008 - 0x0000)
struct BP_PalBossNPCMarker_C_OnInterrupted_79DC72A149AE065376517699E9FF8157 final
{
public:
	class FName                                   NotifyName;                                        // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_PalBossNPCMarker_C_OnInterrupted_79DC72A149AE065376517699E9FF8157) == 0x000004, "Wrong alignment on BP_PalBossNPCMarker_C_OnInterrupted_79DC72A149AE065376517699E9FF8157");
static_assert(sizeof(BP_PalBossNPCMarker_C_OnInterrupted_79DC72A149AE065376517699E9FF8157) == 0x000008, "Wrong size on BP_PalBossNPCMarker_C_OnInterrupted_79DC72A149AE065376517699E9FF8157");
static_assert(offsetof(BP_PalBossNPCMarker_C_OnInterrupted_79DC72A149AE065376517699E9FF8157, NotifyName) == 0x000000, "Member 'BP_PalBossNPCMarker_C_OnInterrupted_79DC72A149AE065376517699E9FF8157::NotifyName' has a wrong offset!");

// Function BP_PalBossNPCMarker.BP_PalBossNPCMarker_C.OnInterrupted_DEAF772043DFD4BDE4BE3D9B4DB706D9
// 0x0008 (0x0008 - 0x0000)
struct BP_PalBossNPCMarker_C_OnInterrupted_DEAF772043DFD4BDE4BE3D9B4DB706D9 final
{
public:
	class FName                                   NotifyName;                                        // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_PalBossNPCMarker_C_OnInterrupted_DEAF772043DFD4BDE4BE3D9B4DB706D9) == 0x000004, "Wrong alignment on BP_PalBossNPCMarker_C_OnInterrupted_DEAF772043DFD4BDE4BE3D9B4DB706D9");
static_assert(sizeof(BP_PalBossNPCMarker_C_OnInterrupted_DEAF772043DFD4BDE4BE3D9B4DB706D9) == 0x000008, "Wrong size on BP_PalBossNPCMarker_C_OnInterrupted_DEAF772043DFD4BDE4BE3D9B4DB706D9");
static_assert(offsetof(BP_PalBossNPCMarker_C_OnInterrupted_DEAF772043DFD4BDE4BE3D9B4DB706D9, NotifyName) == 0x000000, "Member 'BP_PalBossNPCMarker_C_OnInterrupted_DEAF772043DFD4BDE4BE3D9B4DB706D9::NotifyName' has a wrong offset!");

// Function BP_PalBossNPCMarker.BP_PalBossNPCMarker_C.OnNotifyBegin_1FADD12E42BDE1A6BBA9A5942B550B40
// 0x0008 (0x0008 - 0x0000)
struct BP_PalBossNPCMarker_C_OnNotifyBegin_1FADD12E42BDE1A6BBA9A5942B550B40 final
{
public:
	class FName                                   NotifyName;                                        // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_PalBossNPCMarker_C_OnNotifyBegin_1FADD12E42BDE1A6BBA9A5942B550B40) == 0x000004, "Wrong alignment on BP_PalBossNPCMarker_C_OnNotifyBegin_1FADD12E42BDE1A6BBA9A5942B550B40");
static_assert(sizeof(BP_PalBossNPCMarker_C_OnNotifyBegin_1FADD12E42BDE1A6BBA9A5942B550B40) == 0x000008, "Wrong size on BP_PalBossNPCMarker_C_OnNotifyBegin_1FADD12E42BDE1A6BBA9A5942B550B40");
static_assert(offsetof(BP_PalBossNPCMarker_C_OnNotifyBegin_1FADD12E42BDE1A6BBA9A5942B550B40, NotifyName) == 0x000000, "Member 'BP_PalBossNPCMarker_C_OnNotifyBegin_1FADD12E42BDE1A6BBA9A5942B550B40::NotifyName' has a wrong offset!");

// Function BP_PalBossNPCMarker.BP_PalBossNPCMarker_C.OnNotifyBegin_3695005744180F167B404E8D464E2EA8
// 0x0008 (0x0008 - 0x0000)
struct BP_PalBossNPCMarker_C_OnNotifyBegin_3695005744180F167B404E8D464E2EA8 final
{
public:
	class FName                                   NotifyName;                                        // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_PalBossNPCMarker_C_OnNotifyBegin_3695005744180F167B404E8D464E2EA8) == 0x000004, "Wrong alignment on BP_PalBossNPCMarker_C_OnNotifyBegin_3695005744180F167B404E8D464E2EA8");
static_assert(sizeof(BP_PalBossNPCMarker_C_OnNotifyBegin_3695005744180F167B404E8D464E2EA8) == 0x000008, "Wrong size on BP_PalBossNPCMarker_C_OnNotifyBegin_3695005744180F167B404E8D464E2EA8");
static_assert(offsetof(BP_PalBossNPCMarker_C_OnNotifyBegin_3695005744180F167B404E8D464E2EA8, NotifyName) == 0x000000, "Member 'BP_PalBossNPCMarker_C_OnNotifyBegin_3695005744180F167B404E8D464E2EA8::NotifyName' has a wrong offset!");

// Function BP_PalBossNPCMarker.BP_PalBossNPCMarker_C.OnNotifyBegin_79DC72A149AE065376517699E9FF8157
// 0x0008 (0x0008 - 0x0000)
struct BP_PalBossNPCMarker_C_OnNotifyBegin_79DC72A149AE065376517699E9FF8157 final
{
public:
	class FName                                   NotifyName;                                        // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_PalBossNPCMarker_C_OnNotifyBegin_79DC72A149AE065376517699E9FF8157) == 0x000004, "Wrong alignment on BP_PalBossNPCMarker_C_OnNotifyBegin_79DC72A149AE065376517699E9FF8157");
static_assert(sizeof(BP_PalBossNPCMarker_C_OnNotifyBegin_79DC72A149AE065376517699E9FF8157) == 0x000008, "Wrong size on BP_PalBossNPCMarker_C_OnNotifyBegin_79DC72A149AE065376517699E9FF8157");
static_assert(offsetof(BP_PalBossNPCMarker_C_OnNotifyBegin_79DC72A149AE065376517699E9FF8157, NotifyName) == 0x000000, "Member 'BP_PalBossNPCMarker_C_OnNotifyBegin_79DC72A149AE065376517699E9FF8157::NotifyName' has a wrong offset!");

// Function BP_PalBossNPCMarker.BP_PalBossNPCMarker_C.OnNotifyBegin_DEAF772043DFD4BDE4BE3D9B4DB706D9
// 0x0008 (0x0008 - 0x0000)
struct BP_PalBossNPCMarker_C_OnNotifyBegin_DEAF772043DFD4BDE4BE3D9B4DB706D9 final
{
public:
	class FName                                   NotifyName;                                        // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_PalBossNPCMarker_C_OnNotifyBegin_DEAF772043DFD4BDE4BE3D9B4DB706D9) == 0x000004, "Wrong alignment on BP_PalBossNPCMarker_C_OnNotifyBegin_DEAF772043DFD4BDE4BE3D9B4DB706D9");
static_assert(sizeof(BP_PalBossNPCMarker_C_OnNotifyBegin_DEAF772043DFD4BDE4BE3D9B4DB706D9) == 0x000008, "Wrong size on BP_PalBossNPCMarker_C_OnNotifyBegin_DEAF772043DFD4BDE4BE3D9B4DB706D9");
static_assert(offsetof(BP_PalBossNPCMarker_C_OnNotifyBegin_DEAF772043DFD4BDE4BE3D9B4DB706D9, NotifyName) == 0x000000, "Member 'BP_PalBossNPCMarker_C_OnNotifyBegin_DEAF772043DFD4BDE4BE3D9B4DB706D9::NotifyName' has a wrong offset!");

// Function BP_PalBossNPCMarker.BP_PalBossNPCMarker_C.OnNotifyEnd_1FADD12E42BDE1A6BBA9A5942B550B40
// 0x0008 (0x0008 - 0x0000)
struct BP_PalBossNPCMarker_C_OnNotifyEnd_1FADD12E42BDE1A6BBA9A5942B550B40 final
{
public:
	class FName                                   NotifyName;                                        // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_PalBossNPCMarker_C_OnNotifyEnd_1FADD12E42BDE1A6BBA9A5942B550B40) == 0x000004, "Wrong alignment on BP_PalBossNPCMarker_C_OnNotifyEnd_1FADD12E42BDE1A6BBA9A5942B550B40");
static_assert(sizeof(BP_PalBossNPCMarker_C_OnNotifyEnd_1FADD12E42BDE1A6BBA9A5942B550B40) == 0x000008, "Wrong size on BP_PalBossNPCMarker_C_OnNotifyEnd_1FADD12E42BDE1A6BBA9A5942B550B40");
static_assert(offsetof(BP_PalBossNPCMarker_C_OnNotifyEnd_1FADD12E42BDE1A6BBA9A5942B550B40, NotifyName) == 0x000000, "Member 'BP_PalBossNPCMarker_C_OnNotifyEnd_1FADD12E42BDE1A6BBA9A5942B550B40::NotifyName' has a wrong offset!");

// Function BP_PalBossNPCMarker.BP_PalBossNPCMarker_C.OnNotifyEnd_3695005744180F167B404E8D464E2EA8
// 0x0008 (0x0008 - 0x0000)
struct BP_PalBossNPCMarker_C_OnNotifyEnd_3695005744180F167B404E8D464E2EA8 final
{
public:
	class FName                                   NotifyName;                                        // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_PalBossNPCMarker_C_OnNotifyEnd_3695005744180F167B404E8D464E2EA8) == 0x000004, "Wrong alignment on BP_PalBossNPCMarker_C_OnNotifyEnd_3695005744180F167B404E8D464E2EA8");
static_assert(sizeof(BP_PalBossNPCMarker_C_OnNotifyEnd_3695005744180F167B404E8D464E2EA8) == 0x000008, "Wrong size on BP_PalBossNPCMarker_C_OnNotifyEnd_3695005744180F167B404E8D464E2EA8");
static_assert(offsetof(BP_PalBossNPCMarker_C_OnNotifyEnd_3695005744180F167B404E8D464E2EA8, NotifyName) == 0x000000, "Member 'BP_PalBossNPCMarker_C_OnNotifyEnd_3695005744180F167B404E8D464E2EA8::NotifyName' has a wrong offset!");

// Function BP_PalBossNPCMarker.BP_PalBossNPCMarker_C.OnNotifyEnd_79DC72A149AE065376517699E9FF8157
// 0x0008 (0x0008 - 0x0000)
struct BP_PalBossNPCMarker_C_OnNotifyEnd_79DC72A149AE065376517699E9FF8157 final
{
public:
	class FName                                   NotifyName;                                        // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_PalBossNPCMarker_C_OnNotifyEnd_79DC72A149AE065376517699E9FF8157) == 0x000004, "Wrong alignment on BP_PalBossNPCMarker_C_OnNotifyEnd_79DC72A149AE065376517699E9FF8157");
static_assert(sizeof(BP_PalBossNPCMarker_C_OnNotifyEnd_79DC72A149AE065376517699E9FF8157) == 0x000008, "Wrong size on BP_PalBossNPCMarker_C_OnNotifyEnd_79DC72A149AE065376517699E9FF8157");
static_assert(offsetof(BP_PalBossNPCMarker_C_OnNotifyEnd_79DC72A149AE065376517699E9FF8157, NotifyName) == 0x000000, "Member 'BP_PalBossNPCMarker_C_OnNotifyEnd_79DC72A149AE065376517699E9FF8157::NotifyName' has a wrong offset!");

// Function BP_PalBossNPCMarker.BP_PalBossNPCMarker_C.OnNotifyEnd_DEAF772043DFD4BDE4BE3D9B4DB706D9
// 0x0008 (0x0008 - 0x0000)
struct BP_PalBossNPCMarker_C_OnNotifyEnd_DEAF772043DFD4BDE4BE3D9B4DB706D9 final
{
public:
	class FName                                   NotifyName;                                        // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_PalBossNPCMarker_C_OnNotifyEnd_DEAF772043DFD4BDE4BE3D9B4DB706D9) == 0x000004, "Wrong alignment on BP_PalBossNPCMarker_C_OnNotifyEnd_DEAF772043DFD4BDE4BE3D9B4DB706D9");
static_assert(sizeof(BP_PalBossNPCMarker_C_OnNotifyEnd_DEAF772043DFD4BDE4BE3D9B4DB706D9) == 0x000008, "Wrong size on BP_PalBossNPCMarker_C_OnNotifyEnd_DEAF772043DFD4BDE4BE3D9B4DB706D9");
static_assert(offsetof(BP_PalBossNPCMarker_C_OnNotifyEnd_DEAF772043DFD4BDE4BE3D9B4DB706D9, NotifyName) == 0x000000, "Member 'BP_PalBossNPCMarker_C_OnNotifyEnd_DEAF772043DFD4BDE4BE3D9B4DB706D9::NotifyName' has a wrong offset!");

// Function BP_PalBossNPCMarker.BP_PalBossNPCMarker_C.OnWaza
// 0x00B0 (0x00B0 - 0x0000)
struct BP_PalBossNPCMarker_C_OnWaza final
{
public:
	const class UObject*                          Object;                                            // 0x0000(0x0008)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	EPalWazaID                                    NewLocalVar;                                       // 0x0008(0x0002)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_A[0x2];                                        // 0x000A(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         Temp_int_Array_Index_Variable;                     // 0x000C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Loop_Counter_Variable;                    // 0x0010(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Add_IntInt_ReturnValue;                   // 0x0014(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UAnimInstance*                          CallFunc_GetAnimInstance_ReturnValue;              // 0x0018(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class UAnimMontage*                           CallFunc_Map_Find_Value;                           // 0x0020(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Map_Find_ReturnValue;                     // 0x0028(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_29[0x7];                                       // 0x0029(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UClass*                                 CallFunc_GetObjectClass_ReturnValue;               // 0x0030(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_Montage_Play_ReturnValue;                 // 0x0038(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_3C[0x4];                                       // 0x003C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class AActor*                                 CallFunc_GetOwner_ReturnValue;                     // 0x0040(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class UPalStaticCharacterParameterComponent*  CallFunc_GetComponentByClass_ReturnValue;          // 0x0048(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	TArray<EPalWazaID>                            CallFunc_Map_Keys_Keys;                            // 0x0050(0x0010)(ReferenceParm)
	EPalWazaID                                    CallFunc_Array_Get_Item;                           // 0x0060(0x0002)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_62[0x2];                                       // 0x0062(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_Array_Length_ReturnValue;                 // 0x0064(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TSoftClassPtr<class UClass>                   CallFunc_Map_Find_Value_1;                         // 0x0068(0x0030)(UObjectWrapper, HasGetValueTypeHash)
	bool                                          CallFunc_Map_Find_ReturnValue_1;                   // 0x0098(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Less_IntInt_ReturnValue;                  // 0x0099(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_9A[0x6];                                       // 0x009A(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	class UClass*                                 CallFunc_LoadClassAsset_Blocking_ReturnValue;      // 0x00A0(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_EqualEqual_ClassClass_ReturnValue;        // 0x00A8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_PalBossNPCMarker_C_OnWaza) == 0x000008, "Wrong alignment on BP_PalBossNPCMarker_C_OnWaza");
static_assert(sizeof(BP_PalBossNPCMarker_C_OnWaza) == 0x0000B0, "Wrong size on BP_PalBossNPCMarker_C_OnWaza");
static_assert(offsetof(BP_PalBossNPCMarker_C_OnWaza, Object) == 0x000000, "Member 'BP_PalBossNPCMarker_C_OnWaza::Object' has a wrong offset!");
static_assert(offsetof(BP_PalBossNPCMarker_C_OnWaza, NewLocalVar) == 0x000008, "Member 'BP_PalBossNPCMarker_C_OnWaza::NewLocalVar' has a wrong offset!");
static_assert(offsetof(BP_PalBossNPCMarker_C_OnWaza, Temp_int_Array_Index_Variable) == 0x00000C, "Member 'BP_PalBossNPCMarker_C_OnWaza::Temp_int_Array_Index_Variable' has a wrong offset!");
static_assert(offsetof(BP_PalBossNPCMarker_C_OnWaza, Temp_int_Loop_Counter_Variable) == 0x000010, "Member 'BP_PalBossNPCMarker_C_OnWaza::Temp_int_Loop_Counter_Variable' has a wrong offset!");
static_assert(offsetof(BP_PalBossNPCMarker_C_OnWaza, CallFunc_Add_IntInt_ReturnValue) == 0x000014, "Member 'BP_PalBossNPCMarker_C_OnWaza::CallFunc_Add_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_PalBossNPCMarker_C_OnWaza, CallFunc_GetAnimInstance_ReturnValue) == 0x000018, "Member 'BP_PalBossNPCMarker_C_OnWaza::CallFunc_GetAnimInstance_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_PalBossNPCMarker_C_OnWaza, CallFunc_Map_Find_Value) == 0x000020, "Member 'BP_PalBossNPCMarker_C_OnWaza::CallFunc_Map_Find_Value' has a wrong offset!");
static_assert(offsetof(BP_PalBossNPCMarker_C_OnWaza, CallFunc_Map_Find_ReturnValue) == 0x000028, "Member 'BP_PalBossNPCMarker_C_OnWaza::CallFunc_Map_Find_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_PalBossNPCMarker_C_OnWaza, CallFunc_GetObjectClass_ReturnValue) == 0x000030, "Member 'BP_PalBossNPCMarker_C_OnWaza::CallFunc_GetObjectClass_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_PalBossNPCMarker_C_OnWaza, CallFunc_Montage_Play_ReturnValue) == 0x000038, "Member 'BP_PalBossNPCMarker_C_OnWaza::CallFunc_Montage_Play_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_PalBossNPCMarker_C_OnWaza, CallFunc_GetOwner_ReturnValue) == 0x000040, "Member 'BP_PalBossNPCMarker_C_OnWaza::CallFunc_GetOwner_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_PalBossNPCMarker_C_OnWaza, CallFunc_GetComponentByClass_ReturnValue) == 0x000048, "Member 'BP_PalBossNPCMarker_C_OnWaza::CallFunc_GetComponentByClass_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_PalBossNPCMarker_C_OnWaza, CallFunc_Map_Keys_Keys) == 0x000050, "Member 'BP_PalBossNPCMarker_C_OnWaza::CallFunc_Map_Keys_Keys' has a wrong offset!");
static_assert(offsetof(BP_PalBossNPCMarker_C_OnWaza, CallFunc_Array_Get_Item) == 0x000060, "Member 'BP_PalBossNPCMarker_C_OnWaza::CallFunc_Array_Get_Item' has a wrong offset!");
static_assert(offsetof(BP_PalBossNPCMarker_C_OnWaza, CallFunc_Array_Length_ReturnValue) == 0x000064, "Member 'BP_PalBossNPCMarker_C_OnWaza::CallFunc_Array_Length_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_PalBossNPCMarker_C_OnWaza, CallFunc_Map_Find_Value_1) == 0x000068, "Member 'BP_PalBossNPCMarker_C_OnWaza::CallFunc_Map_Find_Value_1' has a wrong offset!");
static_assert(offsetof(BP_PalBossNPCMarker_C_OnWaza, CallFunc_Map_Find_ReturnValue_1) == 0x000098, "Member 'BP_PalBossNPCMarker_C_OnWaza::CallFunc_Map_Find_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_PalBossNPCMarker_C_OnWaza, CallFunc_Less_IntInt_ReturnValue) == 0x000099, "Member 'BP_PalBossNPCMarker_C_OnWaza::CallFunc_Less_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_PalBossNPCMarker_C_OnWaza, CallFunc_LoadClassAsset_Blocking_ReturnValue) == 0x0000A0, "Member 'BP_PalBossNPCMarker_C_OnWaza::CallFunc_LoadClassAsset_Blocking_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_PalBossNPCMarker_C_OnWaza, CallFunc_EqualEqual_ClassClass_ReturnValue) == 0x0000A8, "Member 'BP_PalBossNPCMarker_C_OnWaza::CallFunc_EqualEqual_ClassClass_ReturnValue' has a wrong offset!");

// Function BP_PalBossNPCMarker.BP_PalBossNPCMarker_C.SetRotation
// 0x0130 (0x0130 - 0x0000)
struct BP_PalBossNPCMarker_C_SetRotation final
{
public:
	class USceneComponent*                        CallFunc_GetAttachParent_ReturnValue;              // 0x0000(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	struct FRotator                               CallFunc_K2_GetComponentRotation_ReturnValue;      // 0x0008(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor)
	float                                         CallFunc_BreakRotator_Roll;                        // 0x0020(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_BreakRotator_Pitch;                       // 0x0024(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_BreakRotator_Yaw;                         // 0x0028(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_2C[0x4];                                       // 0x002C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	struct FRotator                               CallFunc_MakeRotator_ReturnValue;                  // 0x0030(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor)
	struct FHitResult                             CallFunc_K2_SetWorldRotation_SweepHitResult;       // 0x0048(0x00E8)(IsPlainOldData, NoDestructor, ContainsInstancedReference)
};
static_assert(alignof(BP_PalBossNPCMarker_C_SetRotation) == 0x000008, "Wrong alignment on BP_PalBossNPCMarker_C_SetRotation");
static_assert(sizeof(BP_PalBossNPCMarker_C_SetRotation) == 0x000130, "Wrong size on BP_PalBossNPCMarker_C_SetRotation");
static_assert(offsetof(BP_PalBossNPCMarker_C_SetRotation, CallFunc_GetAttachParent_ReturnValue) == 0x000000, "Member 'BP_PalBossNPCMarker_C_SetRotation::CallFunc_GetAttachParent_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_PalBossNPCMarker_C_SetRotation, CallFunc_K2_GetComponentRotation_ReturnValue) == 0x000008, "Member 'BP_PalBossNPCMarker_C_SetRotation::CallFunc_K2_GetComponentRotation_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_PalBossNPCMarker_C_SetRotation, CallFunc_BreakRotator_Roll) == 0x000020, "Member 'BP_PalBossNPCMarker_C_SetRotation::CallFunc_BreakRotator_Roll' has a wrong offset!");
static_assert(offsetof(BP_PalBossNPCMarker_C_SetRotation, CallFunc_BreakRotator_Pitch) == 0x000024, "Member 'BP_PalBossNPCMarker_C_SetRotation::CallFunc_BreakRotator_Pitch' has a wrong offset!");
static_assert(offsetof(BP_PalBossNPCMarker_C_SetRotation, CallFunc_BreakRotator_Yaw) == 0x000028, "Member 'BP_PalBossNPCMarker_C_SetRotation::CallFunc_BreakRotator_Yaw' has a wrong offset!");
static_assert(offsetof(BP_PalBossNPCMarker_C_SetRotation, CallFunc_MakeRotator_ReturnValue) == 0x000030, "Member 'BP_PalBossNPCMarker_C_SetRotation::CallFunc_MakeRotator_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_PalBossNPCMarker_C_SetRotation, CallFunc_K2_SetWorldRotation_SweepHitResult) == 0x000048, "Member 'BP_PalBossNPCMarker_C_SetRotation::CallFunc_K2_SetWorldRotation_SweepHitResult' has a wrong offset!");

}

